// Spacecraft dataset for SpaceTec's Spacecraft Database.
//
// This covers crewed vehicles, cargo craft, space stations, robotic probes,
// landers/rovers and space telescopes — i.e. vehicles that fly beyond a
// launch vehicle's role, as distinct from SpaceTec's separate Rocket
// Database (launch vehicles) and Satellite Database (Earth-orbiting
// satellites). Every entry is built from well-established, publicly
// documented spaceflight history. Fields that aren't reliably known for a
// given spacecraft are simply omitted — the UI renders those as
// "DATA UNAVAILABLE" rather than guessing. Nothing here is fabricated.
//
// `agencyLinkId` matches an id in SpaceTecHub.js's AGENCIES list, so a
// spacecraft profile can deep-link straight to that agency's existing card
// instead of duplicating agency info. Not every manufacturer/operator has
// a matching agency card (e.g. Boeing, Northrop Grumman), in which case
// agencyLinkId is simply omitted and the agency is shown as plain text.

export const TYPE_VALUES = [
  'CREWED CAPSULE',
  'SPACEPLANE',
  'CARGO SPACECRAFT',
  'SPACE STATION',
  'ROBOTIC PROBE',
  'LANDER',
  'ROVER',
  'SPACE TELESCOPE',
];

export const STATUS_VALUES = ['ACTIVE', 'RETIRED', 'IN DEVELOPMENT'];

export const SPACECRAFT = [
  {
    id: 'iss',
    name: 'International Space Station',
    manufacturer: 'Multi-agency (Boeing, RKK Energia, Thales Alenia Space and others)',
    agency: 'NASA / Roscosmos / ESA / JAXA / CSA',
    agencyLinkId: 'nasa',
    type: 'SPACE STATION',
    status: 'ACTIVE',
    crewCapacity: 7,
    firstFlight: '1998-11-20',
    launchVehicles: ['Proton-K', 'Space Shuttle', 'Soyuz'],
    specs: { mass: '~450,000 kg', habitableVolume: '~388 m³', power: '~120 kW (solar arrays)' },
    summary:
      'A modular research station in low Earth orbit, assembled in orbit since 1998 and continuously crewed since November 2000 by rotating international crews.',
    missions: [
      { name: 'Zarya module launch', date: '1998-11-20', launchVehicle: 'Proton-K', description: 'First ISS module reaches orbit, beginning on-orbit assembly.' },
      { name: 'Expedition 1', date: '2000-11-02', launchVehicle: 'Soyuz TM-31', description: 'Start of continuous human presence aboard the station.' },
      { name: 'STS-88 (Unity connection)', date: '1998-12-04', launchVehicle: 'Space Shuttle Endeavour', description: 'Shuttle mission joins the Unity node to Zarya.' },
    ],
  },
  {
    id: 'apollo-csm',
    name: 'Apollo Command/Service Module',
    manufacturer: 'North American Rockwell',
    agency: 'NASA',
    agencyLinkId: 'nasa',
    type: 'CREWED CAPSULE',
    status: 'RETIRED',
    crewCapacity: 3,
    firstFlight: '1968-10-11',
    launchVehicles: ['Saturn IB', 'Saturn V'],
    specs: { mass: '~30,300 kg (fully fueled CSM)', length: '~11 m (CSM stack)' },
    summary:
      'The crew capsule and service module that carried astronauts to lunar orbit and back during the Apollo program, and later flew Skylab and Apollo-Soyuz crews.',
    missions: [
      { name: 'Apollo 7', date: '1968-10-11', launchVehicle: 'Saturn IB', description: 'First crewed Apollo flight, testing the CSM in Earth orbit.' },
      { name: 'Apollo 8', date: '1968-12-21', launchVehicle: 'Saturn V', description: 'First crewed spacecraft to orbit the Moon.' },
      { name: 'Apollo 11', date: '1969-07-16', launchVehicle: 'Saturn V', description: 'Carried the crew of the first crewed Moon landing to and from lunar orbit.' },
      { name: 'Apollo 13', date: '1970-04-11', launchVehicle: 'Saturn V', description: 'Served as lifeboat support alongside the Lunar Module after an in-flight oxygen tank failure.' },
      { name: 'Apollo-Soyuz Test Project', date: '1975-07-15', launchVehicle: 'Saturn IB', description: 'Final Apollo CSM flight, docking in orbit with a Soviet Soyuz spacecraft.' },
    ],
  },
  {
    id: 'apollo-lm',
    name: 'Apollo Lunar Module',
    manufacturer: 'Grumman',
    agency: 'NASA',
    agencyLinkId: 'nasa',
    type: 'LANDER',
    status: 'RETIRED',
    crewCapacity: 2,
    firstFlight: '1969-03-03',
    launchVehicles: ['Saturn V'],
    specs: { mass: '~15,100 kg (fully fueled)', height: '~7 m' },
    summary:
      'The two-stage vehicle that carried astronauts from lunar orbit to the Moon\u2019s surface and back during six successful Apollo landings.',
    missions: [
      { name: 'Apollo 9', date: '1969-03-03', launchVehicle: 'Saturn V', description: 'First crewed test of the Lunar Module, in Earth orbit.' },
      { name: 'Apollo 11', date: '1969-07-20', launchVehicle: 'Saturn V', description: 'First crewed lunar landing, at Mare Tranquillitatis.' },
      { name: 'Apollo 17', date: '1972-12-11', launchVehicle: 'Saturn V', description: 'Final crewed lunar landing of the Apollo program.' },
    ],
  },
  {
    id: 'soyuz',
    name: 'Soyuz',
    manufacturer: 'RKK Energia',
    agency: 'Roscosmos',
    agencyLinkId: 'roscosmos',
    type: 'CREWED CAPSULE',
    status: 'ACTIVE',
    crewCapacity: 3,
    firstFlight: '1967-04-23',
    launchVehicles: ['Soyuz rocket'],
    specs: { mass: '~7,150 kg', length: '~7 m' },
    summary:
      'A long-running Soviet-then-Russian crewed spacecraft family that has flown since the 1960s and remains a primary crew ferry to the International Space Station.',
    missions: [
      { name: 'Soyuz 1', date: '1967-04-23', launchVehicle: 'Soyuz rocket', description: 'First crewed flight of the Soyuz spacecraft.' },
      { name: 'Soyuz 19 (Apollo-Soyuz)', date: '1975-07-15', launchVehicle: 'Soyuz rocket', description: 'Docked in orbit with a US Apollo CSM in the first joint US-Soviet human spaceflight.' },
      { name: 'Soyuz TM-31', date: '2000-10-31', launchVehicle: 'Soyuz rocket', description: 'Delivered the first resident crew, Expedition 1, to the ISS.' },
    ],
  },
  {
    id: 'space-shuttle',
    name: 'Space Shuttle',
    manufacturer: 'Rockwell International',
    agency: 'NASA',
    agencyLinkId: 'nasa',
    type: 'SPACEPLANE',
    status: 'RETIRED',
    crewCapacity: 7,
    firstFlight: '1981-04-12',
    launchVehicles: ['Space Shuttle stack (SRBs + External Tank)'],
    specs: { mass: '~78,000 kg (orbiter, unfueled)', length: '~37 m (orbiter)' },
    summary:
      'NASA\u2019s reusable crewed spaceplane fleet, flown 135 times between 1981 and 2011, used to build the ISS and deploy and service major spacecraft including the Hubble Space Telescope.',
    missions: [
      { name: 'STS-1', date: '1981-04-12', launchVehicle: 'Space Shuttle stack', description: 'First orbital flight of the Shuttle program, flown by Columbia.' },
      { name: 'STS-31', date: '1990-04-24', launchVehicle: 'Space Shuttle stack', description: 'Discovery deploys the Hubble Space Telescope.' },
      { name: 'STS-135', date: '2011-07-08', launchVehicle: 'Space Shuttle stack', description: 'Final Shuttle mission, flown by Atlantis.' },
    ],
  },
  {
    id: 'crew-dragon',
    name: 'Crew Dragon',
    manufacturer: 'SpaceX',
    agency: 'SpaceX',
    agencyLinkId: 'spacex',
    type: 'CREWED CAPSULE',
    status: 'ACTIVE',
    crewCapacity: 4,
    firstFlight: '2020-05-30',
    launchVehicles: ['Falcon 9'],
    specs: { mass: '~9,525 kg (dry)', height: '~8.1 m (with trunk)' },
    summary:
      'SpaceX\u2019s reusable crewed capsule, the first commercially built and operated spacecraft to carry astronauts, flying regular NASA crew rotations and private missions.',
    missions: [
      { name: 'Demo-2', date: '2020-05-30', launchVehicle: 'Falcon 9', description: 'First crewed test flight, carrying two NASA astronauts to the ISS.' },
      { name: 'Crew-1', date: '2020-11-16', launchVehicle: 'Falcon 9', description: 'First operational NASA Commercial Crew rotation to the ISS.' },
      { name: 'Polaris Dawn', date: '2024-09-10', launchVehicle: 'Falcon 9', description: 'Private mission that included the first commercial spacewalk.' },
    ],
  },
  {
    id: 'cargo-dragon',
    name: 'Cargo Dragon',
    manufacturer: 'SpaceX',
    agency: 'SpaceX',
    agencyLinkId: 'spacex',
    type: 'CARGO SPACECRAFT',
    status: 'ACTIVE',
    crewCapacity: 0,
    firstFlight: '2020-12-06',
    launchVehicles: ['Falcon 9'],
    specs: { mass: '~6,000 kg (dry)' },
    summary:
      'The uncrewed cargo variant of SpaceX\u2019s Dragon 2 spacecraft, resupplying the ISS under NASA\u2019s Commercial Resupply Services program.',
    missions: [
      { name: 'CRS-21', date: '2020-12-06', launchVehicle: 'Falcon 9', description: 'First flight of the upgraded Cargo Dragon.' },
    ],
  },
  {
    id: 'starliner',
    name: 'CST-100 Starliner',
    manufacturer: 'Boeing',
    agency: 'Boeing / NASA',
    type: 'CREWED CAPSULE',
    status: 'ACTIVE',
    crewCapacity: 4,
    firstFlight: '2019-12-20',
    launchVehicles: ['Atlas V', 'Vulcan Centaur'],
    specs: { mass: '~13,000 kg' },
    summary:
      'Boeing\u2019s crewed capsule developed under NASA\u2019s Commercial Crew Program, which flew its first crewed test flight in 2024.',
    missions: [
      { name: 'Orbital Flight Test', date: '2019-12-20', launchVehicle: 'Atlas V', description: 'Uncrewed test flight that did not reach the planned ISS docking.' },
      { name: 'Crew Flight Test', date: '2024-06-05', launchVehicle: 'Atlas V', description: 'First crewed flight, carrying two NASA astronauts to the ISS.' },
    ],
  },
  {
    id: 'orion',
    name: 'Orion',
    manufacturer: 'Lockheed Martin / Airbus (service module)',
    agency: 'NASA / ESA',
    agencyLinkId: 'nasa',
    type: 'CREWED CAPSULE',
    status: 'ACTIVE',
    crewCapacity: 4,
    firstFlight: '2014-12-05',
    launchVehicles: ['Delta IV Heavy', 'Space Launch System'],
    specs: { mass: '~26,500 kg (fully fueled)' },
    summary:
      'NASA\u2019s deep-space crewed capsule for the Artemis program, built with an ESA-supplied service module, designed to carry astronauts beyond low Earth orbit to the Moon.',
    missions: [
      { name: 'Exploration Flight Test-1', date: '2014-12-05', launchVehicle: 'Delta IV Heavy', description: 'Uncrewed test of the Orion capsule in Earth orbit.' },
      { name: 'Artemis I', date: '2022-11-16', launchVehicle: 'Space Launch System', description: 'Uncrewed flight around the Moon, the first launch of the SLS rocket.' },
    ],
  },
  {
    id: 'shenzhou',
    name: 'Shenzhou',
    manufacturer: 'China Academy of Space Technology (CAST)',
    agency: 'CNSA',
    agencyLinkId: 'cnsa',
    type: 'CREWED CAPSULE',
    status: 'ACTIVE',
    crewCapacity: 3,
    firstFlight: '1999-11-20',
    launchVehicles: ['Long March 2F'],
    specs: { mass: '~8,000 kg' },
    summary:
      'China\u2019s crewed spacecraft, in service since 2003, used to ferry crews to Chinese space stations including Tiangong.',
    missions: [
      { name: 'Shenzhou 5', date: '2003-10-15', launchVehicle: 'Long March 2F', description: 'First crewed Chinese spaceflight, carrying Yang Liwei.' },
      { name: 'Shenzhou 12', date: '2021-06-17', launchVehicle: 'Long March 2F', description: 'First crew to the Tianhe core module of the Tiangong space station.' },
    ],
  },
  {
    id: 'tiangong',
    name: 'Tiangong Space Station',
    manufacturer: 'China Academy of Space Technology (CAST)',
    agency: 'CNSA',
    agencyLinkId: 'cnsa',
    type: 'SPACE STATION',
    status: 'ACTIVE',
    crewCapacity: 3,
    firstFlight: '2021-04-29',
    launchVehicles: ['Long March 5B'],
    specs: { mass: '~100,000 kg (assembled)' },
    summary:
      'China\u2019s modular space station in low Earth orbit, with its Tianhe core module launched in 2021 and permanently crewed since 2022.',
    missions: [
      { name: 'Tianhe core module launch', date: '2021-04-29', launchVehicle: 'Long March 5B', description: 'First and core module of the station reaches orbit.' },
    ],
  },
  {
    id: 'mir',
    name: 'Mir',
    manufacturer: 'RKK Energia',
    agency: 'Roscosmos',
    agencyLinkId: 'roscosmos',
    type: 'SPACE STATION',
    status: 'RETIRED',
    crewCapacity: 3,
    firstFlight: '1986-02-20',
    launchVehicles: ['Proton-K'],
    specs: { mass: '~129,700 kg (final configuration)' },
    summary:
      'A Soviet-then-Russian modular space station occupied almost continuously from 1986 to 2000, deliberately deorbited in 2001.',
    missions: [
      { name: 'Core module launch', date: '1986-02-20', launchVehicle: 'Proton-K', description: 'First Mir module reaches orbit.' },
      { name: 'Deorbit', date: '2001-03-23', launchVehicle: 'Proton-K', description: 'Controlled reentry over the South Pacific after 15 years in orbit.' },
    ],
  },
  {
    id: 'skylab',
    name: 'Skylab',
    manufacturer: 'McDonnell Douglas',
    agency: 'NASA',
    agencyLinkId: 'nasa',
    type: 'SPACE STATION',
    status: 'RETIRED',
    crewCapacity: 3,
    firstFlight: '1973-05-14',
    launchVehicles: ['Saturn V'],
    specs: { mass: '~77,100 kg' },
    summary:
      'The United States\u2019 first space station, hosting three crews in 1973-74 before an uncontrolled reentry over Australia in 1979.',
    missions: [
      { name: 'Skylab launch', date: '1973-05-14', launchVehicle: 'Saturn V', description: 'Station reaches orbit, damaged during ascent and repaired by the first crew.' },
      { name: 'Reentry', date: '1979-07-11', description: 'Skylab reenters the atmosphere, scattering debris over the Indian Ocean and Western Australia.' },
    ],
  },
  {
    id: 'voyager-1',
    name: 'Voyager 1',
    manufacturer: 'Jet Propulsion Laboratory (NASA)',
    agency: 'NASA',
    agencyLinkId: 'nasa',
    type: 'ROBOTIC PROBE',
    status: 'ACTIVE',
    crewCapacity: 0,
    firstFlight: '1977-09-05',
    launchVehicles: ['Titan IIIE-Centaur'],
    specs: { mass: '~825 kg' },
    summary:
      'A NASA probe launched in 1977 to study the outer planets, now the most distant human-made object, operating in interstellar space since 2012.',
    missions: [
      { name: 'Jupiter flyby', date: '1979-03-05', description: 'Close flyby returning detailed images of Jupiter and its moons.' },
      { name: 'Saturn flyby', date: '1980-11-12', description: 'Close flyby of Saturn and its ring system.' },
      { name: 'Interstellar entry', date: '2012-08-25', description: 'Crosses the heliopause into interstellar space.' },
    ],
  },
  {
    id: 'voyager-2',
    name: 'Voyager 2',
    manufacturer: 'Jet Propulsion Laboratory (NASA)',
    agency: 'NASA',
    agencyLinkId: 'nasa',
    type: 'ROBOTIC PROBE',
    status: 'ACTIVE',
    crewCapacity: 0,
    firstFlight: '1977-08-20',
    launchVehicles: ['Titan IIIE-Centaur'],
    specs: { mass: '~825 kg' },
    summary:
      'A NASA probe launched in 1977, the only spacecraft to have flown by all four giant planets, now operating in interstellar space.',
    missions: [
      { name: 'Uranus flyby', date: '1986-01-24', description: 'Only spacecraft to have visited Uranus.' },
      { name: 'Neptune flyby', date: '1989-08-25', description: 'Only spacecraft to have visited Neptune.' },
      { name: 'Interstellar entry', date: '2018-11-05', description: 'Crosses the heliopause into interstellar space.' },
    ],
  },
  {
    id: 'cassini',
    name: 'Cassini',
    manufacturer: 'Jet Propulsion Laboratory (NASA)',
    agency: 'NASA / ESA / ASI',
    agencyLinkId: 'nasa',
    type: 'ROBOTIC PROBE',
    status: 'RETIRED',
    crewCapacity: 0,
    firstFlight: '1997-10-15',
    launchVehicles: ['Titan IVB'],
    specs: { mass: '~5,600 kg (with Huygens probe and fuel)' },
    summary:
      'A NASA/ESA/ASI orbiter that studied Saturn and its moons for 13 years, ending with a deliberate plunge into Saturn\u2019s atmosphere.',
    missions: [
      { name: 'Saturn orbit insertion', date: '2004-07-01', description: 'Cassini enters orbit around Saturn.' },
      { name: 'Huygens landing on Titan', date: '2005-01-14', launchVehicle: 'Titan IVB', description: 'Companion Huygens probe lands on Saturn\u2019s moon Titan.' },
      { name: 'Grand Finale', date: '2017-09-15', description: 'Deliberate atmospheric entry into Saturn, ending the mission.' },
    ],
  },
  {
    id: 'new-horizons',
    name: 'New Horizons',
    manufacturer: 'Johns Hopkins Applied Physics Laboratory',
    agency: 'NASA',
    agencyLinkId: 'nasa',
    type: 'ROBOTIC PROBE',
    status: 'ACTIVE',
    crewCapacity: 0,
    firstFlight: '2006-01-19',
    launchVehicles: ['Atlas V'],
    specs: { mass: '~478 kg' },
    summary:
      'A NASA probe that performed the first flyby of Pluto and later of the Kuiper Belt object Arrokoth, now continuing outward through the Kuiper Belt.',
    missions: [
      { name: 'Pluto flyby', date: '2015-07-14', description: 'First close flyby of Pluto and its moons.' },
      { name: 'Arrokoth flyby', date: '2019-01-01', description: 'Closest flyby yet of a Kuiper Belt object.' },
    ],
  },
  {
    id: 'juno',
    name: 'Juno',
    manufacturer: 'Lockheed Martin',
    agency: 'NASA',
    agencyLinkId: 'nasa',
    type: 'ROBOTIC PROBE',
    status: 'ACTIVE',
    crewCapacity: 0,
    firstFlight: '2011-08-05',
    launchVehicles: ['Atlas V'],
    specs: { mass: '~3,625 kg (fueled)' },
    summary:
      'A NASA solar-powered orbiter studying Jupiter\u2019s composition, gravity field and magnetosphere from a polar orbit.',
    missions: [
      { name: 'Jupiter orbit insertion', date: '2016-07-05', description: 'Juno enters polar orbit around Jupiter.' },
    ],
  },
  {
    id: 'perseverance',
    name: 'Perseverance',
    manufacturer: 'Jet Propulsion Laboratory (NASA)',
    agency: 'NASA',
    agencyLinkId: 'nasa',
    type: 'ROVER',
    status: 'ACTIVE',
    crewCapacity: 0,
    firstFlight: '2020-07-30',
    launchVehicles: ['Atlas V'],
    specs: { mass: '~1,025 kg' },
    summary:
      'A NASA rover exploring Jezero Crater on Mars, searching for signs of ancient microbial life and caching samples for future return to Earth.',
    missions: [
      { name: 'Mars landing', date: '2021-02-18', description: 'Lands in Jezero Crater using the sky-crane descent system.' },
    ],
  },
  {
    id: 'hubble',
    name: 'Hubble Space Telescope',
    manufacturer: 'Lockheed Martin',
    agency: 'NASA / ESA',
    agencyLinkId: 'nasa',
    type: 'SPACE TELESCOPE',
    status: 'ACTIVE',
    crewCapacity: 0,
    firstFlight: '1990-04-24',
    launchVehicles: ['Space Shuttle stack'],
    specs: { mass: '~11,110 kg', length: '~13.2 m' },
    summary:
      'A NASA/ESA space telescope in low Earth orbit since 1990, serviced five times by Space Shuttle crews and still returning science observations.',
    missions: [
      { name: 'Deployment (STS-31)', date: '1990-04-24', launchVehicle: 'Space Shuttle stack', description: 'Deployed from Space Shuttle Discovery.' },
      { name: 'Servicing Mission 1', date: '1993-12-02', launchVehicle: 'Space Shuttle stack', description: 'Corrective optics installed to fix the telescope\u2019s primary mirror flaw.' },
    ],
  },
  {
    id: 'jwst',
    name: 'James Webb Space Telescope',
    manufacturer: 'Northrop Grumman',
    agency: 'NASA / ESA / CSA',
    agencyLinkId: 'nasa',
    type: 'SPACE TELESCOPE',
    status: 'ACTIVE',
    crewCapacity: 0,
    firstFlight: '2021-12-25',
    launchVehicles: ['Ariane 5'],
    specs: { mass: '~6,200 kg', mirrorDiameter: '6.5 m primary mirror' },
    summary:
      'A NASA/ESA/CSA infrared space observatory positioned at the Sun-Earth L2 point, the largest and most powerful space telescope yet flown.',
    missions: [
      { name: 'Launch and deployment', date: '2021-12-25', launchVehicle: 'Ariane 5', description: 'Launched and unfolded its sunshield and mirror en route to L2.' },
      { name: 'First science images', date: '2022-07-12', description: 'Release of the telescope\u2019s first full-color science images.' },
    ],
  },
  {
    id: 'cygnus',
    name: 'Cygnus',
    manufacturer: 'Northrop Grumman',
    agency: 'Northrop Grumman / NASA',
    type: 'CARGO SPACECRAFT',
    status: 'ACTIVE',
    crewCapacity: 0,
    firstFlight: '2013-09-18',
    launchVehicles: ['Antares', 'Falcon 9', 'Atlas V'],
    specs: { mass: '~5,000 kg (dry, varies by variant)' },
    summary:
      'An uncrewed cargo spacecraft resupplying the ISS under NASA\u2019s Commercial Resupply Services program, disposed of by burning up in the atmosphere.',
    missions: [
      { name: 'Orb-D1', date: '2013-09-18', launchVehicle: 'Antares', description: 'First demonstration flight to the ISS.' },
    ],
  },
  {
    id: 'htv',
    name: 'H-II Transfer Vehicle (Kounotori)',
    manufacturer: 'Mitsubishi Heavy Industries',
    agency: 'JAXA',
    agencyLinkId: 'jaxa',
    type: 'CARGO SPACECRAFT',
    status: 'RETIRED',
    crewCapacity: 0,
    firstFlight: '2009-09-10',
    launchVehicles: ['H-IIB'],
    specs: { mass: '~10,500 kg (fully loaded)' },
    summary:
      'JAXA\u2019s uncrewed cargo spacecraft, flown nine times to resupply the ISS between 2009 and 2020 before being succeeded by HTV-X.',
    missions: [
      { name: 'HTV-1', date: '2009-09-10', launchVehicle: 'H-IIB', description: 'First flight of the H-II Transfer Vehicle.' },
      { name: 'HTV-9 (final flight)', date: '2020-05-20', launchVehicle: 'H-IIB', description: 'Final HTV mission before retirement of the vehicle.' },
    ],
  },
  {
    id: 'progress',
    name: 'Progress',
    manufacturer: 'RKK Energia',
    agency: 'Roscosmos',
    agencyLinkId: 'roscosmos',
    type: 'CARGO SPACECRAFT',
    status: 'ACTIVE',
    crewCapacity: 0,
    firstFlight: '1978-01-20',
    launchVehicles: ['Soyuz rocket'],
    specs: { mass: '~7,150 kg' },
    summary:
      'An uncrewed Russian cargo spacecraft derived from Soyuz, in service since the late 1970s and still resupplying the ISS today.',
    missions: [
      { name: 'Progress 1', date: '1978-01-20', launchVehicle: 'Soyuz rocket', description: 'First flight, resupplying the Salyut 6 space station.' },
    ],
  },
  {
    id: 'vikram-lander',
    name: 'Vikram Lander (Chandrayaan-3)',
    manufacturer: 'Indian Space Research Organisation (ISRO)',
    agency: 'ISRO',
    agencyLinkId: 'isro',
    type: 'LANDER',
    status: 'RETIRED',
    crewCapacity: 0,
    firstFlight: '2023-07-14',
    launchVehicles: ['LVM3'],
    specs: { mass: '~1,752 kg (lander, with rover)' },
    summary:
      'ISRO\u2019s lunar lander that made India the first country to land near the Moon\u2019s south polar region, carrying the Pragyan rover.',
    missions: [
      { name: 'Chandrayaan-3 launch', date: '2023-07-14', launchVehicle: 'LVM3', description: 'Mission launches from the Satish Dhawan Space Centre.' },
      { name: 'Lunar south pole landing', date: '2023-08-23', description: 'Successful soft landing near the Moon\u2019s south pole.' },
    ],
  },
];
