// Mission Database — data only. No UI here, so the dataset can grow without
// touching MissionDatabase.js.
//
// Every field below reflects publicly documented mission facts (agency
// mission pages, official mission records). Where a value is not reliably
// known, it is left `null`/omitted and the UI renders "DATA UNAVAILABLE"
// instead of guessing. Statuses reflect the state of each mission as of
// September 2026.
//
// `agencyLinkId` matches an id in SpaceTecHub.js's AGENCIES list, so a
// mission profile can deep-link to that agency's existing card instead of
// duplicating agency info. `crewIds` matches an id in astronautData.js so
// crew names can deep-link to the existing Astronaut Database instead of
// duplicating astronaut info. `launchVehicle` and `spacecraft` are shown as
// plain tags linking generically to the existing Rocket Database (rocket
// entries there are sourced live and don't have stable per-mission ids to
// deep-link to, so — like the Astronaut Database does for launch vehicles —
// we link to the database itself, not a specific record).

export const MISSION_TYPES = [
  'HUMAN SPACEFLIGHT',
  'LUNAR',
  'MARS',
  'DEEP SPACE',
  'ASTEROID',
  'COMET',
  'SOLAR',
  'EARTH OBSERVATION',
  'ASTRONOMY',
  'SPACE STATION',
  'TECHNOLOGY DEMONSTRATION',
  'SCIENCE',
  'OTHER',
];

export const MISSION_STATUSES = [
  'UPCOMING',
  'ACTIVE',
  'COMPLETED',
  'FAILED',
  'PARTIALLY SUCCESSFUL',
  'CANCELLED',
  'EXTENDED',
  'PLANNED',
];

export const MISSIONS = [
  // ============================= HUMAN SPACEFLIGHT =============================
  {
    id: 'vostok-1',
    name: 'Vostok 1',
    agency: 'Soviet Space Programme',
    agencyLinkId: 'roscosmos',
    country: 'Soviet Union',
    type: 'HUMAN SPACEFLIGHT',
    destination: 'Low Earth Orbit',
    status: 'COMPLETED',
    crewed: true,
    launchDate: '1961-04-12',
    launchVehicle: 'Vostok-K',
    spacecraft: 'Vostok',
    launchSite: 'Baikonur Cosmodrome',
    duration: '1 hour 48 minutes',
    objective: 'Carry out the first human spaceflight and orbit the Earth.',
    description: 'Vostok 1 carried Yuri Gagarin on a single orbit of the Earth, making him the first human to travel into space and marking the start of the era of crewed spaceflight.',
    crewIds: ['yuri-gagarin'],
    timeline: [
      { label: 'LAUNCH', date: '1961-04-12', note: 'Vostok-K lifts off from Baikonur.' },
      { label: 'EARTH ORBIT', date: '1961-04-12', note: 'Single orbit of the Earth completed.' },
      { label: 'REENTRY', date: '1961-04-12' },
      { label: 'LANDING', date: '1961-04-12', note: 'Gagarin ejects and lands by parachute near Saratov.' },
    ],
  },
  {
    id: 'freedom-7',
    name: 'Freedom 7 (Mercury-Redstone 3)',
    agency: 'NASA',
    agencyLinkId: 'nasa',
    country: 'United States',
    type: 'HUMAN SPACEFLIGHT',
    destination: 'Suborbital',
    status: 'COMPLETED',
    crewed: true,
    launchDate: '1961-05-05',
    launchVehicle: 'Redstone',
    spacecraft: 'Freedom 7 (Mercury)',
    launchSite: 'Cape Canaveral',
    duration: '15 minutes 28 seconds',
    objective: 'Fly the first American into space on a suborbital trajectory.',
    description: 'Alan Shepard became the first American in space aboard the Mercury capsule Freedom 7, a 15-minute suborbital hop that helped validate the Mercury spacecraft ahead of orbital flights.',
    crewIds: ['alan-shepard'],
    timeline: [
      { label: 'LAUNCH', date: '1961-05-05', note: 'Redstone rocket lifts off from Cape Canaveral.' },
      { label: 'SUBORBITAL ARC', date: '1961-05-05' },
      { label: 'SPLASHDOWN', date: '1961-05-05', note: 'Recovered in the Atlantic Ocean.' },
    ],
  },
  {
    id: 'friendship-7',
    name: 'Friendship 7 (Mercury-Atlas 6)',
    agency: 'NASA',
    agencyLinkId: 'nasa',
    country: 'United States',
    type: 'HUMAN SPACEFLIGHT',
    destination: 'Low Earth Orbit',
    status: 'COMPLETED',
    crewed: true,
    launchDate: '1962-02-20',
    launchVehicle: 'Atlas LV-3B',
    spacecraft: 'Friendship 7 (Mercury)',
    launchSite: 'Cape Canaveral',
    duration: '4 hours 55 minutes',
    objective: 'Fly the first American orbital spaceflight.',
    description: 'John Glenn orbited the Earth three times aboard Friendship 7, becoming the first American to reach orbit and a major milestone in the Mercury program.',
    crewIds: ['john-glenn'],
    timeline: [
      { label: 'LAUNCH', date: '1962-02-20', note: 'Atlas LV-3B lifts off from Cape Canaveral.' },
      { label: 'EARTH ORBIT', date: '1962-02-20', note: 'Three orbits completed.' },
      { label: 'REENTRY', date: '1962-02-20' },
      { label: 'SPLASHDOWN', date: '1962-02-20' },
    ],
  },
  {
    id: 'voskhod-2',
    name: 'Voskhod 2',
    agency: 'Soviet Space Programme',
    agencyLinkId: 'roscosmos',
    country: 'Soviet Union',
    type: 'HUMAN SPACEFLIGHT',
    destination: 'Low Earth Orbit',
    status: 'COMPLETED',
    crewed: true,
    launchDate: '1965-03-18',
    launchVehicle: 'Voskhod',
    spacecraft: 'Voskhod',
    launchSite: 'Baikonur Cosmodrome',
    duration: '1 day 2 hours 2 minutes',
    objective: 'Perform the first spacewalk (extravehicular activity).',
    description: 'Voskhod 2 carried out the first human spacewalk, with Alexei Leonov exiting the capsule for just over 12 minutes, though the mission ended with a difficult manual reentry after an automated system failure.',
    crewIds: ['alexei-leonov'],
    timeline: [
      { label: 'LAUNCH', date: '1965-03-18', note: 'Voskhod rocket lifts off from Baikonur.' },
      { label: 'EARTH ORBIT', date: '1965-03-18' },
      { label: 'SPACEWALK', date: '1965-03-18', note: 'First EVA in history, lasting 12 minutes 9 seconds.' },
      { label: 'REENTRY', date: '1965-03-19', note: 'Manual reentry after automated system malfunction.' },
      { label: 'LANDING', date: '1965-03-19', note: 'Landed off-target in the Ural taiga.' },
    ],
  },
  {
    id: 'apollo-8',
    name: 'Apollo 8',
    agency: 'NASA',
    agencyLinkId: 'nasa',
    country: 'United States',
    type: 'HUMAN SPACEFLIGHT',
    destination: 'Lunar Orbit',
    status: 'COMPLETED',
    crewed: true,
    launchDate: '1968-12-21',
    launchVehicle: 'Saturn V',
    spacecraft: 'Apollo CSM',
    launchSite: 'Kennedy Space Center LC-39A',
    duration: '6 days 3 hours 42 minutes',
    objective: 'Send the first crewed spacecraft to orbit the Moon.',
    description: 'Apollo 8 was the first crewed spacecraft to leave low Earth orbit and orbit the Moon, with its crew reading from the Book of Genesis during a televised broadcast on Christmas Eve 1968.',
    crewIds: ['jim-lovell'],
    timeline: [
      { label: 'LAUNCH', date: '1968-12-21' },
      { label: 'TRANS-LUNAR INJECTION', date: '1968-12-21' },
      { label: 'LUNAR ORBIT INSERTION', date: '1968-12-24' },
      { label: 'TRANS-EARTH INJECTION', date: '1968-12-25' },
      { label: 'SPLASHDOWN', date: '1968-12-27' },
    ],
  },
  {
    id: 'apollo-11',
    name: 'Apollo 11',
    agency: 'NASA',
    agencyLinkId: 'nasa',
    country: 'United States',
    type: 'LUNAR',
    destination: 'Moon',
    status: 'COMPLETED',
    crewed: true,
    launchDate: '1969-07-16',
    launchVehicle: 'Saturn V',
    spacecraft: 'Columbia (CM) / Eagle (LM)',
    launchSite: 'Kennedy Space Center LC-39A',
    duration: '8 days 3 hours 18 minutes',
    objective: 'Land the first humans on the Moon and return them safely to Earth.',
    description: 'Apollo 11 achieved the first crewed lunar landing, with Neil Armstrong and Buzz Aldrin walking on the Moon\u2019s surface at the Sea of Tranquility while Michael Collins orbited above in the command module.',
    crewIds: ['neil-armstrong', 'buzz-aldrin', 'michael-collins'],
    timeline: [
      { label: 'LAUNCH', date: '1969-07-16', note: 'Saturn V lifts off from LC-39A.' },
      { label: 'TRANS-LUNAR INJECTION', date: '1969-07-16' },
      { label: 'LUNAR ORBIT INSERTION', date: '1969-07-19' },
      { label: 'LUNAR LANDING', date: '1969-07-20', note: 'Eagle lands in the Sea of Tranquility.' },
      { label: 'MOONWALK', date: '1969-07-21', note: 'Armstrong and Aldrin spend about 2.5 hours on the surface.' },
      { label: 'LUNAR ASCENT', date: '1969-07-21' },
      { label: 'TRANS-EARTH INJECTION', date: '1969-07-22' },
      { label: 'SPLASHDOWN', date: '1969-07-24' },
    ],
  },
  {
    id: 'apollo-13',
    name: 'Apollo 13',
    agency: 'NASA',
    agencyLinkId: 'nasa',
    country: 'United States',
    type: 'LUNAR',
    destination: 'Moon (flyby, landing aborted)',
    status: 'PARTIALLY SUCCESSFUL',
    crewed: true,
    launchDate: '1970-04-11',
    launchVehicle: 'Saturn V',
    spacecraft: 'Odyssey (CM) / Aquarius (LM)',
    launchSite: 'Kennedy Space Center LC-39A',
    duration: '5 days 22 hours 54 minutes',
    objective: 'Land in the lunar Fra Mauro highlands; converted to a survival mission after an oxygen tank failure.',
    description: 'An oxygen tank explosion en route to the Moon forced Apollo 13\u2019s crew to abort the planned landing and use the lunar module as a lifeboat, returning safely to Earth in what became known as a "successful failure".',
    crewIds: ['jim-lovell'],
    timeline: [
      { label: 'LAUNCH', date: '1970-04-11' },
      { label: 'TRANS-LUNAR INJECTION', date: '1970-04-11' },
      { label: 'OXYGEN TANK FAILURE', date: '1970-04-13', note: 'Explosion cripples the service module; landing aborted.' },
      { label: 'LUNAR FLYBY', date: '1970-04-15', note: 'Free-return trajectory around the Moon.' },
      { label: 'TRANS-EARTH COAST', date: '1970-04-15' },
      { label: 'SPLASHDOWN', date: '1970-04-17', note: 'All three crew recovered safely.' },
    ],
  },
  {
    id: 'apollo-17',
    name: 'Apollo 17',
    agency: 'NASA',
    agencyLinkId: 'nasa',
    country: 'United States',
    type: 'LUNAR',
    destination: 'Moon',
    status: 'COMPLETED',
    crewed: true,
    launchDate: '1972-12-07',
    launchVehicle: 'Saturn V',
    spacecraft: 'America (CM) / Challenger (LM)',
    launchSite: 'Kennedy Space Center LC-39A',
    duration: '12 days 13 hours 52 minutes',
    objective: 'Conduct the final Apollo crewed lunar landing, with an extended surface stay and roving traverses.',
    description: 'Apollo 17 was the sixth and final crewed Moon landing of the Apollo program, with Gene Cernan and Harrison Schmitt spending over three days on the surface in the Taurus-Littrow valley, the longest of any Apollo mission.',
    crewIds: ['gene-cernan'],
    timeline: [
      { label: 'LAUNCH', date: '1972-12-07' },
      { label: 'LUNAR ORBIT INSERTION', date: '1972-12-10' },
      { label: 'LUNAR LANDING', date: '1972-12-11', note: 'Challenger lands in the Taurus-Littrow valley.' },
      { label: 'SURFACE OPERATIONS', date: '1972-12-11', note: 'Three moonwalks totaling over 22 hours.' },
      { label: 'LUNAR ASCENT', date: '1972-12-14' },
      { label: 'SPLASHDOWN', date: '1972-12-19' },
    ],
  },
  {
    id: 'apollo-soyuz',
    name: 'Apollo\u2013Soyuz Test Project',
    agency: 'NASA / Soviet Space Programme',
    agencyLinkId: 'nasa',
    country: 'United States / Soviet Union',
    type: 'HUMAN SPACEFLIGHT',
    destination: 'Low Earth Orbit',
    status: 'COMPLETED',
    crewed: true,
    launchDate: '1975-07-15',
    launchVehicle: 'Saturn IB / Soyuz',
    spacecraft: 'Apollo CSM / Soyuz 19',
    launchSite: 'Kennedy Space Center / Baikonur Cosmodrome',
    duration: '9 days 1 hour 28 minutes',
    objective: 'Dock an American and Soviet spacecraft in orbit as a symbol of détente.',
    description: 'The first joint US\u2013Soviet spaceflight saw an Apollo command module dock with a Soyuz spacecraft in orbit, with crews conducting joint experiments and a symbolic handshake in space.',
    crewIds: [],
    timeline: [
      { label: 'LAUNCH (SOYUZ)', date: '1975-07-15' },
      { label: 'LAUNCH (APOLLO)', date: '1975-07-15' },
      { label: 'DOCKING', date: '1975-07-17', note: 'First international crewed docking in orbit.' },
      { label: 'JOINT OPERATIONS', date: '1975-07-17' },
      { label: 'UNDOCKING', date: '1975-07-19' },
      { label: 'SPLASHDOWN (APOLLO)', date: '1975-07-24' },
    ],
  },
  {
    id: 'sts-1',
    name: 'STS-1',
    agency: 'NASA',
    agencyLinkId: 'nasa',
    country: 'United States',
    type: 'HUMAN SPACEFLIGHT',
    destination: 'Low Earth Orbit',
    status: 'COMPLETED',
    crewed: true,
    launchDate: '1981-04-12',
    launchVehicle: 'Space Shuttle',
    spacecraft: 'Space Shuttle Columbia',
    launchSite: 'Kennedy Space Center LC-39A',
    duration: '2 days 6 hours 21 minutes',
    objective: 'Fly the first orbital test flight of the Space Shuttle.',
    description: 'STS-1 was the first flight of NASA\u2019s Space Shuttle program, sending Columbia into orbit with a two-person crew to validate the world\u2019s first reusable crewed orbital spacecraft.',
    crewIds: [],
    timeline: [
      { label: 'LAUNCH', date: '1981-04-12' },
      { label: 'EARTH ORBIT', date: '1981-04-12', note: '36 orbits over just over two days.' },
      { label: 'REENTRY', date: '1981-04-14' },
      { label: 'LANDING', date: '1981-04-14', note: 'Runway landing at Edwards Air Force Base.' },
    ],
  },
  {
    id: 'sts-51l',
    name: 'STS-51-L (Challenger)',
    agency: 'NASA',
    agencyLinkId: 'nasa',
    country: 'United States',
    type: 'HUMAN SPACEFLIGHT',
    destination: 'Low Earth Orbit',
    status: 'FAILED',
    crewed: true,
    launchDate: '1986-01-28',
    launchVehicle: 'Space Shuttle',
    spacecraft: 'Space Shuttle Challenger',
    launchSite: 'Kennedy Space Center LC-39B',
    duration: '73 seconds',
    objective: 'Deploy a communications satellite and conduct the Teacher in Space project.',
    description: 'Space Shuttle Challenger broke apart 73 seconds after launch due to the failure of an O-ring seal on a solid rocket booster, killing all seven crew members and leading to a major redesign of Shuttle safety systems.',
    crewIds: [],
    timeline: [
      { label: 'LAUNCH', date: '1986-01-28' },
      { label: 'BOOSTER SEAL FAILURE', date: '1986-01-28', note: 'O-ring failure allows hot gas to breach the external tank.' },
      { label: 'VEHICLE BREAKUP', date: '1986-01-28', note: 'Challenger disintegrates 73 seconds after liftoff.' },
    ],
  },
  {
    id: 'sts-107',
    name: 'STS-107 (Columbia)',
    agency: 'NASA',
    agencyLinkId: 'nasa',
    country: 'United States',
    type: 'HUMAN SPACEFLIGHT',
    destination: 'Low Earth Orbit',
    status: 'FAILED',
    crewed: true,
    launchDate: '2003-01-16',
    launchVehicle: 'Space Shuttle',
    spacecraft: 'Space Shuttle Columbia',
    launchSite: 'Kennedy Space Center LC-39A',
    duration: '15 days 22 hours 20 minutes',
    objective: 'Conduct a 16-day science research mission in low Earth orbit.',
    description: 'Space Shuttle Columbia disintegrated during reentry after foam insulation from the external tank damaged its wing at launch, allowing hot atmospheric gases to breach the wing structure; all seven crew members were killed.',
    crewIds: [],
    timeline: [
      { label: 'LAUNCH', date: '2003-01-16', note: 'Foam debris strikes the left wing during ascent.' },
      { label: 'ON-ORBIT SCIENCE', date: '2003-01-16' },
      { label: 'REENTRY', date: '2003-02-01' },
      { label: 'VEHICLE BREAKUP', date: '2003-02-01', note: 'Columbia breaks apart over Texas during reentry.' },
    ],
  },
  {
    id: 'shenzhou-5',
    name: 'Shenzhou 5',
    agency: 'CNSA',
    agencyLinkId: 'cnsa',
    country: 'China',
    type: 'HUMAN SPACEFLIGHT',
    destination: 'Low Earth Orbit',
    status: 'COMPLETED',
    crewed: true,
    launchDate: '2003-10-15',
    launchVehicle: 'Long March 2F',
    spacecraft: 'Shenzhou',
    launchSite: 'Jiuquan Satellite Launch Center',
    duration: '21 hours 23 minutes',
    objective: 'Fly China\u2019s first crewed spaceflight.',
    description: 'Shenzhou 5 made Yang Liwei the first Chinese astronaut in space, completing 14 orbits of the Earth and making China the third nation to independently launch humans into orbit.',
    crewIds: ['yang-liwei'],
    timeline: [
      { label: 'LAUNCH', date: '2003-10-15' },
      { label: 'EARTH ORBIT', date: '2003-10-15', note: '14 orbits completed.' },
      { label: 'REENTRY', date: '2003-10-16' },
      { label: 'LANDING', date: '2003-10-16', note: 'Landed in Inner Mongolia.' },
    ],
  },
  {
    id: 'shenzhou-9',
    name: 'Shenzhou 9',
    agency: 'CNSA',
    agencyLinkId: 'cnsa',
    country: 'China',
    type: 'HUMAN SPACEFLIGHT',
    destination: 'Tiangong-1',
    status: 'COMPLETED',
    crewed: true,
    launchDate: '2012-06-16',
    launchVehicle: 'Long March 2F',
    spacecraft: 'Shenzhou',
    launchSite: 'Jiuquan Satellite Launch Center',
    duration: '12 days 15 hours',
    objective: 'Perform China\u2019s first crewed docking, carrying its first female astronaut.',
    description: 'Shenzhou 9 docked with the Tiangong-1 space lab and carried Liu Yang, China\u2019s first woman in space, along with two crewmates for a stay aboard the module.',
    crewIds: ['liu-yang'],
    timeline: [
      { label: 'LAUNCH', date: '2012-06-16' },
      { label: 'DOCKING WITH TIANGONG-1', date: '2012-06-18' },
      { label: 'ON-ORBIT OPERATIONS', date: '2012-06-18' },
      { label: 'UNDOCKING', date: '2012-06-28' },
      { label: 'LANDING', date: '2012-06-29' },
    ],
  },
  {
    id: 'crew-dragon-demo-2',
    name: 'Crew Dragon Demo-2',
    agency: 'NASA / SpaceX',
    agencyLinkId: 'spacex',
    country: 'United States',
    type: 'HUMAN SPACEFLIGHT',
    destination: 'International Space Station',
    status: 'COMPLETED',
    crewed: true,
    launchDate: '2020-05-30',
    launchVehicle: 'Falcon 9',
    spacecraft: 'Crew Dragon Endeavour',
    launchSite: 'Kennedy Space Center LC-39A',
    duration: '64 days',
    objective: 'Demonstrate Crew Dragon\u2019s ability to safely fly astronauts to and from the ISS.',
    description: 'Demo-2 was the first crewed orbital flight launched from American soil since the retirement of the Space Shuttle, and the first crewed flight of a commercially developed and operated American spacecraft.',
    crewIds: [],
    timeline: [
      { label: 'LAUNCH', date: '2020-05-30' },
      { label: 'DOCKING WITH ISS', date: '2020-05-31' },
      { label: 'ISS STAY', date: '2020-05-31' },
      { label: 'UNDOCKING', date: '2020-08-01' },
      { label: 'SPLASHDOWN', date: '2020-08-02' },
    ],
  },
  {
    id: 'boeing-cft',
    name: 'Boeing Crew Flight Test (CFT)',
    agency: 'NASA / Boeing',
    agencyLinkId: 'nasa',
    country: 'United States',
    type: 'HUMAN SPACEFLIGHT',
    destination: 'International Space Station',
    status: 'PARTIALLY SUCCESSFUL',
    crewed: true,
    launchDate: '2024-06-05',
    launchVehicle: 'Atlas V',
    spacecraft: 'Starliner (CST-100)',
    launchSite: 'Cape Canaveral SFS',
    duration: null,
    objective: 'Fly the first crewed test of Boeing\u2019s Starliner spacecraft to the ISS.',
    description: 'Starliner\u2019s first crewed flight carried two NASA astronauts to the ISS, but helium leaks and thruster issues led NASA to return the spacecraft to Earth uncrewed, with the astronauts instead returning months later aboard a SpaceX Crew Dragon.',
    crewIds: [],
    timeline: [
      { label: 'LAUNCH', date: '2024-06-05' },
      { label: 'DOCKING WITH ISS', date: '2024-06-06' },
      { label: 'THRUSTER/HELIUM ISSUES IDENTIFIED', date: '2024-06-06' },
      { label: 'UNCREWED UNDOCKING', date: '2024-09-06', note: 'NASA opts to return Starliner without its crew.' },
      { label: 'UNCREWED LANDING', date: '2024-09-07', note: 'Landed at White Sands, New Mexico.' },
      { label: 'CREW RETURN VIA CREW DRAGON', date: '2025-03-18', note: 'Astronauts return on a SpaceX Crew Dragon.' },
    ],
  },
  {
    id: 'axiom-mission-4',
    name: 'Axiom Mission 4 (Ax-4)',
    agency: 'Axiom Space / NASA',
    agencyLinkId: 'nasa',
    country: 'United States / International',
    type: 'HUMAN SPACEFLIGHT',
    destination: 'International Space Station',
    status: 'COMPLETED',
    crewed: true,
    launchDate: '2025-06-25',
    launchVehicle: 'Falcon 9',
    spacecraft: 'Crew Dragon',
    launchSite: 'Kennedy Space Center LC-39A',
    duration: null,
    objective: 'Fly a private astronaut mission to the ISS carrying crew from multiple nations.',
    description: 'Axiom Mission 4 was a commercial spaceflight to the ISS whose crew included Shubhanshu Shukla, the first Indian astronaut to visit the space station and only the second Indian to fly in space.',
    crewIds: ['shubhanshu-shukla'],
    timeline: [
      { label: 'LAUNCH', date: '2025-06-25' },
      { label: 'DOCKING WITH ISS', date: '2025-06-26' },
      { label: 'ISS STAY', date: '2025-06-26', note: 'Crew conducts joint research aboard the station.' },
      { label: 'UNDOCKING', date: null },
      { label: 'SPLASHDOWN', date: null },
    ],
  },
  {
    id: 'gaganyaan-g1',
    name: 'Gaganyaan G1',
    agency: 'ISRO',
    agencyLinkId: 'isro',
    country: 'India',
    type: 'HUMAN SPACEFLIGHT',
    destination: 'Low Earth Orbit',
    status: 'UPCOMING',
    crewed: false,
    launchDate: null,
    launchVehicle: 'HLVM3',
    spacecraft: 'Gaganyaan (uncrewed test)',
    launchSite: 'Satish Dhawan Space Centre',
    duration: null,
    objective: 'Fly the first uncrewed test flight of the Gaganyaan crew capsule ahead of India\u2019s first crewed spaceflight.',
    description: 'Gaganyaan G1 is the first uncrewed orbital test of India\u2019s Gaganyaan crew capsule, carrying the humanoid Vyommitra to validate life-support and re-entry systems before India\u2019s first crewed orbital mission.',
    crewIds: [],
    timeline: [
      { label: 'LAUNCH', date: null, note: 'Targeted for late 2026.' },
      { label: 'EARTH ORBIT', date: null },
      { label: 'REENTRY & RECOVERY', date: null },
    ],
  },

  // =================================== LUNAR ===================================
  {
    id: 'luna-2',
    name: 'Luna 2',
    agency: 'Soviet Space Programme',
    agencyLinkId: 'roscosmos',
    country: 'Soviet Union',
    type: 'LUNAR',
    destination: 'Moon',
    status: 'COMPLETED',
    crewed: false,
    launchDate: '1959-09-12',
    launchVehicle: 'Luna 8K72',
    spacecraft: 'Luna 2',
    launchSite: 'Baikonur Cosmodrome',
    duration: '2 days',
    objective: 'Achieve the first spacecraft impact on the Moon.',
    description: 'Luna 2 became the first human-made object to reach the surface of the Moon, impacting near the Sea of Serenity and confirming the Moon has no significant magnetic field.',
    crewIds: [],
    timeline: [
      { label: 'LAUNCH', date: '1959-09-12' },
      { label: 'TRANS-LUNAR COAST', date: '1959-09-12' },
      { label: 'LUNAR IMPACT', date: '1959-09-14' },
    ],
  },
  {
    id: 'luna-9',
    name: 'Luna 9',
    agency: 'Soviet Space Programme',
    agencyLinkId: 'roscosmos',
    country: 'Soviet Union',
    type: 'LUNAR',
    destination: 'Moon',
    status: 'COMPLETED',
    crewed: false,
    launchDate: '1966-01-31',
    launchVehicle: 'Molniya',
    spacecraft: 'Luna 9',
    launchSite: 'Baikonur Cosmodrome',
    duration: '3 days (surface operations)',
    objective: 'Achieve the first soft landing on the Moon and return surface imagery.',
    description: 'Luna 9 made the first soft landing on another world and transmitted the first images from the lunar surface, easing fears that spacecraft would sink into deep lunar dust.',
    crewIds: [],
    timeline: [
      { label: 'LAUNCH', date: '1966-01-31' },
      { label: 'TRANS-LUNAR COAST', date: '1966-01-31' },
      { label: 'SOFT LANDING', date: '1966-02-03' },
      { label: 'SURFACE IMAGING', date: '1966-02-03' },
    ],
  },
  {
    id: 'artemis-1',
    name: 'Artemis I',
    agency: 'NASA',
    agencyLinkId: 'nasa',
    country: 'United States',
    type: 'LUNAR',
    destination: 'Lunar Orbit',
    status: 'COMPLETED',
    crewed: false,
    launchDate: '2022-11-16',
    launchVehicle: 'SLS',
    spacecraft: 'Orion',
    launchSite: 'Kennedy Space Center LC-39B',
    duration: '25 days 10 hours 53 minutes',
    objective: 'Fly an uncrewed test of the SLS rocket and Orion spacecraft around the Moon.',
    description: 'Artemis I was the first integrated flight test of NASA\u2019s Space Launch System and Orion spacecraft, sending an uncrewed Orion capsule on a distant retrograde orbit around the Moon before a successful splashdown.',
    crewIds: [],
    timeline: [
      { label: 'LAUNCH', date: '2022-11-16' },
      { label: 'TRANS-LUNAR INJECTION', date: '2022-11-16' },
      { label: 'LUNAR FLYBY', date: '2022-11-21' },
      { label: 'DISTANT RETROGRADE ORBIT', date: '2022-11-25' },
      { label: 'TRANS-EARTH INJECTION', date: '2022-12-05' },
      { label: 'SPLASHDOWN', date: '2022-12-11' },
    ],
  },
  {
    id: 'artemis-2',
    name: 'Artemis II',
    agency: 'NASA',
    agencyLinkId: 'nasa',
    country: 'United States',
    type: 'LUNAR',
    destination: 'Lunar Flyby',
    status: 'COMPLETED',
    crewed: true,
    launchDate: '2026-04-01',
    launchVehicle: 'SLS',
    spacecraft: 'Orion',
    launchSite: 'Kennedy Space Center LC-39B',
    duration: '10 days',
    objective: 'Fly the first crewed test of Orion on a free-return trajectory around the Moon.',
    description: 'Artemis II carried four astronauts around the Moon and back, the first crewed lunar mission since Apollo 17, traveling farther from Earth than any humans in history without landing on the surface.',
    crewIds: ['victor-glover', 'jeremy-hansen'],
    timeline: [
      { label: 'LAUNCH', date: '2026-04-01', note: 'SLS lifts off from LC-39B with a crew of four.' },
      { label: 'TRANS-LUNAR INJECTION', date: '2026-04-01' },
      { label: 'LUNAR FLYBY', date: '2026-04-05', note: 'Free-return trajectory around the far side of the Moon.' },
      { label: 'TRANS-EARTH COAST', date: '2026-04-05' },
      { label: 'SPLASHDOWN', date: '2026-04-11' },
    ],
  },
  {
    id: 'artemis-3',
    name: 'Artemis III',
    agency: 'NASA',
    agencyLinkId: 'nasa',
    country: 'United States',
    type: 'LUNAR',
    destination: 'Low Earth Orbit (lander demonstration)',
    status: 'UPCOMING',
    crewed: true,
    launchDate: null,
    launchVehicle: 'SLS',
    spacecraft: 'Orion',
    launchSite: 'Kennedy Space Center LC-39B',
    duration: null,
    objective: 'Demonstrate rendezvous and docking with commercial human landing systems in Earth orbit, ahead of a future crewed lunar landing.',
    description: 'Artemis III was originally planned as the Artemis program\u2019s first crewed lunar landing, but NASA revised the mission to a low Earth orbit test of the SpaceX and Blue Origin lunar landers, with the first crewed landing now targeted for Artemis IV.',
    crewIds: [],
    timeline: [
      { label: 'LAUNCH', date: null, note: 'Targeted for late 2027.' },
      { label: 'RENDEZVOUS WITH LANDER(S)', date: null },
      { label: 'DOCKING DEMONSTRATIONS', date: null },
      { label: 'SPLASHDOWN', date: null },
    ],
  },
  {
    id: 'chandrayaan-1',
    name: 'Chandrayaan-1',
    agency: 'ISRO',
    agencyLinkId: 'isro',
    country: 'India',
    type: 'LUNAR',
    destination: 'Moon',
    status: 'COMPLETED',
    crewed: false,
    launchDate: '2008-10-22',
    launchVehicle: 'PSLV',
    spacecraft: 'Chandrayaan-1',
    launchSite: 'Satish Dhawan Space Centre',
    duration: '312 days',
    objective: 'Orbit the Moon and search for evidence of water.',
    description: 'India\u2019s first lunar probe orbited the Moon and carried an impactor that helped confirm the presence of water molecules on the lunar surface.',
    crewIds: [],
    timeline: [
      { label: 'LAUNCH', date: '2008-10-22' },
      { label: 'LUNAR ORBIT INSERTION', date: '2008-11-08' },
      { label: 'IMPACTOR RELEASE', date: '2008-11-14' },
      { label: 'MISSION END', date: '2009-08-29', note: 'Contact lost after just under a year in orbit.' },
    ],
  },
  {
    id: 'chandrayaan-2',
    name: 'Chandrayaan-2',
    agency: 'ISRO',
    agencyLinkId: 'isro',
    country: 'India',
    type: 'LUNAR',
    destination: 'Moon',
    status: 'PARTIALLY SUCCESSFUL',
    crewed: false,
    launchDate: '2019-07-22',
    launchVehicle: 'LVM3',
    spacecraft: 'Chandrayaan-2 (Orbiter / Vikram lander / Pragyan rover)',
    launchSite: 'Satish Dhawan Space Centre',
    duration: null,
    objective: 'Orbit the Moon and land near the lunar south pole.',
    description: 'Chandrayaan-2\u2019s orbiter successfully entered lunar orbit and continues to operate, but its Vikram lander crashed during its final descent, ending the surface landing attempt.',
    crewIds: [],
    timeline: [
      { label: 'LAUNCH', date: '2019-07-22' },
      { label: 'LUNAR ORBIT INSERTION', date: '2019-08-20' },
      { label: 'LANDER SEPARATION', date: '2019-09-02' },
      { label: 'DESCENT & LOSS OF SIGNAL', date: '2019-09-06', note: 'Vikram lander crashes in the final descent phase.' },
    ],
  },
  {
    id: 'chandrayaan-3',
    name: 'Chandrayaan-3',
    agency: 'ISRO',
    agencyLinkId: 'isro',
    country: 'India',
    type: 'LUNAR',
    destination: 'Moon',
    status: 'COMPLETED',
    crewed: false,
    launchDate: '2023-07-14',
    launchVehicle: 'LVM3',
    spacecraft: 'Chandrayaan-3 (Vikram lander / Pragyan rover)',
    launchSite: 'Satish Dhawan Space Centre',
    duration: '14 days (surface operations)',
    objective: 'Achieve a soft landing near the lunar south pole and operate a surface rover.',
    description: 'Chandrayaan-3 made India the fourth country to achieve a soft lunar landing and the first to land near the Moon\u2019s south pole, with the Pragyan rover studying the surface for one lunar day.',
    crewIds: [],
    timeline: [
      { label: 'LAUNCH', date: '2023-07-14' },
      { label: 'LUNAR ORBIT INSERTION', date: '2023-08-05' },
      { label: 'SOFT LANDING', date: '2023-08-23', note: 'Vikram lands near the lunar south pole.' },
      { label: 'ROVER OPERATIONS', date: '2023-08-23' },
      { label: 'MISSION END', date: '2023-09-02', note: 'Lander and rover placed into sleep mode at lunar sunset.' },
    ],
  },
  {
    id: 'change-4',
    name: "Chang'e 4",
    agency: 'CNSA',
    agencyLinkId: 'cnsa',
    country: 'China',
    type: 'LUNAR',
    destination: 'Moon (far side)',
    status: 'ACTIVE',
    crewed: false,
    launchDate: '2018-12-07',
    launchVehicle: 'Long March 3B',
    spacecraft: "Chang'e 4 lander / Yutu-2 rover",
    launchSite: 'Xichang Satellite Launch Center',
    duration: null,
    objective: 'Achieve the first landing on the far side of the Moon.',
    description: "Chang'e 4 achieved the first-ever soft landing on the far side of the Moon, in the South Pole\u2013Aitken basin, relaying communications through the Queqiao satellite; its Yutu-2 rover remains operational.",
    crewIds: [],
    timeline: [
      { label: 'LAUNCH', date: '2018-12-07' },
      { label: 'LUNAR ORBIT INSERTION', date: '2018-12-12' },
      { label: 'FAR-SIDE LANDING', date: '2019-01-03', note: 'Lands in the Von Kármán crater.' },
      { label: 'ROVER DEPLOYMENT', date: '2019-01-03' },
    ],
  },
  {
    id: 'change-5',
    name: "Chang'e 5",
    agency: 'CNSA',
    agencyLinkId: 'cnsa',
    country: 'China',
    type: 'LUNAR',
    destination: 'Moon',
    status: 'COMPLETED',
    crewed: false,
    launchDate: '2020-11-23',
    launchVehicle: 'Long March 5',
    spacecraft: "Chang'e 5",
    launchSite: 'Wenchang Space Launch Site',
    duration: '23 days',
    objective: 'Collect and return samples from the lunar surface.',
    description: "Chang'e 5 returned about 1.7 kilograms of lunar samples to Earth, the first lunar sample return since the Soviet Luna 24 mission in 1976.",
    crewIds: [],
    timeline: [
      { label: 'LAUNCH', date: '2020-11-23' },
      { label: 'LUNAR LANDING', date: '2020-12-01' },
      { label: 'SAMPLE COLLECTION', date: '2020-12-01' },
      { label: 'LUNAR ASCENT', date: '2020-12-03' },
      { label: 'RETURN TO EARTH', date: '2020-12-16', note: 'Sample capsule lands in Inner Mongolia.' },
    ],
  },
  {
    id: 'change-6',
    name: "Chang'e 6",
    agency: 'CNSA',
    agencyLinkId: 'cnsa',
    country: 'China',
    type: 'LUNAR',
    destination: 'Moon (far side)',
    status: 'COMPLETED',
    crewed: false,
    launchDate: '2024-05-03',
    launchVehicle: 'Long March 5',
    spacecraft: "Chang'e 6",
    launchSite: 'Wenchang Space Launch Site',
    duration: '53 days',
    objective: 'Collect and return the first samples from the far side of the Moon.',
    description: "Chang'e 6 landed in the South Pole\u2013Aitken basin on the lunar far side and returned the first-ever samples collected from that hemisphere of the Moon.",
    crewIds: [],
    timeline: [
      { label: 'LAUNCH', date: '2024-05-03' },
      { label: 'FAR-SIDE LANDING', date: '2024-06-01', note: 'Lands in the Apollo crater, South Pole\u2013Aitken basin.' },
      { label: 'SAMPLE COLLECTION', date: '2024-06-02' },
      { label: 'LUNAR ASCENT', date: '2024-06-04' },
      { label: 'RETURN TO EARTH', date: '2024-06-25' },
    ],
  },
  {
    id: 'slim',
    name: 'SLIM (Smart Lander for Investigating Moon)',
    agency: 'JAXA',
    agencyLinkId: 'jaxa',
    country: 'Japan',
    type: 'LUNAR',
    destination: 'Moon',
    status: 'COMPLETED',
    crewed: false,
    launchDate: '2023-09-06',
    launchVehicle: 'H-IIA',
    spacecraft: 'SLIM',
    launchSite: 'Tanegashima Space Center',
    duration: null,
    objective: 'Demonstrate precision "pinpoint" lunar landing technology.',
    description: "SLIM made Japan the fifth country to soft-land on the Moon and demonstrated precision landing within about 100 meters of its target, despite tipping onto its side after touchdown, which limited but did not stop its science operations.",
    crewIds: [],
    timeline: [
      { label: 'LAUNCH', date: '2023-09-06' },
      { label: 'LUNAR ORBIT INSERTION', date: '2023-12-25' },
      { label: 'PINPOINT LANDING', date: '2024-01-19', note: 'Lands within about 100 m of target; lander ends up tipped on its side.' },
      { label: 'SURFACE OPERATIONS', date: '2024-01-19' },
      { label: 'MISSION END', date: '2024-08-23' },
    ],
  },
  {
    id: 'im-1-odysseus',
    name: 'IM-1 (Odysseus)',
    agency: 'Intuitive Machines',
    agencyLinkId: null,
    country: 'United States',
    type: 'LUNAR',
    destination: 'Moon',
    status: 'PARTIALLY SUCCESSFUL',
    crewed: false,
    launchDate: '2024-02-15',
    launchVehicle: 'Falcon 9',
    spacecraft: 'Odysseus (Nova-C)',
    launchSite: 'Kennedy Space Center LC-39A',
    duration: null,
    objective: 'Achieve the first commercial soft landing on the Moon under NASA\u2019s CLPS program.',
    description: 'Odysseus became the first commercially built spacecraft to soft-land on the Moon, though it landed at an angle after a laser-altimeter issue, which limited some payload operations before the lander went silent.',
    crewIds: [],
    timeline: [
      { label: 'LAUNCH', date: '2024-02-15' },
      { label: 'LUNAR ORBIT INSERTION', date: '2024-02-21' },
      { label: 'LUNAR LANDING', date: '2024-02-22', note: 'Lands near Malapert A crater, tipped on its side.' },
      { label: 'SURFACE OPERATIONS', date: '2024-02-22' },
      { label: 'MISSION END', date: '2024-02-29' },
    ],
  },
  {
    id: 'peregrine-mission-one',
    name: 'Peregrine Mission One',
    agency: 'Astrobotic Technology',
    agencyLinkId: null,
    country: 'United States',
    type: 'LUNAR',
    destination: 'Moon',
    status: 'FAILED',
    crewed: false,
    launchDate: '2024-01-08',
    launchVehicle: 'Vulcan Centaur',
    spacecraft: 'Peregrine',
    launchSite: 'Cape Canaveral SFS',
    duration: null,
    objective: 'Achieve a commercial lunar landing under NASA\u2019s CLPS program.',
    description: 'A propellant leak shortly after launch prevented Peregrine from reaching the Moon; the spacecraft instead conducted checkouts in space before a controlled reentry burn over the Pacific Ocean.',
    crewIds: [],
    timeline: [
      { label: 'LAUNCH', date: '2024-01-08' },
      { label: 'PROPELLANT LEAK DETECTED', date: '2024-01-08' },
      { label: 'LUNAR LANDING ABORTED', date: '2024-01-08' },
      { label: 'CONTROLLED REENTRY', date: '2024-01-18', note: 'Deliberate atmospheric reentry over the South Pacific.' },
    ],
  },

  // =================================== MARS ====================================
  {
    id: 'viking-1',
    name: 'Viking 1',
    agency: 'NASA',
    agencyLinkId: 'nasa',
    country: 'United States',
    type: 'MARS',
    destination: 'Mars',
    status: 'COMPLETED',
    crewed: false,
    launchDate: '1975-08-20',
    launchVehicle: 'Titan IIIE',
    spacecraft: 'Viking 1 (Orbiter / Lander)',
    launchSite: 'Cape Canaveral',
    duration: null,
    objective: 'Orbit and soft-land on Mars to study its surface and search for signs of life.',
    description: 'Viking 1 achieved the first fully successful landing on Mars and operated on the surface for over six years, returning the first close-up color images of the Martian surface.',
    crewIds: [],
    timeline: [
      { label: 'LAUNCH', date: '1975-08-20' },
      { label: 'MARS ORBIT INSERTION', date: '1976-06-19' },
      { label: 'LANDING', date: '1976-07-20' },
      { label: 'SURFACE OPERATIONS', date: '1976-07-20' },
      { label: 'MISSION END', date: '1982-11-13' },
    ],
  },
  {
    id: 'mars-pathfinder',
    name: 'Mars Pathfinder',
    agency: 'NASA',
    agencyLinkId: 'nasa',
    country: 'United States',
    type: 'MARS',
    destination: 'Mars',
    status: 'COMPLETED',
    crewed: false,
    launchDate: '1996-12-04',
    launchVehicle: 'Delta II',
    spacecraft: 'Pathfinder / Sojourner rover',
    launchSite: 'Cape Canaveral',
    duration: null,
    objective: 'Demonstrate low-cost landing technology and deploy the first Mars rover.',
    description: 'Mars Pathfinder used an innovative airbag landing system and deployed Sojourner, the first wheeled rover to operate on another planet, proving low-cost robotic exploration of Mars.',
    crewIds: [],
    timeline: [
      { label: 'LAUNCH', date: '1996-12-04' },
      { label: 'LANDING', date: '1997-07-04', note: 'Airbag-cushioned landing in Ares Vallis.' },
      { label: 'ROVER DEPLOYMENT', date: '1997-07-05' },
      { label: 'MISSION END', date: '1997-09-27' },
    ],
  },
  {
    id: 'spirit',
    name: 'Spirit (MER-A)',
    agency: 'NASA',
    agencyLinkId: 'nasa',
    country: 'United States',
    type: 'MARS',
    destination: 'Mars',
    status: 'COMPLETED',
    crewed: false,
    launchDate: '2003-06-10',
    launchVehicle: 'Delta II',
    spacecraft: 'Spirit rover',
    launchSite: 'Cape Canaveral',
    duration: null,
    objective: 'Search for evidence of past water activity in Gusev crater.',
    description: 'Spirit operated on Mars for over six years, far beyond its 90-day design life, finding evidence of past hydrothermal activity before becoming stuck in soft soil and eventually losing contact.',
    crewIds: [],
    timeline: [
      { label: 'LAUNCH', date: '2003-06-10' },
      { label: 'LANDING', date: '2004-01-04', note: 'Lands in Gusev crater.' },
      { label: 'SURFACE OPERATIONS', date: '2004-01-04' },
      { label: 'MISSION END', date: '2010-05-25', note: 'Contact lost after becoming stuck in soft soil.' },
    ],
  },
  {
    id: 'opportunity',
    name: 'Opportunity (MER-B)',
    agency: 'NASA',
    agencyLinkId: 'nasa',
    country: 'United States',
    type: 'MARS',
    destination: 'Mars',
    status: 'COMPLETED',
    crewed: false,
    launchDate: '2003-07-07',
    launchVehicle: 'Delta II',
    spacecraft: 'Opportunity rover',
    launchSite: 'Cape Canaveral',
    duration: null,
    objective: 'Search for evidence of past water activity in Meridiani Planum.',
    description: 'Opportunity operated on Mars for nearly 15 years, traveling over 45 kilometers and setting the extraterrestrial driving distance record, before a planet-wide dust storm ended communications in 2018.',
    crewIds: [],
    timeline: [
      { label: 'LAUNCH', date: '2003-07-07' },
      { label: 'LANDING', date: '2004-01-25', note: 'Lands in Meridiani Planum.' },
      { label: 'SURFACE OPERATIONS', date: '2004-01-25' },
      { label: 'MISSION END', date: '2018-06-10', note: 'Contact lost during a global dust storm.' },
    ],
  },
  {
    id: 'mars-reconnaissance-orbiter',
    name: 'Mars Reconnaissance Orbiter',
    agency: 'NASA',
    agencyLinkId: 'nasa',
    country: 'United States',
    type: 'MARS',
    destination: 'Mars',
    status: 'ACTIVE',
    crewed: false,
    launchDate: '2005-08-12',
    launchVehicle: 'Atlas V',
    spacecraft: 'MRO',
    launchSite: 'Cape Canaveral',
    duration: null,
    objective: 'Study the Martian surface, atmosphere, and subsurface in high resolution, and relay data from surface missions.',
    description: 'MRO has operated at Mars for two decades, providing the highest-resolution global imagery of the planet and serving as a key communications relay for NASA\u2019s surface rovers.',
    crewIds: [],
    timeline: [
      { label: 'LAUNCH', date: '2005-08-12' },
      { label: 'MARS ORBIT INSERTION', date: '2006-03-10' },
      { label: 'PRIMARY SCIENCE MISSION', date: '2006-11-01' },
      { label: 'EXTENDED MISSION', date: '2008-01-01', note: 'Operations continue into an extended mission.' },
    ],
  },
  {
    id: 'phoenix',
    name: 'Phoenix',
    agency: 'NASA',
    agencyLinkId: 'nasa',
    country: 'United States',
    type: 'MARS',
    destination: 'Mars',
    status: 'COMPLETED',
    crewed: false,
    launchDate: '2007-08-04',
    launchVehicle: 'Delta II',
    spacecraft: 'Phoenix',
    launchSite: 'Cape Canaveral',
    duration: null,
    objective: 'Study the Martian arctic and confirm the presence of water ice near the surface.',
    description: 'Phoenix landed in the Martian arctic and directly confirmed water ice in the subsurface soil, before the onset of the Martian winter ended its solar-powered mission.',
    crewIds: [],
    timeline: [
      { label: 'LAUNCH', date: '2007-08-04' },
      { label: 'LANDING', date: '2008-05-25', note: 'Powered descent landing in the northern arctic plains.' },
      { label: 'SURFACE OPERATIONS', date: '2008-05-25' },
      { label: 'MISSION END', date: '2008-11-02', note: 'Loss of power as Martian winter sets in.' },
    ],
  },
  {
    id: 'curiosity',
    name: 'Curiosity (MSL)',
    agency: 'NASA',
    agencyLinkId: 'nasa',
    country: 'United States',
    type: 'MARS',
    destination: 'Mars',
    status: 'ACTIVE',
    crewed: false,
    launchDate: '2011-11-26',
    launchVehicle: 'Atlas V',
    spacecraft: 'Curiosity rover',
    launchSite: 'Cape Canaveral',
    duration: null,
    objective: 'Assess whether Gale crater ever had environmental conditions favorable for microbial life.',
    description: 'Curiosity has spent over a decade exploring Gale crater and climbing Mount Sharp, finding extensive evidence of an ancient habitable environment and continuing active surface operations.',
    crewIds: [],
    timeline: [
      { label: 'LAUNCH', date: '2011-11-26' },
      { label: 'LANDING', date: '2012-08-06', note: 'Sky crane landing in Gale crater.' },
      { label: 'SURFACE OPERATIONS', date: '2012-08-06' },
      { label: 'EXTENDED MISSION', date: '2014-01-01', note: 'Continues climbing Mount Sharp.' },
    ],
  },
  {
    id: 'maven',
    name: 'MAVEN',
    agency: 'NASA',
    agencyLinkId: 'nasa',
    country: 'United States',
    type: 'MARS',
    destination: 'Mars',
    status: 'ACTIVE',
    crewed: false,
    launchDate: '2013-11-18',
    launchVehicle: 'Atlas V',
    spacecraft: 'MAVEN',
    launchSite: 'Cape Canaveral',
    duration: null,
    objective: 'Study the loss of the Martian atmosphere to space.',
    description: 'MAVEN studies how solar wind stripped away much of Mars\u2019s early atmosphere, helping explain the planet\u2019s transition from a warmer, wetter world to the cold desert it is today.',
    crewIds: [],
    timeline: [
      { label: 'LAUNCH', date: '2013-11-18' },
      { label: 'MARS ORBIT INSERTION', date: '2014-09-21' },
      { label: 'PRIMARY SCIENCE MISSION', date: '2014-11-01' },
      { label: 'EXTENDED MISSION', date: '2016-01-01' },
    ],
  },
  {
    id: 'insight',
    name: 'InSight',
    agency: 'NASA',
    agencyLinkId: 'nasa',
    country: 'United States',
    type: 'MARS',
    destination: 'Mars',
    status: 'COMPLETED',
    crewed: false,
    launchDate: '2018-05-05',
    launchVehicle: 'Atlas V',
    spacecraft: 'InSight',
    launchSite: 'Vandenberg SFB',
    duration: null,
    objective: 'Study the deep interior of Mars using seismology and heat-flow measurements.',
    description: 'InSight placed the first seismometer on Mars, detecting hundreds of marsquakes and revealing the size and structure of the planet\u2019s core and mantle, before dust accumulation on its solar panels ended the mission.',
    crewIds: [],
    timeline: [
      { label: 'LAUNCH', date: '2018-05-05' },
      { label: 'LANDING', date: '2018-11-26', note: 'Lands in Elysium Planitia.' },
      { label: 'SEISMOMETER DEPLOYMENT', date: '2018-12-19' },
      { label: 'MISSION END', date: '2022-12-20', note: 'Power lost to dust-covered solar panels.' },
    ],
  },
  {
    id: 'perseverance',
    name: 'Perseverance',
    agency: 'NASA',
    agencyLinkId: 'nasa',
    country: 'United States',
    type: 'MARS',
    destination: 'Mars',
    status: 'ACTIVE',
    crewed: false,
    launchDate: '2020-07-30',
    launchVehicle: 'Atlas V',
    spacecraft: 'Perseverance rover',
    launchSite: 'Cape Canaveral SFS',
    duration: null,
    objective: 'Search for signs of ancient microbial life and cache samples for future return to Earth.',
    description: 'Perseverance is exploring Jezero crater\u2019s ancient river delta, collecting and caching rock samples intended for a future Mars Sample Return mission, and carried the Ingenuity helicopter to Mars.',
    crewIds: [],
    timeline: [
      { label: 'LAUNCH', date: '2020-07-30' },
      { label: 'LANDING', date: '2021-02-18', note: 'Sky crane landing in Jezero crater.' },
      { label: 'SAMPLE CACHING', date: '2021-09-06' },
      { label: 'DELTA EXPLORATION', date: '2022-07-01' },
    ],
  },
  {
    id: 'ingenuity',
    name: 'Ingenuity',
    agency: 'NASA',
    agencyLinkId: 'nasa',
    country: 'United States',
    type: 'TECHNOLOGY DEMONSTRATION',
    destination: 'Mars',
    status: 'COMPLETED',
    crewed: false,
    launchDate: '2020-07-30',
    launchVehicle: 'Atlas V',
    spacecraft: 'Ingenuity helicopter',
    launchSite: 'Cape Canaveral SFS',
    duration: null,
    objective: 'Demonstrate the first powered, controlled flight on another planet.',
    description: 'Ingenuity flew alongside Perseverance to Mars and made the first powered flight on another planet, going on to complete 72 flights, far more than its planned five, before rotor damage ended its mission.',
    crewIds: [],
    timeline: [
      { label: 'LAUNCH', date: '2020-07-30', note: 'Carried to Mars attached to the Perseverance rover.' },
      { label: 'DEPLOYMENT', date: '2021-04-03' },
      { label: 'FIRST FLIGHT', date: '2021-04-19', note: 'First powered, controlled flight on another world.' },
      { label: 'MISSION END', date: '2024-01-18', note: 'Rotor blade damage during landing ends the mission.' },
    ],
  },
  {
    id: 'tianwen-1',
    name: 'Tianwen-1',
    agency: 'CNSA',
    agencyLinkId: 'cnsa',
    country: 'China',
    type: 'MARS',
    destination: 'Mars',
    status: 'PARTIALLY SUCCESSFUL',
    crewed: false,
    launchDate: '2020-07-23',
    launchVehicle: 'Long March 5',
    spacecraft: 'Tianwen-1 (Orbiter / Zhurong rover)',
    launchSite: 'Wenchang Space Launch Site',
    duration: null,
    objective: 'Orbit, land, and rove on Mars in a single mission.',
    description: 'Tianwen-1 made China the second nation to successfully operate a rover on Mars; the orbiter continues to study the planet, while the Zhurong rover stopped communicating after going into a planned hibernation for the Martian winter.',
    crewIds: [],
    timeline: [
      { label: 'LAUNCH', date: '2020-07-23' },
      { label: 'MARS ORBIT INSERTION', date: '2021-02-10' },
      { label: 'LANDING', date: '2021-05-14', note: 'Zhurong rover lands in Utopia Planitia.' },
      { label: 'ROVER OPERATIONS', date: '2021-05-22' },
      { label: 'ROVER HIBERNATION / LOSS OF CONTACT', date: '2022-05-20' },
    ],
  },
  {
    id: 'hope-probe',
    name: 'Hope Probe (Al-Amal)',
    agency: 'UAE Space Agency',
    agencyLinkId: 'uaesa',
    country: 'United Arab Emirates',
    type: 'MARS',
    destination: 'Mars',
    status: 'ACTIVE',
    crewed: false,
    launchDate: '2020-07-19',
    launchVehicle: 'H-IIA',
    spacecraft: 'Hope (Al-Amal)',
    launchSite: 'Tanegashima Space Center',
    duration: null,
    objective: 'Study the Martian atmosphere and climate as the Arab world\u2019s first interplanetary mission.',
    description: 'Hope was the first interplanetary mission from an Arab nation, and continues to study the Martian atmosphere\u2019s daily and seasonal weather cycles from a unique high orbit.',
    crewIds: [],
    timeline: [
      { label: 'LAUNCH', date: '2020-07-19' },
      { label: 'MARS ORBIT INSERTION', date: '2021-02-09' },
      { label: 'PRIMARY SCIENCE MISSION', date: '2021-05-23' },
    ],
  },

  // ================================ DEEP SPACE =================================
  {
    id: 'voyager-1',
    name: 'Voyager 1',
    agency: 'NASA',
    agencyLinkId: 'nasa',
    country: 'United States',
    type: 'DEEP SPACE',
    destination: 'Interstellar Space',
    status: 'EXTENDED',
    crewed: false,
    launchDate: '1977-09-05',
    launchVehicle: 'Titan IIIE',
    spacecraft: 'Voyager 1',
    launchSite: 'Cape Canaveral',
    duration: null,
    objective: 'Explore Jupiter and Saturn, then continue outward into interstellar space.',
    description: 'Voyager 1 flew by Jupiter and Saturn before becoming the first human-made object to enter interstellar space in 2012, and remains the most distant human-made object, still returning data nearly 50 years after launch.',
    crewIds: [],
    timeline: [
      { label: 'LAUNCH', date: '1977-09-05' },
      { label: 'JUPITER FLYBY', date: '1979-03-05' },
      { label: 'SATURN FLYBY', date: '1980-11-12' },
      { label: 'INTERSTELLAR ENTRY', date: '2012-08-25' },
      { label: 'EXTENDED MISSION', date: '2012-08-25', note: 'Continues returning data from interstellar space.' },
    ],
  },
  {
    id: 'voyager-2',
    name: 'Voyager 2',
    agency: 'NASA',
    agencyLinkId: 'nasa',
    country: 'United States',
    type: 'DEEP SPACE',
    destination: 'Interstellar Space',
    status: 'EXTENDED',
    crewed: false,
    launchDate: '1977-08-20',
    launchVehicle: 'Titan IIIE',
    spacecraft: 'Voyager 2',
    launchSite: 'Cape Canaveral',
    duration: null,
    objective: 'Explore Jupiter, Saturn, Uranus, and Neptune, then continue into interstellar space.',
    description: 'Voyager 2 remains the only spacecraft to have visited Uranus and Neptune, and entered interstellar space in 2018, continuing to operate alongside its twin, Voyager 1.',
    crewIds: [],
    timeline: [
      { label: 'LAUNCH', date: '1977-08-20' },
      { label: 'JUPITER FLYBY', date: '1979-07-09' },
      { label: 'SATURN FLYBY', date: '1981-08-25' },
      { label: 'URANUS FLYBY', date: '1986-01-24' },
      { label: 'NEPTUNE FLYBY', date: '1989-08-25' },
      { label: 'INTERSTELLAR ENTRY', date: '2018-11-05' },
    ],
  },
  {
    id: 'galileo',
    name: 'Galileo',
    agency: 'NASA',
    agencyLinkId: 'nasa',
    country: 'United States',
    type: 'DEEP SPACE',
    destination: 'Jupiter',
    status: 'COMPLETED',
    crewed: false,
    launchDate: '1989-10-18',
    launchVehicle: 'Space Shuttle Atlantis',
    spacecraft: 'Galileo',
    launchSite: 'Kennedy Space Center',
    duration: null,
    objective: 'Orbit Jupiter and study its atmosphere, moons, and magnetosphere in detail.',
    description: 'Galileo was the first spacecraft to orbit Jupiter and to deploy an atmospheric probe into a gas giant, and it discovered strong evidence of a subsurface ocean on Europa before being deliberately deorbited into Jupiter.',
    crewIds: [],
    timeline: [
      { label: 'LAUNCH', date: '1989-10-18' },
      { label: 'JUPITER ORBIT INSERTION', date: '1995-12-07' },
      { label: 'ATMOSPHERIC PROBE ENTRY', date: '1995-12-07' },
      { label: 'MOON FLYBYS', date: '1996-01-01' },
      { label: 'MISSION END', date: '2003-09-21', note: 'Deliberately deorbited into Jupiter\u2019s atmosphere.' },
    ],
  },
  {
    id: 'cassini-huygens',
    name: 'Cassini\u2013Huygens',
    agency: 'NASA / ESA / ASI',
    agencyLinkId: 'nasa',
    country: 'United States / Europe',
    type: 'DEEP SPACE',
    destination: 'Saturn',
    status: 'COMPLETED',
    crewed: false,
    launchDate: '1997-10-15',
    launchVehicle: 'Titan IVB',
    spacecraft: 'Cassini orbiter / Huygens probe',
    launchSite: 'Cape Canaveral',
    duration: null,
    objective: 'Orbit Saturn and land a probe on its moon Titan.',
    description: 'Cassini spent 13 years orbiting Saturn, discovering active geysers on Enceladus and hydrocarbon lakes on Titan, while its Huygens probe made the first landing on a moon in the outer solar system, before Cassini ended its mission with a deliberate plunge into Saturn.',
    crewIds: [],
    timeline: [
      { label: 'LAUNCH', date: '1997-10-15' },
      { label: 'SATURN ORBIT INSERTION', date: '2004-07-01' },
      { label: 'HUYGENS TITAN LANDING', date: '2005-01-14' },
      { label: 'EXTENDED MISSIONS', date: '2008-07-01' },
      { label: 'GRAND FINALE / SATURN ENTRY', date: '2017-09-15' },
    ],
  },
  {
    id: 'new-horizons',
    name: 'New Horizons',
    agency: 'NASA',
    agencyLinkId: 'nasa',
    country: 'United States',
    type: 'DEEP SPACE',
    destination: 'Pluto / Kuiper Belt',
    status: 'EXTENDED',
    crewed: false,
    launchDate: '2006-01-19',
    launchVehicle: 'Atlas V',
    spacecraft: 'New Horizons',
    launchSite: 'Cape Canaveral',
    duration: null,
    objective: 'Perform the first flyby reconnaissance of Pluto, then continue into the Kuiper Belt.',
    description: 'New Horizons made the first-ever flyby of Pluto in 2015, revealing a geologically active world, and went on to fly past the Kuiper Belt object Arrokoth in 2019, the most distant object ever explored up close.',
    crewIds: [],
    timeline: [
      { label: 'LAUNCH', date: '2006-01-19' },
      { label: 'JUPITER GRAVITY ASSIST', date: '2007-02-28' },
      { label: 'PLUTO FLYBY', date: '2015-07-14' },
      { label: 'ARROKOTH FLYBY', date: '2019-01-01' },
      { label: 'EXTENDED KUIPER BELT MISSION', date: '2019-01-01' },
    ],
  },
  {
    id: 'juno',
    name: 'Juno',
    agency: 'NASA',
    agencyLinkId: 'nasa',
    country: 'United States',
    type: 'DEEP SPACE',
    destination: 'Jupiter',
    status: 'EXTENDED',
    crewed: false,
    launchDate: '2011-08-05',
    launchVehicle: 'Atlas V',
    spacecraft: 'Juno',
    launchSite: 'Cape Canaveral',
    duration: null,
    objective: 'Study Jupiter\u2019s composition, gravity field, magnetic field, and polar magnetosphere.',
    description: 'Juno orbits Jupiter on a highly elliptical polar path, returning detailed data on the planet\u2019s deep atmosphere and interior structure, with its mission extended to include close flybys of several of Jupiter\u2019s moons.',
    crewIds: [],
    timeline: [
      { label: 'LAUNCH', date: '2011-08-05' },
      { label: 'JUPITER ORBIT INSERTION', date: '2016-07-05' },
      { label: 'PRIMARY SCIENCE MISSION', date: '2016-08-27' },
      { label: 'EXTENDED MISSION', date: '2021-08-01', note: 'Mission extended to study Ganymede, Europa, and Io.' },
    ],
  },
  {
    id: 'europa-clipper',
    name: 'Europa Clipper',
    agency: 'NASA',
    agencyLinkId: 'nasa',
    country: 'United States',
    type: 'DEEP SPACE',
    destination: 'Europa (Jupiter)',
    status: 'ACTIVE',
    crewed: false,
    launchDate: '2024-10-14',
    launchVehicle: 'Falcon Heavy',
    spacecraft: 'Europa Clipper',
    launchSite: 'Kennedy Space Center LC-39A',
    duration: null,
    objective: 'Determine whether Jupiter\u2019s moon Europa could have conditions suitable for life.',
    description: 'Europa Clipper is en route to Jupiter via gravity-assist flybys of Mars and Earth, and will conduct dozens of close flybys of the icy moon Europa to study its subsurface ocean once it arrives in 2030.',
    crewIds: [],
    timeline: [
      { label: 'LAUNCH', date: '2024-10-14' },
      { label: 'MARS GRAVITY ASSIST', date: '2025-03-01' },
      { label: 'EARTH GRAVITY ASSIST', date: '2026-12-03' },
      { label: 'JUPITER ORBIT INSERTION', date: '2030-04-11' },
      { label: 'EUROPA FLYBYS', date: null },
    ],
  },
  {
    id: 'juice',
    name: 'JUICE (Jupiter Icy Moons Explorer)',
    agency: 'ESA',
    agencyLinkId: 'esa',
    country: 'Europe',
    type: 'DEEP SPACE',
    destination: 'Ganymede / Jupiter',
    status: 'ACTIVE',
    crewed: false,
    launchDate: '2023-04-14',
    launchVehicle: 'Ariane 5',
    spacecraft: 'JUICE',
    launchSite: 'Guiana Space Centre',
    duration: null,
    objective: 'Study Jupiter and its icy moons Ganymede, Callisto, and Europa, and orbit Ganymede.',
    description: 'JUICE is en route to the Jupiter system on a series of gravity-assist flybys, and will become the first spacecraft to orbit a moon other than Earth\u2019s when it enters orbit around Ganymede.',
    crewIds: [],
    timeline: [
      { label: 'LAUNCH', date: '2023-04-14' },
      { label: 'EARTH\u2013MOON GRAVITY ASSIST', date: '2024-08-19' },
      { label: 'VENUS GRAVITY ASSIST', date: '2025-08-31' },
      { label: 'JUPITER ORBIT INSERTION', date: '2031-07-01' },
      { label: 'GANYMEDE ORBIT INSERTION', date: '2034-12-01' },
    ],
  },
  {
    id: 'bepicolombo',
    name: 'BepiColombo',
    agency: 'ESA / JAXA',
    agencyLinkId: 'esa',
    country: 'Europe / Japan',
    type: 'DEEP SPACE',
    destination: 'Mercury',
    status: 'ACTIVE',
    crewed: false,
    launchDate: '2018-10-20',
    launchVehicle: 'Ariane 5',
    spacecraft: 'BepiColombo (MPO / Mio)',
    launchSite: 'Guiana Space Centre',
    duration: null,
    objective: 'Study Mercury\u2019s composition, geology, and magnetosphere with two orbiters.',
    description: 'BepiColombo is completing a long cruise to Mercury with a series of Earth, Venus, and Mercury flybys, with its two science orbiters set to separate and begin studying the planet after orbit insertion.',
    crewIds: [],
    timeline: [
      { label: 'LAUNCH', date: '2018-10-20' },
      { label: 'MERCURY FLYBYS', date: '2021-10-01', note: 'Series of six Mercury flybys ahead of orbit insertion.' },
      { label: 'MERCURY ORBIT INSERTION', date: null, note: 'Expected November 2026.' },
      { label: 'ORBITER SEPARATION', date: null, note: 'MPO and Mio expected to separate in December 2026.' },
      { label: 'SCIENCE PHASE', date: null, note: 'Expected to begin in 2027.' },
    ],
  },

  // =============================== ASTEROIDS / COMETS ===========================
  {
    id: 'near-shoemaker',
    name: 'NEAR Shoemaker',
    agency: 'NASA',
    agencyLinkId: 'nasa',
    country: 'United States',
    type: 'ASTEROID',
    destination: '433 Eros',
    status: 'COMPLETED',
    crewed: false,
    launchDate: '1996-02-17',
    launchVehicle: 'Delta II',
    spacecraft: 'NEAR Shoemaker',
    launchSite: 'Cape Canaveral',
    duration: null,
    objective: 'Orbit and study the near-Earth asteroid Eros.',
    description: 'NEAR Shoemaker was the first spacecraft to orbit an asteroid and, at the end of its mission, made a controlled landing on Eros\u2019s surface despite not being designed to land, continuing to return data after touchdown.',
    crewIds: [],
    timeline: [
      { label: 'LAUNCH', date: '1996-02-17' },
      { label: 'EROS ORBIT INSERTION', date: '2000-02-14' },
      { label: 'SURFACE LANDING', date: '2001-02-12', note: 'First landing on an asteroid.' },
      { label: 'MISSION END', date: '2001-02-28' },
    ],
  },
  {
    id: 'hayabusa',
    name: 'Hayabusa',
    agency: 'JAXA',
    agencyLinkId: 'jaxa',
    country: 'Japan',
    type: 'ASTEROID',
    destination: '25143 Itokawa',
    status: 'COMPLETED',
    crewed: false,
    launchDate: '2003-05-09',
    launchVehicle: 'M-V',
    spacecraft: 'Hayabusa',
    launchSite: 'Uchinoura Space Center',
    duration: null,
    objective: 'Rendezvous with an asteroid, collect a surface sample, and return it to Earth.',
    description: 'Despite numerous technical failures en route, Hayabusa achieved the first-ever sample return from an asteroid, bringing tiny grains of Itokawa back to Earth after a seven-year mission.',
    crewIds: [],
    timeline: [
      { label: 'LAUNCH', date: '2003-05-09' },
      { label: 'ASTEROID RENDEZVOUS', date: '2005-09-12' },
      { label: 'SAMPLE COLLECTION ATTEMPTS', date: '2005-11-01' },
      { label: 'RETURN TO EARTH', date: '2010-06-13' },
    ],
  },
  {
    id: 'rosetta',
    name: 'Rosetta',
    agency: 'ESA',
    agencyLinkId: 'esa',
    country: 'Europe',
    type: 'COMET',
    destination: 'Comet 67P/Churyumov\u2013Gerasimenko',
    status: 'COMPLETED',
    crewed: false,
    launchDate: '2004-03-02',
    launchVehicle: 'Ariane 5',
    spacecraft: 'Rosetta orbiter / Philae lander',
    launchSite: 'Guiana Space Centre',
    duration: null,
    objective: 'Orbit a comet and land a probe on its nucleus.',
    description: 'Rosetta was the first spacecraft to orbit a comet nucleus and to deploy a lander, Philae, onto a comet\u2019s surface, studying 67P in unprecedented detail as it approached the Sun.',
    crewIds: [],
    timeline: [
      { label: 'LAUNCH', date: '2004-03-02' },
      { label: 'COMET RENDEZVOUS', date: '2014-08-06' },
      { label: 'PHILAE LANDING', date: '2014-11-12' },
      { label: 'PERIHELION ESCORT', date: '2015-08-13' },
      { label: 'MISSION END', date: '2016-09-30', note: 'Controlled descent onto the comet\u2019s surface.' },
    ],
  },
  {
    id: 'hayabusa2',
    name: 'Hayabusa2',
    agency: 'JAXA',
    agencyLinkId: 'jaxa',
    country: 'Japan',
    type: 'ASTEROID',
    destination: '162173 Ryugu / extended targets',
    status: 'EXTENDED',
    crewed: false,
    launchDate: '2014-12-03',
    launchVehicle: 'H-IIA',
    spacecraft: 'Hayabusa2',
    launchSite: 'Tanegashima Space Center',
    duration: null,
    objective: 'Return samples from asteroid Ryugu, then continue to additional asteroid targets.',
    description: 'Hayabusa2 collected surface and subsurface samples from asteroid Ryugu and returned them to Earth in 2020; the spacecraft continues on an extended mission toward additional small asteroids.',
    crewIds: [],
    timeline: [
      { label: 'LAUNCH', date: '2014-12-03' },
      { label: 'RYUGU RENDEZVOUS', date: '2018-06-27' },
      { label: 'SAMPLE COLLECTION', date: '2019-02-22' },
      { label: 'SAMPLE RETURN TO EARTH', date: '2020-12-06' },
      { label: 'EXTENDED MISSION', date: '2020-12-06', note: 'En route to additional small asteroids.' },
    ],
  },
  {
    id: 'osiris-rex',
    name: 'OSIRIS-REx',
    agency: 'NASA',
    agencyLinkId: 'nasa',
    country: 'United States',
    type: 'ASTEROID',
    destination: '101955 Bennu',
    status: 'COMPLETED',
    crewed: false,
    launchDate: '2016-09-08',
    launchVehicle: 'Atlas V',
    spacecraft: 'OSIRIS-REx',
    launchSite: 'Cape Canaveral',
    duration: null,
    objective: 'Return a sample from the carbon-rich asteroid Bennu.',
    description: 'OSIRIS-REx collected the largest sample ever returned from an asteroid, over 100 grams from Bennu, delivering it to Earth in 2023 before its spacecraft continued on to a new target as OSIRIS-APEX.',
    crewIds: [],
    timeline: [
      { label: 'LAUNCH', date: '2016-09-08' },
      { label: 'BENNU RENDEZVOUS', date: '2018-12-03' },
      { label: 'SAMPLE COLLECTION (TAG)', date: '2020-10-20' },
      { label: 'SAMPLE RETURN TO EARTH', date: '2023-09-24' },
    ],
  },
  {
    id: 'osiris-apex',
    name: 'OSIRIS-APEX',
    agency: 'NASA',
    agencyLinkId: 'nasa',
    country: 'United States',
    type: 'ASTEROID',
    destination: '99942 Apophis',
    status: 'ACTIVE',
    crewed: false,
    launchDate: '2016-09-08',
    launchVehicle: 'Atlas V',
    spacecraft: 'OSIRIS-APEX (formerly OSIRIS-REx)',
    launchSite: 'Cape Canaveral',
    duration: null,
    objective: 'Study the asteroid Apophis up close, including during its close 2029 Earth flyby.',
    description: 'Repurposed after delivering its Bennu sample, the same spacecraft is now headed toward Apophis to study the asteroid before and after its historically close approach to Earth in 2029.',
    crewIds: [],
    timeline: [
      { label: 'MISSION RENAMED / EXTENDED', date: '2023-09-24' },
      { label: 'CRUISE TO APOPHIS', date: '2023-09-24' },
      { label: 'APOPHIS ARRIVAL', date: null, note: 'Expected shortly after Apophis\u2019s April 2029 Earth flyby.' },
    ],
  },
  {
    id: 'dart',
    name: 'DART (Double Asteroid Redirection Test)',
    agency: 'NASA',
    agencyLinkId: 'nasa',
    country: 'United States',
    type: 'TECHNOLOGY DEMONSTRATION',
    destination: 'Dimorphos',
    status: 'COMPLETED',
    crewed: false,
    launchDate: '2021-11-24',
    launchVehicle: 'Falcon 9',
    spacecraft: 'DART',
    launchSite: 'Vandenberg SFB',
    duration: null,
    objective: 'Demonstrate deflecting an asteroid\u2019s orbit by deliberate kinetic impact.',
    description: 'DART deliberately collided with the moonlet Dimorphos, successfully shortening its orbit around the larger asteroid Didymos and proving kinetic impact as a viable planetary defense technique.',
    crewIds: [],
    timeline: [
      { label: 'LAUNCH', date: '2021-11-24' },
      { label: 'APPROACH TO DIDYMOS SYSTEM', date: '2022-09-26' },
      { label: 'KINETIC IMPACT', date: '2022-09-26', note: 'DART intentionally collides with Dimorphos.' },
      { label: 'ORBIT CHANGE CONFIRMED', date: '2022-10-11' },
    ],
  },
  {
    id: 'lucy',
    name: 'Lucy',
    agency: 'NASA',
    agencyLinkId: 'nasa',
    country: 'United States',
    type: 'ASTEROID',
    destination: 'Jupiter Trojan asteroids',
    status: 'ACTIVE',
    crewed: false,
    launchDate: '2021-10-16',
    launchVehicle: 'Atlas V',
    spacecraft: 'Lucy',
    launchSite: 'Cape Canaveral SFS',
    duration: null,
    objective: 'Fly by a record number of asteroids, including several Jupiter Trojans.',
    description: 'Lucy is on a 12-year tour to fly by both main-belt asteroids and multiple Jupiter Trojan asteroids, small bodies thought to be remnants from the early solar system, with its first Trojan encounters expected later in the decade.',
    crewIds: [],
    timeline: [
      { label: 'LAUNCH', date: '2021-10-16' },
      { label: 'DINKINESH FLYBY', date: '2023-11-01', note: 'Main-belt asteroid flyby.' },
      { label: 'DONALDJOHANSON FLYBY', date: '2025-04-20' },
      { label: 'TROJAN ASTEROID ENCOUNTERS', date: null, note: 'Beginning in 2027.' },
    ],
  },
  {
    id: 'psyche',
    name: 'Psyche',
    agency: 'NASA',
    agencyLinkId: 'nasa',
    country: 'United States',
    type: 'ASTEROID',
    destination: '16 Psyche',
    status: 'ACTIVE',
    crewed: false,
    launchDate: '2023-10-13',
    launchVehicle: 'Falcon Heavy',
    spacecraft: 'Psyche',
    launchSite: 'Kennedy Space Center LC-39A',
    duration: null,
    objective: 'Orbit and study the metal-rich asteroid Psyche, thought to be a remnant planetary core.',
    description: 'Psyche is cruising toward the metallic asteroid of the same name, which scientists believe may be the exposed iron-nickel core of an early planetary building block.',
    crewIds: [],
    timeline: [
      { label: 'LAUNCH', date: '2023-10-13' },
      { label: 'MARS GRAVITY ASSIST', date: '2026-05-01' },
      { label: 'PSYCHE ORBIT INSERTION', date: null, note: 'Expected in 2029.' },
    ],
  },
  {
    id: 'tianwen-2',
    name: 'Tianwen-2',
    agency: 'CNSA',
    agencyLinkId: 'cnsa',
    country: 'China',
    type: 'ASTEROID',
    destination: '469219 Kamo\u02bboalewa / 311P',
    status: 'ACTIVE',
    crewed: false,
    launchDate: '2025-05-29',
    launchVehicle: 'Long March 3B',
    spacecraft: 'Tianwen-2',
    launchSite: 'Xichang Satellite Launch Center',
    duration: null,
    objective: 'Return a sample from near-Earth quasi-satellite Kamo\u02bboalewa, then explore the active asteroid 311P/PANSTARRS.',
    description: 'Tianwen-2 arrived at the small near-Earth asteroid Kamo\u02bboalewa in 2026 to begin close-up survey operations ahead of a planned sample collection, with sample return to Earth expected in late 2027 before the spacecraft continues on to comet-like asteroid 311P/PANSTARRS.',
    crewIds: [],
    timeline: [
      { label: 'LAUNCH', date: '2025-05-29' },
      { label: 'ASTEROID RENDEZVOUS', date: '2026-06-07', note: 'Arrives at Kamo\u02bboalewa after a 400-day cruise.' },
      { label: 'CLOSE-PROXIMITY SURVEY', date: '2026-07-06' },
      { label: 'SAMPLE COLLECTION', date: null },
      { label: 'SAMPLE RETURN TO EARTH', date: null, note: 'Expected around November 2027.' },
    ],
  },
  {
    id: 'hera',
    name: 'Hera',
    agency: 'ESA',
    agencyLinkId: 'esa',
    country: 'Europe',
    type: 'ASTEROID',
    destination: 'Didymos / Dimorphos',
    status: 'ACTIVE',
    crewed: false,
    launchDate: '2024-10-07',
    launchVehicle: 'Falcon 9',
    spacecraft: 'Hera',
    launchSite: 'Kennedy Space Center',
    duration: null,
    objective: 'Survey the Didymos\u2013Dimorphos asteroid system to follow up on NASA\u2019s DART impact.',
    description: 'Hera is en route to closely examine the aftermath of DART\u2019s kinetic impact on Dimorphos, gathering detailed data on the crater and the asteroid\u2019s composition to refine planetary defense models.',
    crewIds: [],
    timeline: [
      { label: 'LAUNCH', date: '2024-10-07' },
      { label: 'MARS FLYBY', date: '2025-03-12' },
      { label: 'DIDYMOS SYSTEM ARRIVAL', date: null, note: 'Expected December 2026.' },
    ],
  },

  // =================================== SOLAR ====================================
  {
    id: 'soho',
    name: 'SOHO (Solar and Heliospheric Observatory)',
    agency: 'ESA / NASA',
    agencyLinkId: 'esa',
    country: 'Europe / United States',
    type: 'SOLAR',
    destination: 'Sun\u2013Earth L1',
    status: 'EXTENDED',
    crewed: false,
    launchDate: '1995-12-02',
    launchVehicle: 'Atlas IIAS',
    spacecraft: 'SOHO',
    launchSite: 'Cape Canaveral',
    duration: null,
    objective: 'Study the Sun\u2019s interior structure, outer atmosphere, and solar wind.',
    description: 'SOHO has observed the Sun continuously from the L1 Lagrange point for three decades, and its imagery has been used to discover more than 5,000 comets, making it the most prolific comet finder in history.',
    crewIds: [],
    timeline: [
      { label: 'LAUNCH', date: '1995-12-02' },
      { label: 'L1 ORBIT INSERTION', date: '1996-02-14' },
      { label: 'PRIMARY SCIENCE MISSION', date: '1996-05-01' },
      { label: 'EXTENDED MISSION', date: '1998-01-01' },
    ],
  },
  {
    id: 'parker-solar-probe',
    name: 'Parker Solar Probe',
    agency: 'NASA',
    agencyLinkId: 'nasa',
    country: 'United States',
    type: 'SOLAR',
    destination: 'Sun (corona)',
    status: 'ACTIVE',
    crewed: false,
    launchDate: '2018-08-12',
    launchVehicle: 'Delta IV Heavy',
    spacecraft: 'Parker Solar Probe',
    launchSite: 'Cape Canaveral',
    duration: null,
    objective: 'Fly closer to the Sun than any spacecraft in history to study the solar corona and solar wind.',
    description: 'Parker Solar Probe uses repeated Venus gravity assists to spiral ever closer to the Sun, having become the first spacecraft to "touch" the solar corona and set the record for closest and fastest approach to a star.',
    crewIds: [],
    timeline: [
      { label: 'LAUNCH', date: '2018-08-12' },
      { label: 'FIRST SOLAR APPROACH', date: '2018-11-05' },
      { label: 'VENUS GRAVITY ASSISTS', date: '2019-01-01' },
      { label: 'CLOSEST APPROACH TO DATE', date: '2024-12-24', note: 'Passes within about 6.1 million km of the Sun\u2019s surface.' },
    ],
  },
  {
    id: 'solar-orbiter',
    name: 'Solar Orbiter',
    agency: 'ESA / NASA',
    agencyLinkId: 'esa',
    country: 'Europe / United States',
    type: 'SOLAR',
    destination: 'Sun',
    status: 'ACTIVE',
    crewed: false,
    launchDate: '2020-02-10',
    launchVehicle: 'Atlas V',
    spacecraft: 'Solar Orbiter',
    launchSite: 'Cape Canaveral',
    duration: null,
    objective: 'Capture the first images of the Sun\u2019s poles and study the connection between the Sun and heliosphere.',
    description: 'Solar Orbiter uses gravity assists to progressively tilt its orbit out of the ecliptic plane, allowing it to capture the first-ever images of the Sun\u2019s polar regions.',
    crewIds: [],
    timeline: [
      { label: 'LAUNCH', date: '2020-02-10' },
      { label: 'VENUS GRAVITY ASSISTS', date: '2020-12-27' },
      { label: 'FIRST CLOSE PERIHELION', date: '2022-03-26' },
      { label: 'FIRST POLAR IMAGES', date: '2025-03-01' },
    ],
  },

  // ============================= EARTH / ASTRONOMY / SCIENCE ====================
  {
    id: 'hubble',
    name: 'Hubble Space Telescope',
    agency: 'NASA / ESA',
    agencyLinkId: 'nasa',
    country: 'United States / Europe',
    type: 'ASTRONOMY',
    destination: 'Low Earth Orbit',
    status: 'ACTIVE',
    crewed: false,
    launchDate: '1990-04-24',
    launchVehicle: 'Space Shuttle Discovery',
    spacecraft: 'Hubble Space Telescope',
    launchSite: 'Kennedy Space Center',
    duration: null,
    objective: 'Observe the universe in visible, ultraviolet, and near-infrared light from above the atmosphere.',
    description: 'Hubble has operated for over three decades, transforming astronomy with observations from nearby planets to the deepest reaches of the observable universe, and was serviced five times by Space Shuttle crews.',
    crewIds: [],
    timeline: [
      { label: 'LAUNCH', date: '1990-04-24' },
      { label: 'DEPLOYMENT', date: '1990-04-25' },
      { label: 'MIRROR FLAW DISCOVERED', date: '1990-06-27' },
      { label: 'FIRST SERVICING MISSION', date: '1993-12-02', note: 'Corrective optics installed by Shuttle astronauts.' },
      { label: 'CONTINUED OPERATIONS', date: '2009-05-11', note: 'Fifth and final servicing mission.' },
    ],
  },
  {
    id: 'jwst',
    name: 'James Webb Space Telescope',
    agency: 'NASA / ESA / CSA',
    agencyLinkId: 'nasa',
    country: 'United States / Europe / Canada',
    type: 'ASTRONOMY',
    destination: 'Sun\u2013Earth L2',
    status: 'ACTIVE',
    crewed: false,
    launchDate: '2021-12-25',
    launchVehicle: 'Ariane 5',
    spacecraft: 'James Webb Space Telescope',
    launchSite: 'Guiana Space Centre',
    duration: null,
    objective: 'Observe the universe in infrared light to study the earliest galaxies, star and planet formation, and exoplanet atmospheres.',
    description: 'JWST is the largest and most powerful space telescope ever launched, and has revealed galaxies from the early universe and detailed atmospheric compositions of exoplanets since beginning science operations in 2022.',
    crewIds: [],
    timeline: [
      { label: 'LAUNCH', date: '2021-12-25' },
      { label: 'SUNSHIELD & MIRROR DEPLOYMENT', date: '2022-01-08' },
      { label: 'L2 ORBIT INSERTION', date: '2022-01-24' },
      { label: 'FIRST SCIENCE IMAGES', date: '2022-07-12' },
    ],
  },
  {
    id: 'chandra',
    name: 'Chandra X-ray Observatory',
    agency: 'NASA',
    agencyLinkId: 'nasa',
    country: 'United States',
    type: 'ASTRONOMY',
    destination: 'High Earth Orbit',
    status: 'ACTIVE',
    crewed: false,
    launchDate: '1999-07-23',
    launchVehicle: 'Space Shuttle Columbia',
    spacecraft: 'Chandra X-ray Observatory',
    launchSite: 'Kennedy Space Center',
    duration: null,
    objective: 'Observe X-ray emission from hot regions of the universe such as black holes and supernova remnants.',
    description: 'Chandra is one of NASA\u2019s "Great Observatories" and has spent over two decades imaging X-ray sources including black holes, neutron stars, and the aftermath of supernova explosions.',
    crewIds: [],
    timeline: [
      { label: 'LAUNCH', date: '1999-07-23' },
      { label: 'DEPLOYMENT', date: '1999-07-23' },
      { label: 'PRIMARY SCIENCE MISSION', date: '1999-08-19' },
      { label: 'EXTENDED MISSION', date: '2001-01-01' },
    ],
  },
  {
    id: 'kepler',
    name: 'Kepler',
    agency: 'NASA',
    agencyLinkId: 'nasa',
    country: 'United States',
    type: 'ASTRONOMY',
    destination: 'Heliocentric Orbit',
    status: 'COMPLETED',
    crewed: false,
    launchDate: '2009-03-07',
    launchVehicle: 'Delta II',
    spacecraft: 'Kepler',
    launchSite: 'Cape Canaveral',
    duration: null,
    objective: 'Survey a patch of sky to detect Earth-sized exoplanets using the transit method.',
    description: 'Kepler discovered thousands of confirmed exoplanets and reshaped our understanding of how common planets are throughout the galaxy, operating for nine years before running out of fuel.',
    crewIds: [],
    timeline: [
      { label: 'LAUNCH', date: '2009-03-07' },
      { label: 'PRIMARY MISSION', date: '2009-05-12' },
      { label: 'REACTION WHEEL FAILURES', date: '2013-05-11', note: 'Prompts the extended K2 mission phase.' },
      { label: 'MISSION END', date: '2018-10-30', note: 'Spacecraft runs out of fuel.' },
    ],
  },
  {
    id: 'tess',
    name: 'TESS (Transiting Exoplanet Survey Satellite)',
    agency: 'NASA',
    agencyLinkId: 'nasa',
    country: 'United States',
    type: 'ASTRONOMY',
    destination: 'High Earth Orbit',
    status: 'EXTENDED',
    crewed: false,
    launchDate: '2018-04-18',
    launchVehicle: 'Falcon 9',
    spacecraft: 'TESS',
    launchSite: 'Cape Canaveral',
    duration: null,
    objective: 'Survey nearly the entire sky for transiting exoplanets around nearby bright stars.',
    description: 'TESS has surveyed most of the sky for planets orbiting nearby stars, finding thousands of candidate worlds for detailed follow-up study, and continues operating in an extended mission.',
    crewIds: [],
    timeline: [
      { label: 'LAUNCH', date: '2018-04-18' },
      { label: 'PRIMARY MISSION (ALL-SKY SURVEY)', date: '2018-07-25' },
      { label: 'EXTENDED MISSION', date: '2020-07-04' },
    ],
  },
  {
    id: 'gaia',
    name: 'Gaia',
    agency: 'ESA',
    agencyLinkId: 'esa',
    country: 'Europe',
    type: 'ASTRONOMY',
    destination: 'Sun\u2013Earth L2',
    status: 'COMPLETED',
    crewed: false,
    launchDate: '2013-12-19',
    launchVehicle: 'Soyuz',
    spacecraft: 'Gaia',
    launchSite: 'Guiana Space Centre',
    duration: null,
    objective: 'Precisely map the positions, distances, and motions of over a billion stars in the Milky Way.',
    description: 'Gaia created the most detailed 3D map of the Milky Way ever made, and its science observations concluded in early 2025 after more than a decade in orbit, with mission scientists continuing to process and release its data.',
    crewIds: [],
    timeline: [
      { label: 'LAUNCH', date: '2013-12-19' },
      { label: 'L2 ORBIT INSERTION', date: '2014-01-08' },
      { label: 'SCIENCE OPERATIONS', date: '2014-07-25' },
      { label: 'END OF OBSERVATIONS', date: '2025-01-15' },
    ],
  },
  {
    id: 'landsat-9',
    name: 'Landsat 9',
    agency: 'NASA / USGS',
    agencyLinkId: 'nasa',
    country: 'United States',
    type: 'EARTH OBSERVATION',
    destination: 'Sun-Synchronous Orbit',
    status: 'ACTIVE',
    crewed: false,
    launchDate: '2021-09-27',
    launchVehicle: 'Atlas V',
    spacecraft: 'Landsat 9',
    launchSite: 'Vandenberg SFB',
    duration: null,
    objective: 'Continue the decades-long Landsat record of Earth\u2019s land surface for environmental and land-use monitoring.',
    description: 'Landsat 9 extends the longest continuous record of Earth\u2019s land surface from space, tracking changes such as urban growth, deforestation, and agricultural conditions alongside its predecessor Landsat 8.',
    crewIds: [],
    timeline: [
      { label: 'LAUNCH', date: '2021-09-27' },
      { label: 'ORBIT INSERTION', date: '2021-09-27' },
      { label: 'OPERATIONAL IMAGING', date: '2022-02-10' },
    ],
  },

  // ================================ SPACE STATIONS ===============================
  {
    id: 'skylab',
    name: 'Skylab',
    agency: 'NASA',
    agencyLinkId: 'nasa',
    country: 'United States',
    type: 'SPACE STATION',
    destination: 'Low Earth Orbit',
    status: 'COMPLETED',
    crewed: true,
    launchDate: '1973-05-14',
    launchVehicle: 'Saturn V',
    spacecraft: 'Skylab',
    launchSite: 'Kennedy Space Center LC-39A',
    duration: null,
    objective: 'Operate the United States\u2019 first space station, hosting three crews for extended-duration research.',
    description: 'Skylab was America\u2019s first space station, hosting three crewed missions that studied the effects of long-duration spaceflight before the station\u2019s orbit decayed and it reentered the atmosphere in 1979.',
    crewIds: [],
    timeline: [
      { label: 'LAUNCH', date: '1973-05-14' },
      { label: 'FIRST CREW ARRIVAL', date: '1973-05-25' },
      { label: 'THIRD CREW DEPARTURE', date: '1974-02-08' },
      { label: 'REENTRY', date: '1979-07-11', note: 'Uncontrolled reentry scatters debris over Australia.' },
    ],
  },
  {
    id: 'mir',
    name: 'Mir',
    agency: 'Roscosmos',
    agencyLinkId: 'roscosmos',
    country: 'Russia / Soviet Union',
    type: 'SPACE STATION',
    destination: 'Low Earth Orbit',
    status: 'COMPLETED',
    crewed: true,
    launchDate: '1986-02-19',
    launchVehicle: 'Proton-K',
    spacecraft: 'Mir core module',
    launchSite: 'Baikonur Cosmodrome',
    duration: null,
    objective: 'Operate a modular, continuously crewed space station for long-duration research.',
    description: 'Mir was the first modular space station, continuously crewed for most of its 15 years in orbit, and hosted long-duration missions including Valeri Polyakov\u2019s record 437-day continuous spaceflight before its controlled deorbit in 2001.',
    crewIds: ['valeri-polyakov'],
    timeline: [
      { label: 'CORE MODULE LAUNCH', date: '1986-02-19' },
      { label: 'MODULE ADDITIONS', date: '1987-01-01', note: 'Additional science and docking modules launched through the 1990s.' },
      { label: 'SHUTTLE\u2013MIR DOCKINGS', date: '1995-06-29' },
      { label: 'DEORBIT', date: '2001-03-23', note: 'Controlled reentry over the South Pacific.' },
    ],
  },
  {
    id: 'iss',
    name: 'International Space Station',
    agency: 'NASA / Roscosmos / ESA / JAXA / CSA',
    agencyLinkId: 'nasa',
    country: 'International',
    type: 'SPACE STATION',
    destination: 'Low Earth Orbit',
    status: 'ACTIVE',
    crewed: true,
    launchDate: '1998-11-20',
    launchVehicle: 'Proton-K (Zarya module)',
    spacecraft: 'International Space Station',
    launchSite: 'Baikonur Cosmodrome',
    duration: null,
    objective: 'Operate a permanently crewed research laboratory in low Earth orbit through international partnership.',
    description: 'The ISS has been continuously crewed since November 2000, hosting rotating international crews for scientific research in microgravity; NASA and its partners plan to deorbit the station later this decade as commercial successors come online.',
    crewIds: ['peggy-whitson', 'scott-kelly', 'christina-koch', 'samantha-cristoforetti', 'frank-rubio'],
    timeline: [
      { label: 'ZARYA MODULE LAUNCH', date: '1998-11-20' },
      { label: 'UNITY MODULE DOCKING', date: '1998-12-06' },
      { label: 'FIRST RESIDENT CREW (EXPEDITION 1)', date: '2000-11-02' },
      { label: 'CONTINUOUS HABITATION', date: '2000-11-02', note: 'Continuously crewed ever since.' },
    ],
  },
  {
    id: 'tiangong-1',
    name: 'Tiangong-1',
    agency: 'CNSA',
    agencyLinkId: 'cnsa',
    country: 'China',
    type: 'SPACE STATION',
    destination: 'Low Earth Orbit',
    status: 'COMPLETED',
    crewed: true,
    launchDate: '2011-09-29',
    launchVehicle: 'Long March 2F',
    spacecraft: 'Tiangong-1',
    launchSite: 'Jiuquan Satellite Launch Center',
    duration: null,
    objective: 'Serve as China\u2019s first space station and docking target for crewed test missions.',
    description: 'Tiangong-1 was China\u2019s first prototype space station, hosting two crewed missions to test docking procedures before its systems failed and it made an uncontrolled reentry in 2018.',
    crewIds: ['liu-yang'],
    timeline: [
      { label: 'LAUNCH', date: '2011-09-29' },
      { label: 'SHENZHOU 9 DOCKING', date: '2012-06-18' },
      { label: 'SHENZHOU 10 DOCKING', date: '2013-06-13' },
      { label: 'UNCONTROLLED REENTRY', date: '2018-04-02', note: 'Reenters over the South Pacific.' },
    ],
  },
  {
    id: 'tiangong',
    name: 'Tiangong Space Station',
    agency: 'CNSA',
    agencyLinkId: 'cnsa',
    country: 'China',
    type: 'SPACE STATION',
    destination: 'Low Earth Orbit',
    status: 'ACTIVE',
    crewed: true,
    launchDate: '2021-04-29',
    launchVehicle: 'Long March 5B',
    spacecraft: 'Tianhe core module',
    launchSite: 'Wenchang Space Launch Site',
    duration: null,
    objective: 'Operate China\u2019s permanent, modular space station in low Earth orbit.',
    description: 'Tiangong is China\u2019s permanently crewed space station, built from the Tianhe core module plus two laboratory modules, and has hosted continuous rotating Shenzhou crews since 2022.',
    crewIds: ['wang-yaping'],
    timeline: [
      { label: 'TIANHE CORE MODULE LAUNCH', date: '2021-04-29' },
      { label: 'FIRST CREW ARRIVAL (SHENZHOU 12)', date: '2021-06-17' },
      { label: 'LABORATORY MODULE ADDITIONS', date: '2022-07-24' },
      { label: 'CONTINUOUS CREWED OPERATIONS', date: '2022-12-01' },
    ],
  },

  // =========================== TECHNOLOGY DEMONSTRATION ==========================
  {
    id: 'deep-space-1',
    name: 'Deep Space 1',
    agency: 'NASA',
    agencyLinkId: 'nasa',
    country: 'United States',
    type: 'TECHNOLOGY DEMONSTRATION',
    destination: 'Asteroid Braille / Comet Borrelly',
    status: 'COMPLETED',
    crewed: false,
    launchDate: '1998-10-24',
    launchVehicle: 'Delta II',
    spacecraft: 'Deep Space 1',
    launchSite: 'Cape Canaveral',
    duration: null,
    objective: 'Test ion propulsion and autonomous navigation technologies later used on many deep-space missions.',
    description: 'Deep Space 1 validated ion engine propulsion and autonomous navigation software in flight, technologies that went on to be used by later missions including Dawn and Hayabusa2, while also flying past an asteroid and a comet.',
    crewIds: [],
    timeline: [
      { label: 'LAUNCH', date: '1998-10-24' },
      { label: 'ASTEROID BRAILLE FLYBY', date: '1999-07-29' },
      { label: 'COMET BORRELLY FLYBY', date: '2001-09-22' },
      { label: 'MISSION END', date: '2001-12-18' },
    ],
  },
  {
    id: 'lcross',
    name: 'LCROSS',
    agency: 'NASA',
    agencyLinkId: 'nasa',
    country: 'United States',
    type: 'TECHNOLOGY DEMONSTRATION',
    destination: 'Moon',
    status: 'COMPLETED',
    crewed: false,
    launchDate: '2009-06-18',
    launchVehicle: 'Atlas V',
    spacecraft: 'LCROSS',
    launchSite: 'Cape Canaveral',
    duration: null,
    objective: 'Search for water ice in a permanently shadowed lunar crater by deliberately impacting it.',
    description: 'LCROSS sent a spent rocket stage crashing into a permanently shadowed crater near the lunar south pole, and analysis of the resulting debris plume confirmed the presence of water ice.',
    crewIds: [],
    timeline: [
      { label: 'LAUNCH', date: '2009-06-18' },
      { label: 'LUNAR ORBIT PHASE', date: '2009-06-23' },
      { label: 'CENTAUR IMPACT', date: '2009-10-09', note: 'Impacts Cabeus crater near the lunar south pole.' },
      { label: 'SHEPHERDING SPACECRAFT IMPACT', date: '2009-10-09' },
    ],
  },
  {
    id: 'x-37b',
    name: 'X-37B (Orbital Test Vehicle)',
    agency: 'US Space Force',
    agencyLinkId: null,
    country: 'United States',
    type: 'TECHNOLOGY DEMONSTRATION',
    destination: 'Low Earth Orbit',
    status: 'ACTIVE',
    crewed: false,
    launchDate: '2010-04-22',
    launchVehicle: 'Atlas V',
    spacecraft: 'X-37B',
    launchSite: 'Cape Canaveral',
    duration: null,
    objective: 'Test reusable spaceplane technologies and host experimental payloads on long-duration orbital missions.',
    description: 'The uncrewed, reusable X-37B spaceplane has flown a series of long-duration classified test missions since 2010, landing autonomously on a runway like the Space Shuttle after each flight.',
    crewIds: [],
    timeline: [
      { label: 'FIRST LAUNCH (OTV-1)', date: '2010-04-22' },
      { label: 'SUBSEQUENT MISSIONS', date: '2012-03-01', note: 'Multiple additional long-duration missions have followed.' },
      { label: 'AUTONOMOUS RUNWAY LANDINGS', date: '2010-12-03' },
    ],
  },
  {
    id: 'starship-flight-test-program',
    name: 'Starship Integrated Flight Test Program',
    agency: 'SpaceX',
    agencyLinkId: 'spacex',
    country: 'United States',
    type: 'TECHNOLOGY DEMONSTRATION',
    destination: 'Suborbital / Orbital',
    status: 'ACTIVE',
    crewed: false,
    launchDate: '2023-04-20',
    launchVehicle: 'Starship / Super Heavy',
    spacecraft: 'Starship',
    launchSite: 'Starbase Boca Chica',
    duration: null,
    objective: 'Flight-test the fully reusable Starship and Super Heavy launch system toward orbital and lunar/Mars capability.',
    description: 'SpaceX\u2019s iterative Starship flight test campaign has flown a series of increasingly complex integrated test flights, including booster catches at the launch tower, working toward a fully and rapidly reusable launch system for missions including NASA\u2019s Artemis lunar lander.',
    crewIds: [],
    timeline: [
      { label: 'FIRST INTEGRATED FLIGHT TEST', date: '2023-04-20', note: 'Vehicle breaks up shortly after launch.' },
      { label: 'FIRST SUCCESSFUL BOOSTER CATCH', date: '2024-10-13' },
      { label: 'CONTINUED TEST CAMPAIGN', date: null, note: 'Additional test flights ongoing.' },
    ],
  },

  // ================================ EARTH SCIENCE / OTHER =========================
  {
    id: 'mars-express',
    name: 'Mars Express',
    agency: 'ESA',
    agencyLinkId: 'esa',
    country: 'Europe',
    type: 'MARS',
    destination: 'Mars',
    status: 'ACTIVE',
    crewed: false,
    launchDate: '2003-06-02',
    launchVehicle: 'Soyuz',
    spacecraft: 'Mars Express',
    launchSite: 'Baikonur Cosmodrome',
    duration: null,
    objective: 'Study the Martian surface, subsurface, and atmosphere from orbit.',
    description: 'Mars Express has orbited Mars for over two decades, providing high-resolution imagery and finding strong evidence for subsurface liquid water, despite the loss of its Beagle 2 lander on arrival.',
    crewIds: [],
    timeline: [
      { label: 'LAUNCH', date: '2003-06-02' },
      { label: 'BEAGLE 2 LANDER RELEASE', date: '2003-12-19', note: 'Lander is lost; contact never established.' },
      { label: 'MARS ORBIT INSERTION', date: '2003-12-25' },
      { label: 'EXTENDED MISSION', date: '2007-01-01' },
    ],
  },
  {
    id: 'exomars-tgo',
    name: 'ExoMars Trace Gas Orbiter',
    agency: 'ESA / Roscosmos',
    agencyLinkId: 'esa',
    country: 'Europe / Russia',
    type: 'MARS',
    destination: 'Mars',
    status: 'ACTIVE',
    crewed: false,
    launchDate: '2016-03-14',
    launchVehicle: 'Proton-M',
    spacecraft: 'Trace Gas Orbiter',
    launchSite: 'Baikonur Cosmodrome',
    duration: null,
    objective: 'Study trace gases in the Martian atmosphere, including methane, and relay data from surface missions.',
    description: 'The Trace Gas Orbiter studies the Martian atmosphere\u2019s composition in search of gases like methane that could hint at geological or biological activity, and serves as a relay for Mars surface missions.',
    crewIds: [],
    timeline: [
      { label: 'LAUNCH', date: '2016-03-14' },
      { label: 'MARS ORBIT INSERTION', date: '2016-10-19' },
      { label: 'AEROBRAKING PHASE', date: '2017-03-01' },
      { label: 'SCIENCE OPERATIONS', date: '2018-04-21' },
    ],
  },
  {
    id: 'mangalyaan',
    name: 'Mars Orbiter Mission (Mangalyaan)',
    agency: 'ISRO',
    agencyLinkId: 'isro',
    country: 'India',
    type: 'MARS',
    destination: 'Mars',
    status: 'COMPLETED',
    crewed: false,
    launchDate: '2013-11-05',
    launchVehicle: 'PSLV',
    spacecraft: 'Mangalyaan',
    launchSite: 'Satish Dhawan Space Centre',
    duration: null,
    objective: 'Demonstrate India\u2019s capability to reach Mars and study its atmosphere and surface.',
    description: 'Mangalyaan made India the first country to reach Mars orbit on its first attempt and the least expensive Mars mission to date, operating for years beyond its planned six-month mission.',
    crewIds: [],
    timeline: [
      { label: 'LAUNCH', date: '2013-11-05' },
      { label: 'TRANS-MARS INJECTION', date: '2013-12-01' },
      { label: 'MARS ORBIT INSERTION', date: '2014-09-24' },
      { label: 'MISSION END', date: '2022-10-02', note: 'Contact lost after fuel depletion.' },
    ],
  },
  {
    id: 'mars-odyssey',
    name: 'Mars Odyssey',
    agency: 'NASA',
    agencyLinkId: 'nasa',
    country: 'United States',
    type: 'MARS',
    destination: 'Mars',
    status: 'ACTIVE',
    crewed: false,
    launchDate: '2001-04-07',
    launchVehicle: 'Delta II',
    spacecraft: 'Mars Odyssey',
    launchSite: 'Cape Canaveral',
    duration: null,
    objective: 'Map the mineralogy and radiation environment of Mars and relay data from surface missions.',
    description: 'Mars Odyssey is the longest-operating spacecraft ever sent to Mars, having mapped evidence of subsurface water ice and served as a communications relay for numerous Mars surface missions for over two decades.',
    crewIds: [],
    timeline: [
      { label: 'LAUNCH', date: '2001-04-07' },
      { label: 'MARS ORBIT INSERTION', date: '2001-10-24' },
      { label: 'PRIMARY SCIENCE MISSION', date: '2002-02-19' },
      { label: 'EXTENDED MISSION', date: '2004-01-01' },
    ],
  },
];
