// Astronaut / spaceflight-crew dataset for SpaceTec's Astronaut Database.
//
// Every entry here is built from well-established, publicly documented
// spaceflight history (agency biographies, mission records). Fields that
// aren't reliably known for a given astronaut are simply omitted — the UI
// renders those as "DATA UNAVAILABLE" rather than guessing. Nothing here
// is fabricated.
//
// `agencyLinkId` matches an id in SpaceTecHub.js's AGENCIES list, so the
// astronaut profile can deep-link straight to that agency's existing card
// instead of duplicating agency info.

export const STATUS_VALUES = ['ACTIVE', 'RETIRED', 'DECEASED'];

export const ASTRONAUTS = [
  {
    id: 'yuri-gagarin',
    name: 'Yuri Gagarin',
    agency: 'Soviet Space Programme',
    agencyLinkId: 'roscosmos',
    nationality: 'Soviet Union',
    status: 'DECEASED',
    selectionYear: 1960,
    spacecraftFlown: ['Vostok'],
    launchVehiclesFlown: ['Vostok-K'],
    launchSites: ['Baikonur Cosmodrome'],
    spacewalks: { count: 0, totalTime: null },
    missions: [
      {
        name: 'Vostok 1',
        launchDate: '1961-04-12',
        spacecraft: 'Vostok',
        launchVehicle: 'Vostok-K',
        launchSite: 'Baikonur Cosmodrome',
        role: 'Pilot',
        duration: '1 hour 48 minutes',
        note: 'First human spaceflight in history.',
      },
    ],
  },
  {
    id: 'valentina-tereshkova',
    name: 'Valentina Tereshkova',
    agency: 'Soviet Space Programme',
    agencyLinkId: 'roscosmos',
    nationality: 'Soviet Union',
    status: 'RETIRED',
    selectionYear: 1962,
    spacecraftFlown: ['Vostok'],
    launchVehiclesFlown: ['Vostok-K'],
    launchSites: ['Baikonur Cosmodrome'],
    spacewalks: { count: 0, totalTime: null },
    missions: [
      {
        name: 'Vostok 6',
        launchDate: '1963-06-16',
        spacecraft: 'Vostok',
        launchVehicle: 'Vostok-K',
        launchSite: 'Baikonur Cosmodrome',
        role: 'Pilot',
        duration: '2 days 22 hours 50 minutes',
        note: 'First woman in space.',
      },
    ],
  },
  {
    id: 'alexei-leonov',
    name: 'Alexei Leonov',
    agency: 'Soviet Space Programme',
    agencyLinkId: 'roscosmos',
    nationality: 'Soviet Union',
    status: 'DECEASED',
    selectionYear: 1960,
    spacecraftFlown: ['Voskhod', 'Soyuz'],
    launchVehiclesFlown: ['Voskhod', 'Soyuz'],
    launchSites: ['Baikonur Cosmodrome'],
    spacewalks: { count: 1, totalTime: '12 minutes 9 seconds' },
    missions: [
      {
        name: 'Voskhod 2',
        launchDate: '1965-03-18',
        spacecraft: 'Voskhod',
        launchVehicle: 'Voskhod',
        launchSite: 'Baikonur Cosmodrome',
        role: 'Pilot',
        duration: '1 day 2 hours',
        note: 'Performed the first spacewalk in history.',
      },
      {
        name: 'Soyuz 19 (Apollo–Soyuz Test Project)',
        launchDate: '1975-07-15',
        spacecraft: 'Soyuz',
        launchVehicle: 'Soyuz',
        launchSite: 'Baikonur Cosmodrome',
        role: 'Commander',
        duration: '5 days 22 hours 30 minutes',
      },
    ],
  },
  {
    id: 'neil-armstrong',
    name: 'Neil Armstrong',
    agency: 'NASA',
    agencyLinkId: 'nasa',
    nationality: 'United States',
    status: 'DECEASED',
    selectionYear: 1962,
    spacecraftFlown: ['Gemini', 'Apollo Command/Service Module', 'Apollo Lunar Module'],
    launchVehiclesFlown: ['Titan II GLV', 'Saturn V'],
    launchSites: ['Cape Canaveral', 'Kennedy Space Center'],
    spacewalks: { count: 1, totalTime: '2 hours 31 minutes' },
    missions: [
      {
        name: 'Gemini 8',
        launchDate: '1966-03-16',
        spacecraft: 'Gemini',
        launchVehicle: 'Titan II GLV',
        launchSite: 'Cape Canaveral',
        role: 'Command Pilot',
        duration: '10 hours 41 minutes',
        note: 'First docking of two spacecraft in orbit.',
      },
      {
        name: 'Apollo 11',
        launchDate: '1969-07-16',
        spacecraft: 'Apollo Command/Service Module & Lunar Module',
        launchVehicle: 'Saturn V',
        launchSite: 'Kennedy Space Center',
        role: 'Commander',
        duration: '8 days 3 hours 18 minutes',
        note: 'First crewed lunar landing; first person to walk on the Moon.',
      },
    ],
  },
  {
    id: 'buzz-aldrin',
    name: 'Buzz Aldrin',
    agency: 'NASA',
    agencyLinkId: 'nasa',
    nationality: 'United States',
    status: 'RETIRED',
    selectionYear: 1963,
    spacecraftFlown: ['Gemini', 'Apollo Command/Service Module', 'Apollo Lunar Module'],
    launchVehiclesFlown: ['Titan II GLV', 'Saturn V'],
    launchSites: ['Cape Canaveral', 'Kennedy Space Center'],
    spacewalks: { count: 4, totalTime: '7 hours 52 minutes' },
    missions: [
      {
        name: 'Gemini 12',
        launchDate: '1966-11-11',
        spacecraft: 'Gemini',
        launchVehicle: 'Titan II GLV',
        launchSite: 'Cape Canaveral',
        role: 'Pilot',
        duration: '3 days 22 hours 34 minutes',
      },
      {
        name: 'Apollo 11',
        launchDate: '1969-07-16',
        spacecraft: 'Apollo Command/Service Module & Lunar Module',
        launchVehicle: 'Saturn V',
        launchSite: 'Kennedy Space Center',
        role: 'Lunar Module Pilot',
        duration: '8 days 3 hours 18 minutes',
        note: 'Second person to walk on the Moon.',
      },
    ],
  },
  {
    id: 'michael-collins',
    name: 'Michael Collins',
    agency: 'NASA',
    agencyLinkId: 'nasa',
    nationality: 'United States',
    status: 'DECEASED',
    selectionYear: 1963,
    spacecraftFlown: ['Gemini', 'Apollo Command/Service Module'],
    launchVehiclesFlown: ['Titan II GLV', 'Saturn V'],
    launchSites: ['Cape Canaveral', 'Kennedy Space Center'],
    spacewalks: { count: 1, totalTime: '39 minutes' },
    missions: [
      {
        name: 'Gemini 10',
        launchDate: '1966-07-18',
        spacecraft: 'Gemini',
        launchVehicle: 'Titan II GLV',
        launchSite: 'Cape Canaveral',
        role: 'Pilot',
        duration: '2 days 22 hours 47 minutes',
      },
      {
        name: 'Apollo 11',
        launchDate: '1969-07-16',
        spacecraft: 'Apollo Command/Service Module',
        launchVehicle: 'Saturn V',
        launchSite: 'Kennedy Space Center',
        role: 'Command Module Pilot',
        duration: '8 days 3 hours 18 minutes',
        note: 'Piloted the Command Module in lunar orbit during the Apollo 11 landing.',
      },
    ],
  },
  {
    id: 'john-glenn',
    name: 'John Glenn',
    agency: 'NASA',
    agencyLinkId: 'nasa',
    nationality: 'United States',
    status: 'DECEASED',
    selectionYear: 1959,
    spacecraftFlown: ['Mercury', 'Space Shuttle'],
    launchVehiclesFlown: ['Atlas LV-3B', 'Space Shuttle'],
    launchSites: ['Cape Canaveral', 'Kennedy Space Center'],
    spacewalks: { count: 0, totalTime: null },
    missions: [
      {
        name: 'Mercury-Atlas 6 (Friendship 7)',
        launchDate: '1962-02-20',
        spacecraft: 'Mercury',
        launchVehicle: 'Atlas LV-3B',
        launchSite: 'Cape Canaveral',
        role: 'Pilot',
        duration: '4 hours 55 minutes',
        note: 'First American to orbit the Earth.',
      },
      {
        name: 'STS-95',
        launchDate: '1998-10-29',
        spacecraft: 'Space Shuttle Discovery',
        launchVehicle: 'Space Shuttle',
        launchSite: 'Kennedy Space Center',
        role: 'Payload Specialist',
        duration: '8 days 21 hours 44 minutes',
        note: 'At 77, became the oldest person to fly in space at the time.',
      },
    ],
  },
  {
    id: 'sally-ride',
    name: 'Sally Ride',
    agency: 'NASA',
    agencyLinkId: 'nasa',
    nationality: 'United States',
    status: 'DECEASED',
    selectionYear: 1978,
    spacecraftFlown: ['Space Shuttle'],
    launchVehiclesFlown: ['Space Shuttle'],
    launchSites: ['Kennedy Space Center'],
    spacewalks: { count: 0, totalTime: null },
    missions: [
      {
        name: 'STS-7',
        launchDate: '1983-06-18',
        spacecraft: 'Space Shuttle Challenger',
        launchVehicle: 'Space Shuttle',
        launchSite: 'Kennedy Space Center',
        role: 'Mission Specialist',
        duration: '6 days 2 hours 24 minutes',
        note: 'First American woman in space.',
      },
      {
        name: 'STS-41-G',
        launchDate: '1984-10-05',
        spacecraft: 'Space Shuttle Challenger',
        launchVehicle: 'Space Shuttle',
        launchSite: 'Kennedy Space Center',
        role: 'Mission Specialist',
        duration: '8 days 5 hours 24 minutes',
      },
    ],
  },
  {
    id: 'sunita-williams',
    name: 'Sunita Williams',
    agency: 'NASA',
    agencyLinkId: 'nasa',
    nationality: 'United States',
    status: 'ACTIVE',
    selectionYear: 1998,
    spacecraftFlown: ['Space Shuttle', 'Soyuz', 'Boeing Starliner'],
    launchVehiclesFlown: ['Space Shuttle', 'Soyuz', 'Atlas V'],
    launchSites: ['Kennedy Space Center', 'Baikonur Cosmodrome', 'Cape Canaveral'],
    spacewalks: { count: 9, totalTime: '62 hours 6 minutes' },
    missions: [
      {
        name: 'STS-116 / Expedition 14/15',
        launchDate: '2006-12-09',
        spacecraft: 'Space Shuttle Discovery / ISS',
        launchVehicle: 'Space Shuttle',
        launchSite: 'Kennedy Space Center',
        role: 'Flight Engineer',
        duration: '195 days 18 hours',
      },
      {
        name: 'Soyuz TMA-05M / Expedition 32/33',
        launchDate: '2012-07-15',
        spacecraft: 'Soyuz',
        launchVehicle: 'Soyuz',
        launchSite: 'Baikonur Cosmodrome',
        role: 'ISS Commander (Expedition 33)',
        duration: '127 days',
      },
      {
        name: 'Boeing Crewed Flight Test / Expedition 71/72',
        launchDate: '2024-06-05',
        spacecraft: 'Boeing Starliner',
        launchVehicle: 'Atlas V',
        launchSite: 'Cape Canaveral',
        role: 'Pilot',
        duration: null,
        note: 'Extended ISS stay after Starliner returned uncrewed; came home on a Crew Dragon.',
      },
    ],
  },
  {
    id: 'peggy-whitson',
    name: 'Peggy Whitson',
    agency: 'NASA',
    agencyLinkId: 'nasa',
    nationality: 'United States',
    status: 'ACTIVE',
    selectionYear: 1996,
    spacecraftFlown: ['Space Shuttle', 'Soyuz', 'Crew Dragon'],
    launchVehiclesFlown: ['Space Shuttle', 'Soyuz', 'Falcon 9'],
    launchSites: ['Kennedy Space Center', 'Baikonur Cosmodrome'],
    spacewalks: { count: 10, totalTime: '60 hours 21 minutes' },
    missions: [
      {
        name: 'STS-111 / Expedition 5',
        launchDate: '2002-06-05',
        spacecraft: 'Space Shuttle Endeavour / ISS',
        launchVehicle: 'Space Shuttle',
        launchSite: 'Kennedy Space Center',
        role: 'Flight Engineer',
        duration: '184 days',
      },
      {
        name: 'Soyuz TMA-11 / Expedition 16',
        launchDate: '2007-10-10',
        spacecraft: 'Soyuz',
        launchVehicle: 'Soyuz',
        launchSite: 'Baikonur Cosmodrome',
        role: 'ISS Commander',
        duration: '191 days',
        note: 'First woman to command the ISS.',
      },
      {
        name: 'Soyuz MS-03 / Expedition 50/51',
        launchDate: '2016-11-17',
        spacecraft: 'Soyuz',
        launchVehicle: 'Soyuz',
        launchSite: 'Baikonur Cosmodrome',
        role: 'ISS Commander (Expedition 51)',
        duration: '289 days',
      },
      {
        name: 'Axiom Mission 2',
        launchDate: '2023-05-21',
        spacecraft: 'Crew Dragon',
        launchVehicle: 'Falcon 9',
        launchSite: 'Kennedy Space Center',
        role: 'Commander',
        duration: '8 days',
      },
    ],
  },
  {
    id: 'scott-kelly',
    name: 'Scott Kelly',
    agency: 'NASA',
    agencyLinkId: 'nasa',
    nationality: 'United States',
    status: 'RETIRED',
    selectionYear: 1996,
    spacecraftFlown: ['Space Shuttle', 'Soyuz'],
    launchVehiclesFlown: ['Space Shuttle', 'Soyuz'],
    launchSites: ['Kennedy Space Center', 'Baikonur Cosmodrome'],
    spacewalks: { count: 3, totalTime: '12 hours 1 minute' },
    missions: [
      {
        name: 'STS-103',
        launchDate: '1999-12-19',
        spacecraft: 'Space Shuttle Discovery',
        launchVehicle: 'Space Shuttle',
        launchSite: 'Kennedy Space Center',
        role: 'Pilot',
        duration: '7 days 23 hours',
      },
      {
        name: 'STS-118',
        launchDate: '2007-08-08',
        spacecraft: 'Space Shuttle Endeavour',
        launchVehicle: 'Space Shuttle',
        launchSite: 'Kennedy Space Center',
        role: 'Commander',
        duration: '12 days 17 hours',
      },
      {
        name: 'Soyuz TMA-18M / Expedition 43/44/45/46 ("Year in Space")',
        launchDate: '2015-03-27',
        spacecraft: 'Soyuz',
        launchVehicle: 'Soyuz',
        launchSite: 'Baikonur Cosmodrome',
        role: 'ISS Commander (Expedition 46)',
        duration: '340 days',
        note: 'Longest single spaceflight by a NASA astronaut at the time.',
      },
    ],
  },
  {
    id: 'christina-koch',
    name: 'Christina Koch',
    agency: 'NASA',
    agencyLinkId: 'nasa',
    nationality: 'United States',
    status: 'ACTIVE',
    selectionYear: 2013,
    spacecraftFlown: ['Soyuz'],
    launchVehiclesFlown: ['Soyuz'],
    launchSites: ['Baikonur Cosmodrome'],
    spacewalks: { count: 6, totalTime: '42 hours 15 minutes' },
    missions: [
      {
        name: 'Soyuz MS-12 / Expedition 59/60/61',
        launchDate: '2019-03-14',
        spacecraft: 'Soyuz',
        launchVehicle: 'Soyuz',
        launchSite: 'Baikonur Cosmodrome',
        role: 'Flight Engineer',
        duration: '328 days',
        note: 'Longest single spaceflight by a woman at the time; part of the first all-female spacewalk with Jessica Meir.',
      },
    ],
  },
  {
    id: 'samantha-cristoforetti',
    name: 'Samantha Cristoforetti',
    agency: 'European Space Agency',
    agencyLinkId: 'esa',
    nationality: 'Italy',
    status: 'ACTIVE',
    selectionYear: 2009,
    spacecraftFlown: ['Soyuz', 'Crew Dragon'],
    launchVehiclesFlown: ['Soyuz', 'Falcon 9'],
    launchSites: ['Baikonur Cosmodrome', 'Kennedy Space Center'],
    spacewalks: { count: 1, totalTime: '7 hours 5 minutes' },
    missions: [
      {
        name: 'Soyuz TMA-15M / Expedition 42/43',
        launchDate: '2014-11-23',
        spacecraft: 'Soyuz',
        launchVehicle: 'Soyuz',
        launchSite: 'Baikonur Cosmodrome',
        role: 'Flight Engineer',
        duration: '199 days 16 hours',
        note: 'Longest single spaceflight by a woman at the time of return.',
      },
      {
        name: 'Crew-4 / Expedition 67/68',
        launchDate: '2022-04-27',
        spacecraft: 'Crew Dragon',
        launchVehicle: 'Falcon 9',
        launchSite: 'Kennedy Space Center',
        role: 'ISS Commander (Expedition 68)',
        duration: '170 days',
        note: 'First European woman to command the ISS.',
      },
    ],
  },
  {
    id: 'tim-peake',
    name: 'Tim Peake',
    agency: 'European Space Agency',
    agencyLinkId: 'esa',
    nationality: 'United Kingdom',
    status: 'RETIRED',
    selectionYear: 2009,
    spacecraftFlown: ['Soyuz'],
    launchVehiclesFlown: ['Soyuz'],
    launchSites: ['Baikonur Cosmodrome'],
    spacewalks: { count: 1, totalTime: '4 hours 43 minutes' },
    missions: [
      {
        name: 'Soyuz TMA-19M / Expedition 46/47',
        launchDate: '2015-12-15',
        spacecraft: 'Soyuz',
        launchVehicle: 'Soyuz',
        launchSite: 'Baikonur Cosmodrome',
        role: 'Flight Engineer',
        duration: '186 days',
        note: 'First British ESA astronaut on the ISS.',
      },
    ],
  },
  {
    id: 'thomas-pesquet',
    name: 'Thomas Pesquet',
    agency: 'European Space Agency',
    agencyLinkId: 'esa',
    nationality: 'France',
    status: 'ACTIVE',
    selectionYear: 2009,
    spacecraftFlown: ['Soyuz', 'Crew Dragon'],
    launchVehiclesFlown: ['Soyuz', 'Falcon 9'],
    launchSites: ['Baikonur Cosmodrome', 'Kennedy Space Center'],
    spacewalks: { count: 4, totalTime: '23 hours 24 minutes' },
    missions: [
      {
        name: 'Soyuz MS-03 / Expedition 50/51',
        launchDate: '2016-11-17',
        spacecraft: 'Soyuz',
        launchVehicle: 'Soyuz',
        launchSite: 'Baikonur Cosmodrome',
        role: 'Flight Engineer',
        duration: '196 days',
      },
      {
        name: 'Crew-2 / Expedition 65',
        launchDate: '2021-04-23',
        spacecraft: 'Crew Dragon',
        launchVehicle: 'Falcon 9',
        launchSite: 'Kennedy Space Center',
        role: 'ISS Commander (Expedition 65)',
        duration: '199 days',
        note: 'First French astronaut to command the ISS.',
      },
    ],
  },
  {
    id: 'rakesh-sharma',
    name: 'Rakesh Sharma',
    agency: 'Intercosmos (Soviet–Indian mission)',
    agencyLinkId: null,
    nationality: 'India',
    status: 'RETIRED',
    selectionYear: 1982,
    spacecraftFlown: ['Soyuz'],
    launchVehiclesFlown: ['Soyuz'],
    launchSites: ['Baikonur Cosmodrome'],
    spacewalks: { count: 0, totalTime: null },
    missions: [
      {
        name: 'Soyuz T-11',
        launchDate: '1984-04-03',
        spacecraft: 'Soyuz',
        launchVehicle: 'Soyuz',
        launchSite: 'Baikonur Cosmodrome',
        role: 'Cosmonaut Researcher',
        duration: '7 days 21 hours 40 minutes',
        note: 'First Indian citizen in space, flown under the Soviet Intercosmos programme.',
      },
    ],
  },
  {
    id: 'yang-liwei',
    name: 'Yang Liwei',
    agency: 'CNSA',
    agencyLinkId: 'cnsa',
    nationality: 'China',
    status: 'RETIRED',
    selectionYear: 1998,
    spacecraftFlown: ['Shenzhou'],
    launchVehiclesFlown: ['Long March 2F'],
    launchSites: ['Jiuquan Satellite Launch Center'],
    spacewalks: { count: 0, totalTime: null },
    missions: [
      {
        name: 'Shenzhou 5',
        launchDate: '2003-10-15',
        spacecraft: 'Shenzhou',
        launchVehicle: 'Long March 2F',
        launchSite: 'Jiuquan Satellite Launch Center',
        role: 'Pilot',
        duration: '21 hours 22 minutes',
        note: 'First crewed Chinese spaceflight.',
      },
    ],
  },
  {
    id: 'liu-yang',
    name: 'Liu Yang',
    agency: 'CNSA',
    agencyLinkId: 'cnsa',
    nationality: 'China',
    status: 'ACTIVE',
    selectionYear: 2010,
    spacecraftFlown: ['Shenzhou'],
    launchVehiclesFlown: ['Long March 2F'],
    launchSites: ['Jiuquan Satellite Launch Center'],
    spacewalks: { count: 0, totalTime: null },
    missions: [
      {
        name: 'Shenzhou 9',
        launchDate: '2012-06-16',
        spacecraft: 'Shenzhou',
        launchVehicle: 'Long March 2F',
        launchSite: 'Jiuquan Satellite Launch Center',
        role: 'Mission Specialist',
        duration: '12 days 15 hours',
        note: 'First Chinese woman in space.',
      },
      {
        name: 'Shenzhou 14',
        launchDate: '2022-06-05',
        spacecraft: 'Shenzhou',
        launchVehicle: 'Long March 2F',
        launchSite: 'Jiuquan Satellite Launch Center',
        role: 'Mission Specialist',
        duration: '183 days',
      },
    ],
  },
  {
    id: 'wang-yaping',
    name: 'Wang Yaping',
    agency: 'CNSA',
    agencyLinkId: 'cnsa',
    nationality: 'China',
    status: 'ACTIVE',
    selectionYear: 2010,
    spacecraftFlown: ['Shenzhou'],
    launchVehiclesFlown: ['Long March 2F'],
    launchSites: ['Jiuquan Satellite Launch Center'],
    spacewalks: { count: 1, totalTime: '6 hours 25 minutes' },
    missions: [
      {
        name: 'Shenzhou 10',
        launchDate: '2013-06-11',
        spacecraft: 'Shenzhou',
        launchVehicle: 'Long March 2F',
        launchSite: 'Jiuquan Satellite Launch Center',
        role: 'Mission Specialist',
        duration: '14 days 14 hours',
      },
      {
        name: 'Shenzhou 13',
        launchDate: '2021-10-15',
        spacecraft: 'Shenzhou',
        launchVehicle: 'Long March 2F',
        launchSite: 'Jiuquan Satellite Launch Center',
        role: 'Mission Specialist',
        duration: '183 days',
        note: 'First Chinese woman to perform a spacewalk.',
      },
    ],
  },
  {
    id: 'koichi-wakata',
    name: 'Koichi Wakata',
    agency: 'JAXA',
    agencyLinkId: 'jaxa',
    nationality: 'Japan',
    status: 'RETIRED',
    selectionYear: 1992,
    spacecraftFlown: ['Space Shuttle', 'Soyuz', 'Crew Dragon'],
    launchVehiclesFlown: ['Space Shuttle', 'Soyuz', 'Falcon 9'],
    launchSites: ['Kennedy Space Center', 'Baikonur Cosmodrome'],
    spacewalks: { count: 0, totalTime: null },
    missions: [
      {
        name: 'STS-72',
        launchDate: '1996-01-11',
        spacecraft: 'Space Shuttle Endeavour',
        launchVehicle: 'Space Shuttle',
        launchSite: 'Kennedy Space Center',
        role: 'Mission Specialist',
        duration: '8 days 22 hours',
      },
      {
        name: 'STS-92',
        launchDate: '2000-10-11',
        spacecraft: 'Space Shuttle Discovery',
        launchVehicle: 'Space Shuttle',
        launchSite: 'Kennedy Space Center',
        role: 'Mission Specialist',
        duration: '12 days 21 hours',
      },
      {
        name: 'Soyuz TMA-13 / Expedition 18/19/20',
        launchDate: '2009-03-26',
        spacecraft: 'Soyuz',
        launchVehicle: 'Soyuz',
        launchSite: 'Baikonur Cosmodrome',
        role: 'Flight Engineer',
        duration: '137 days',
      },
      {
        name: 'Soyuz TMA-11M / Expedition 38/39',
        launchDate: '2013-11-07',
        spacecraft: 'Soyuz',
        launchVehicle: 'Soyuz',
        launchSite: 'Baikonur Cosmodrome',
        role: 'ISS Commander (Expedition 39)',
        duration: '188 days',
        note: 'First Japanese ISS commander.',
      },
      {
        name: 'Crew-5 / Expedition 68/69',
        launchDate: '2022-10-05',
        spacecraft: 'Crew Dragon',
        launchVehicle: 'Falcon 9',
        launchSite: 'Kennedy Space Center',
        role: 'Flight Engineer',
        duration: '157 days',
      },
    ],
  },
  {
    id: 'naoko-yamazaki',
    name: 'Naoko Yamazaki',
    agency: 'JAXA',
    agencyLinkId: 'jaxa',
    nationality: 'Japan',
    status: 'RETIRED',
    selectionYear: 1999,
    spacecraftFlown: ['Space Shuttle'],
    launchVehiclesFlown: ['Space Shuttle'],
    launchSites: ['Kennedy Space Center'],
    spacewalks: { count: 0, totalTime: null },
    missions: [
      {
        name: 'STS-131',
        launchDate: '2010-04-05',
        spacecraft: 'Space Shuttle Discovery',
        launchVehicle: 'Space Shuttle',
        launchSite: 'Kennedy Space Center',
        role: 'Mission Specialist',
        duration: '15 days 2 hours',
        note: 'Second Japanese woman in space.',
      },
    ],
  },
  {
    id: 'chris-hadfield',
    name: 'Chris Hadfield',
    agency: 'Canadian Space Agency',
    agencyLinkId: 'csa',
    nationality: 'Canada',
    status: 'RETIRED',
    selectionYear: 1992,
    spacecraftFlown: ['Space Shuttle', 'Soyuz'],
    launchVehiclesFlown: ['Space Shuttle', 'Soyuz'],
    launchSites: ['Kennedy Space Center', 'Baikonur Cosmodrome'],
    spacewalks: { count: 2, totalTime: '14 hours 54 minutes' },
    missions: [
      {
        name: 'STS-74',
        launchDate: '1995-11-12',
        spacecraft: 'Space Shuttle Atlantis',
        launchVehicle: 'Space Shuttle',
        launchSite: 'Kennedy Space Center',
        role: 'Mission Specialist',
        duration: '8 days 4 hours',
        note: 'First Canadian to visit Mir.',
      },
      {
        name: 'STS-100',
        launchDate: '2001-04-19',
        spacecraft: 'Space Shuttle Endeavour',
        launchVehicle: 'Space Shuttle',
        launchSite: 'Kennedy Space Center',
        role: 'Mission Specialist',
        duration: '11 days 21 hours',
        note: 'First Canadian to perform a spacewalk.',
      },
      {
        name: 'Soyuz TMA-07M / Expedition 34/35',
        launchDate: '2012-12-19',
        spacecraft: 'Soyuz',
        launchVehicle: 'Soyuz',
        launchSite: 'Baikonur Cosmodrome',
        role: 'ISS Commander (Expedition 35)',
        duration: '146 days',
        note: 'First Canadian to command the ISS.',
      },
    ],
  },
  {
    id: 'roberta-bondar',
    name: 'Roberta Bondar',
    agency: 'Canadian Space Agency',
    agencyLinkId: 'csa',
    nationality: 'Canada',
    status: 'RETIRED',
    selectionYear: 1983,
    spacecraftFlown: ['Space Shuttle'],
    launchVehiclesFlown: ['Space Shuttle'],
    launchSites: ['Kennedy Space Center'],
    spacewalks: { count: 0, totalTime: null },
    missions: [
      {
        name: 'STS-42',
        launchDate: '1992-01-22',
        spacecraft: 'Space Shuttle Discovery',
        launchVehicle: 'Space Shuttle',
        launchSite: 'Kennedy Space Center',
        role: 'Payload Specialist',
        duration: '8 days 1 hour',
        note: 'First Canadian woman in space.',
      },
    ],
  },

  // ---- Additional NASA astronauts (Space Shuttle era to present ISS crews) ----
  {
    id: 'mae-jemison',
    name: 'Mae Jemison',
    agency: 'NASA',
    agencyLinkId: 'nasa',
    nationality: 'United States',
    status: 'RETIRED',
    selectionYear: 1987,
    spacecraftFlown: ['Space Shuttle'],
    launchVehiclesFlown: ['Space Shuttle'],
    launchSites: ['Kennedy Space Center'],
    spacewalks: { count: 0, totalTime: null },
    missions: [
      {
        name: 'STS-47',
        launchDate: '1992-09-12',
        spacecraft: 'Space Shuttle Endeavour',
        launchVehicle: 'Space Shuttle',
        launchSite: 'Kennedy Space Center',
        role: 'Mission Specialist',
        duration: '7 days 22 hours',
        note: 'First African-American woman in space.',
      },
    ],
  },
  {
    id: 'guion-bluford',
    name: 'Guion Bluford',
    agency: 'NASA',
    agencyLinkId: 'nasa',
    nationality: 'United States',
    status: 'RETIRED',
    selectionYear: 1978,
    spacecraftFlown: ['Space Shuttle'],
    launchVehiclesFlown: ['Space Shuttle'],
    launchSites: ['Kennedy Space Center'],
    spacewalks: { count: 0, totalTime: null },
    missions: [
      {
        name: 'STS-8',
        launchDate: '1983-08-30',
        spacecraft: 'Space Shuttle Challenger',
        launchVehicle: 'Space Shuttle',
        launchSite: 'Kennedy Space Center',
        role: 'Mission Specialist',
        duration: '6 days 1 hour',
        note: 'First African-American in space.',
      },
    ],
  },
  {
    id: 'eileen-collins',
    name: 'Eileen Collins',
    agency: 'NASA',
    agencyLinkId: 'nasa',
    nationality: 'United States',
    status: 'RETIRED',
    selectionYear: 1990,
    spacecraftFlown: ['Space Shuttle'],
    launchVehiclesFlown: ['Space Shuttle'],
    launchSites: ['Kennedy Space Center'],
    spacewalks: { count: 0, totalTime: null },
    missions: [
      {
        name: 'STS-63',
        launchDate: '1995-02-03',
        spacecraft: 'Space Shuttle Discovery',
        launchVehicle: 'Space Shuttle',
        launchSite: 'Kennedy Space Center',
        role: 'Pilot',
        duration: null,
        note: 'First woman to pilot a Space Shuttle.',
      },
      {
        name: 'STS-93',
        launchDate: '1999-07-23',
        spacecraft: 'Space Shuttle Columbia',
        launchVehicle: 'Space Shuttle',
        launchSite: 'Kennedy Space Center',
        role: 'Commander',
        duration: null,
        note: 'First woman to command a Space Shuttle mission.',
      },
    ],
  },
  {
    id: 'shannon-lucid',
    name: 'Shannon Lucid',
    agency: 'NASA',
    agencyLinkId: 'nasa',
    nationality: 'United States',
    status: 'RETIRED',
    selectionYear: 1978,
    spacecraftFlown: ['Space Shuttle', 'Soyuz'],
    launchVehiclesFlown: ['Space Shuttle', 'Soyuz'],
    launchSites: ['Kennedy Space Center', 'Baikonur Cosmodrome'],
    spacewalks: { count: 0, totalTime: null },
    missions: [
      {
        name: 'STS-76 / Mir',
        launchDate: '1996-03-22',
        spacecraft: 'Space Shuttle Atlantis / Mir',
        launchVehicle: 'Space Shuttle',
        launchSite: 'Kennedy Space Center',
        role: 'Mission Specialist',
        duration: '188 days',
        note: 'Longest single spaceflight by a woman at the time.',
      },
    ],
  },
  {
    id: 'jim-lovell',
    name: 'Jim Lovell',
    agency: 'NASA',
    agencyLinkId: 'nasa',
    nationality: 'United States',
    status: 'RETIRED',
    selectionYear: 1962,
    spacecraftFlown: ['Gemini', 'Apollo Command/Service Module'],
    launchVehiclesFlown: ['Titan II GLV', 'Saturn V'],
    launchSites: ['Cape Canaveral', 'Kennedy Space Center'],
    spacewalks: { count: 0, totalTime: null },
    missions: [
      {
        name: 'Gemini 7',
        launchDate: '1965-12-04',
        spacecraft: 'Gemini',
        launchVehicle: 'Titan II GLV',
        launchSite: 'Cape Canaveral',
        role: 'Pilot',
        duration: '13 days 18 hours',
      },
      {
        name: 'Gemini 12',
        launchDate: '1966-11-11',
        spacecraft: 'Gemini',
        launchVehicle: 'Titan II GLV',
        launchSite: 'Cape Canaveral',
        role: 'Command Pilot',
        duration: '3 days 22 hours',
      },
      {
        name: 'Apollo 8',
        launchDate: '1968-12-21',
        spacecraft: 'Apollo Command/Service Module',
        launchVehicle: 'Saturn V',
        launchSite: 'Kennedy Space Center',
        role: 'Command Module Pilot',
        duration: '6 days 3 hours',
        note: 'First crewed mission to orbit the Moon.',
      },
      {
        name: 'Apollo 13',
        launchDate: '1970-04-11',
        spacecraft: 'Apollo Command/Service Module',
        launchVehicle: 'Saturn V',
        launchSite: 'Kennedy Space Center',
        role: 'Commander',
        duration: '5 days 22 hours',
        note: 'Commanded the aborted lunar mission after an in-flight oxygen tank failure.',
      },
    ],
  },
  {
    id: 'alan-shepard',
    name: 'Alan Shepard',
    agency: 'NASA',
    agencyLinkId: 'nasa',
    nationality: 'United States',
    status: 'DECEASED',
    selectionYear: 1959,
    spacecraftFlown: ['Mercury', 'Apollo Command/Service Module & Lunar Module'],
    launchVehiclesFlown: ['Redstone', 'Saturn V'],
    launchSites: ['Cape Canaveral', 'Kennedy Space Center'],
    spacewalks: { count: 0, totalTime: null },
    missions: [
      {
        name: 'Mercury-Redstone 3 (Freedom 7)',
        launchDate: '1961-05-05',
        spacecraft: 'Mercury',
        launchVehicle: 'Redstone',
        launchSite: 'Cape Canaveral',
        role: 'Pilot',
        duration: '15 minutes',
        note: 'First American in space.',
      },
      {
        name: 'Apollo 14',
        launchDate: '1971-01-31',
        spacecraft: 'Apollo Command/Service Module & Lunar Module',
        launchVehicle: 'Saturn V',
        launchSite: 'Kennedy Space Center',
        role: 'Commander',
        duration: '9 days',
        note: 'Fifth person to walk on the Moon.',
      },
    ],
  },
  {
    id: 'gene-cernan',
    name: 'Gene Cernan',
    agency: 'NASA',
    agencyLinkId: 'nasa',
    nationality: 'United States',
    status: 'DECEASED',
    selectionYear: 1963,
    spacecraftFlown: ['Gemini', 'Apollo Command/Service Module & Lunar Module'],
    launchVehiclesFlown: ['Titan II GLV', 'Saturn V'],
    launchSites: ['Cape Canaveral', 'Kennedy Space Center'],
    spacewalks: { count: 3, totalTime: null },
    missions: [
      {
        name: 'Gemini 9A',
        launchDate: '1966-06-03',
        spacecraft: 'Gemini',
        launchVehicle: 'Titan II GLV',
        launchSite: 'Cape Canaveral',
        role: 'Pilot',
        duration: '3 days',
      },
      {
        name: 'Apollo 10',
        launchDate: '1969-05-18',
        spacecraft: 'Apollo Command/Service Module & Lunar Module',
        launchVehicle: 'Saturn V',
        launchSite: 'Kennedy Space Center',
        role: 'Lunar Module Pilot',
        duration: '8 days',
      },
      {
        name: 'Apollo 17',
        launchDate: '1972-12-07',
        spacecraft: 'Apollo Command/Service Module & Lunar Module',
        launchVehicle: 'Saturn V',
        launchSite: 'Kennedy Space Center',
        role: 'Commander',
        duration: '12 days 14 hours',
        note: 'Last person to walk on the Moon.',
      },
    ],
  },
  {
    id: 'bob-behnken',
    name: 'Bob Behnken',
    agency: 'NASA',
    agencyLinkId: 'nasa',
    nationality: 'United States',
    status: 'RETIRED',
    selectionYear: 2000,
    spacecraftFlown: ['Space Shuttle', 'Crew Dragon'],
    launchVehiclesFlown: ['Space Shuttle', 'Falcon 9'],
    launchSites: ['Kennedy Space Center'],
    spacewalks: { count: 6, totalTime: null },
    missions: [
      {
        name: 'STS-123',
        launchDate: '2008-03-11',
        spacecraft: 'Space Shuttle Endeavour',
        launchVehicle: 'Space Shuttle',
        launchSite: 'Kennedy Space Center',
        role: 'Mission Specialist',
        duration: null,
      },
      {
        name: 'STS-130',
        launchDate: '2010-02-08',
        spacecraft: 'Space Shuttle Endeavour',
        launchVehicle: 'Space Shuttle',
        launchSite: 'Kennedy Space Center',
        role: 'Mission Specialist',
        duration: null,
      },
      {
        name: 'Crew Dragon Demo-2',
        launchDate: '2020-05-30',
        spacecraft: 'Crew Dragon',
        launchVehicle: 'Falcon 9',
        launchSite: 'Kennedy Space Center',
        role: 'Joint Operations Commander',
        duration: '64 days',
        note: 'First crewed flight of Crew Dragon.',
      },
    ],
  },
  {
    id: 'doug-hurley',
    name: 'Doug Hurley',
    agency: 'NASA',
    agencyLinkId: 'nasa',
    nationality: 'United States',
    status: 'RETIRED',
    selectionYear: 2000,
    spacecraftFlown: ['Space Shuttle', 'Crew Dragon'],
    launchVehiclesFlown: ['Space Shuttle', 'Falcon 9'],
    launchSites: ['Kennedy Space Center'],
    spacewalks: { count: 0, totalTime: null },
    missions: [
      {
        name: 'STS-127',
        launchDate: '2009-07-15',
        spacecraft: 'Space Shuttle Endeavour',
        launchVehicle: 'Space Shuttle',
        launchSite: 'Kennedy Space Center',
        role: 'Pilot',
        duration: null,
      },
      {
        name: 'STS-135',
        launchDate: '2011-07-08',
        spacecraft: 'Space Shuttle Atlantis',
        launchVehicle: 'Space Shuttle',
        launchSite: 'Kennedy Space Center',
        role: 'Pilot',
        duration: null,
        note: 'Final flight of the Space Shuttle program.',
      },
      {
        name: 'Crew Dragon Demo-2',
        launchDate: '2020-05-30',
        spacecraft: 'Crew Dragon',
        launchVehicle: 'Falcon 9',
        launchSite: 'Kennedy Space Center',
        role: 'Spacecraft Commander',
        duration: '64 days',
        note: 'First crewed flight of Crew Dragon.',
      },
    ],
  },
  {
    id: 'victor-glover',
    name: 'Victor Glover',
    agency: 'NASA',
    agencyLinkId: 'nasa',
    nationality: 'United States',
    status: 'ACTIVE',
    selectionYear: 2013,
    spacecraftFlown: ['Crew Dragon'],
    launchVehiclesFlown: ['Falcon 9'],
    launchSites: ['Kennedy Space Center'],
    spacewalks: { count: 4, totalTime: null },
    missions: [
      {
        name: 'Crew-1 / Expedition 64/65',
        launchDate: '2020-11-16',
        spacecraft: 'Crew Dragon',
        launchVehicle: 'Falcon 9',
        launchSite: 'Kennedy Space Center',
        role: 'Pilot',
        duration: '168 days',
      },
    ],
  },
  {
    id: 'jasmin-moghbeli',
    name: 'Jasmin Moghbeli',
    agency: 'NASA',
    agencyLinkId: 'nasa',
    nationality: 'United States',
    status: 'ACTIVE',
    selectionYear: 2017,
    spacecraftFlown: ['Crew Dragon'],
    launchVehiclesFlown: ['Falcon 9'],
    launchSites: ['Kennedy Space Center'],
    spacewalks: { count: 1, totalTime: null },
    missions: [
      {
        name: 'Crew-7 / Expedition 69/70',
        launchDate: '2023-08-26',
        spacecraft: 'Crew Dragon',
        launchVehicle: 'Falcon 9',
        launchSite: 'Kennedy Space Center',
        role: 'ISS Commander (Expedition 70)',
        duration: '199 days',
      },
    ],
  },
  {
    id: 'frank-rubio',
    name: 'Frank Rubio',
    agency: 'NASA',
    agencyLinkId: 'nasa',
    nationality: 'United States',
    status: 'ACTIVE',
    selectionYear: 2017,
    spacecraftFlown: ['Soyuz'],
    launchVehiclesFlown: ['Soyuz'],
    launchSites: ['Baikonur Cosmodrome'],
    spacewalks: { count: 1, totalTime: null },
    missions: [
      {
        name: 'Soyuz MS-22 / Expedition 68/69',
        launchDate: '2022-09-21',
        spacecraft: 'Soyuz',
        launchVehicle: 'Soyuz',
        launchSite: 'Baikonur Cosmodrome',
        role: 'Flight Engineer',
        duration: '371 days',
        note: 'Longest single spaceflight by a NASA astronaut, extended after his Soyuz was damaged.',
      },
    ],
  },
  {
    id: 'nick-hague',
    name: 'Nick Hague',
    agency: 'NASA',
    agencyLinkId: 'nasa',
    nationality: 'United States',
    status: 'ACTIVE',
    selectionYear: 2013,
    spacecraftFlown: ['Soyuz', 'Crew Dragon'],
    launchVehiclesFlown: ['Soyuz', 'Falcon 9'],
    launchSites: ['Baikonur Cosmodrome', 'Kennedy Space Center'],
    spacewalks: { count: 3, totalTime: null },
    missions: [
      {
        name: 'Soyuz MS-10',
        launchDate: '2018-10-11',
        spacecraft: 'Soyuz',
        launchVehicle: 'Soyuz',
        launchSite: 'Baikonur Cosmodrome',
        role: 'Flight Engineer',
        duration: null,
        note: 'Mission aborted during ascent after a booster failure; crew survived via the launch escape system.',
      },
      {
        name: 'Soyuz MS-12 / Expedition 59/60',
        launchDate: '2019-03-14',
        spacecraft: 'Soyuz',
        launchVehicle: 'Soyuz',
        launchSite: 'Baikonur Cosmodrome',
        role: 'Flight Engineer',
        duration: '203 days',
      },
      {
        name: 'Crew-9 / Expedition 71/72',
        launchDate: '2024-09-28',
        spacecraft: 'Crew Dragon',
        launchVehicle: 'Falcon 9',
        launchSite: 'Kennedy Space Center',
        role: 'Spacecraft Commander',
        duration: null,
      },
    ],
  },
  {
    id: 'don-pettit',
    name: 'Don Pettit',
    agency: 'NASA',
    agencyLinkId: 'nasa',
    nationality: 'United States',
    status: 'ACTIVE',
    selectionYear: 1996,
    spacecraftFlown: ['Space Shuttle', 'Soyuz'],
    launchVehiclesFlown: ['Space Shuttle', 'Soyuz'],
    launchSites: ['Kennedy Space Center', 'Baikonur Cosmodrome'],
    spacewalks: { count: 2, totalTime: null },
    missions: [
      {
        name: 'Expedition 6',
        launchDate: '2002-11-23',
        spacecraft: 'Space Shuttle Endeavour / ISS',
        launchVehicle: 'Space Shuttle',
        launchSite: 'Kennedy Space Center',
        role: 'Flight Engineer',
        duration: null,
      },
      {
        name: 'Expedition 30/31',
        launchDate: '2011-12-21',
        spacecraft: 'Soyuz',
        launchVehicle: 'Soyuz',
        launchSite: 'Baikonur Cosmodrome',
        role: 'Flight Engineer',
        duration: null,
      },
      {
        name: 'Soyuz MS-26 / Expedition 71/72',
        launchDate: '2024-09-11',
        spacecraft: 'Soyuz',
        launchVehicle: 'Soyuz',
        launchSite: 'Baikonur Cosmodrome',
        role: 'Flight Engineer',
        duration: null,
      },
    ],
  },

  // ---- Additional Roscosmos / Soviet cosmonauts ----
  {
    id: 'valeri-polyakov',
    name: 'Valeri Polyakov',
    agency: 'Roscosmos',
    agencyLinkId: 'roscosmos',
    nationality: 'Russia',
    status: 'DECEASED',
    selectionYear: 1972,
    spacecraftFlown: ['Soyuz', 'Mir'],
    launchVehiclesFlown: ['Soyuz'],
    launchSites: ['Baikonur Cosmodrome'],
    spacewalks: { count: 0, totalTime: null },
    missions: [
      {
        name: 'Soyuz TM-6',
        launchDate: '1988-08-29',
        spacecraft: 'Soyuz',
        launchVehicle: 'Soyuz',
        launchSite: 'Baikonur Cosmodrome',
        role: 'Flight Engineer',
        duration: null,
      },
      {
        name: 'Soyuz TM-18',
        launchDate: '1994-01-08',
        spacecraft: 'Soyuz',
        launchVehicle: 'Soyuz',
        launchSite: 'Baikonur Cosmodrome',
        role: 'Flight Engineer',
        duration: '437 days 18 hours',
        note: 'Longest single spaceflight in history.',
      },
    ],
  },
  {
    id: 'sergei-krikalev',
    name: 'Sergei Krikalev',
    agency: 'Roscosmos',
    agencyLinkId: 'roscosmos',
    nationality: 'Russia',
    status: 'RETIRED',
    selectionYear: 1985,
    spacecraftFlown: ['Soyuz', 'Space Shuttle'],
    launchVehiclesFlown: ['Soyuz', 'Space Shuttle'],
    launchSites: ['Baikonur Cosmodrome', 'Kennedy Space Center'],
    spacewalks: { count: 8, totalTime: null },
    missions: [
      {
        name: 'Soyuz TM-7',
        launchDate: '1988-11-26',
        spacecraft: 'Soyuz',
        launchVehicle: 'Soyuz',
        launchSite: 'Baikonur Cosmodrome',
        role: 'Flight Engineer',
        duration: null,
      },
      {
        name: 'Soyuz TM-31 / Expedition 1',
        launchDate: '2000-10-31',
        spacecraft: 'Soyuz',
        launchVehicle: 'Soyuz',
        launchSite: 'Baikonur Cosmodrome',
        role: 'Flight Engineer',
        duration: null,
        note: 'Part of the first crew to occupy the ISS.',
      },
    ],
  },
  {
    id: 'gennady-padalka',
    name: 'Gennady Padalka',
    agency: 'Roscosmos',
    agencyLinkId: 'roscosmos',
    nationality: 'Russia',
    status: 'RETIRED',
    selectionYear: 1989,
    spacecraftFlown: ['Soyuz'],
    launchVehiclesFlown: ['Soyuz'],
    launchSites: ['Baikonur Cosmodrome'],
    spacewalks: { count: 10, totalTime: null },
    missions: [
      {
        name: 'Soyuz TM-28',
        launchDate: '1998-08-13',
        spacecraft: 'Soyuz',
        launchVehicle: 'Soyuz',
        launchSite: 'Baikonur Cosmodrome',
        role: 'Commander',
        duration: null,
      },
      {
        name: 'Soyuz TMA-16M / Expedition 43/44',
        launchDate: '2015-03-27',
        spacecraft: 'Soyuz',
        launchVehicle: 'Soyuz',
        launchSite: 'Baikonur Cosmodrome',
        role: 'ISS Commander',
        duration: null,
        note: 'Holds the record for most cumulative time in space by any human.',
      },
    ],
  },
  {
    id: 'oleg-kononenko',
    name: 'Oleg Kononenko',
    agency: 'Roscosmos',
    agencyLinkId: 'roscosmos',
    nationality: 'Russia',
    status: 'ACTIVE',
    selectionYear: 1996,
    spacecraftFlown: ['Soyuz'],
    launchVehiclesFlown: ['Soyuz'],
    launchSites: ['Baikonur Cosmodrome'],
    spacewalks: { count: 8, totalTime: null },
    missions: [
      {
        name: 'Soyuz TMA-12',
        launchDate: '2008-04-08',
        spacecraft: 'Soyuz',
        launchVehicle: 'Soyuz',
        launchSite: 'Baikonur Cosmodrome',
        role: 'Flight Engineer',
        duration: null,
      },
      {
        name: 'Soyuz MS-24 / Expedition 70/71',
        launchDate: '2023-09-15',
        spacecraft: 'Soyuz',
        launchVehicle: 'Soyuz',
        launchSite: 'Baikonur Cosmodrome',
        role: 'ISS Commander',
        duration: '374 days',
        note: 'Surpassed Gennady Padalka to become the person with the most cumulative time in space.',
      },
    ],
  },
  {
    id: 'elena-serova',
    name: 'Elena Serova',
    agency: 'Roscosmos',
    agencyLinkId: 'roscosmos',
    nationality: 'Russia',
    status: 'RETIRED',
    selectionYear: 2006,
    spacecraftFlown: ['Soyuz'],
    launchVehiclesFlown: ['Soyuz'],
    launchSites: ['Baikonur Cosmodrome'],
    spacewalks: { count: 0, totalTime: null },
    missions: [
      {
        name: 'Soyuz TMA-14M / Expedition 41/42',
        launchDate: '2014-09-25',
        spacecraft: 'Soyuz',
        launchVehicle: 'Soyuz',
        launchSite: 'Baikonur Cosmodrome',
        role: 'Flight Engineer',
        duration: '167 days',
        note: 'First Russian woman to visit the ISS.',
      },
    ],
  },
  {
    id: 'anna-kikina',
    name: 'Anna Kikina',
    agency: 'Roscosmos',
    agencyLinkId: 'roscosmos',
    nationality: 'Russia',
    status: 'ACTIVE',
    selectionYear: 2012,
    spacecraftFlown: ['Crew Dragon'],
    launchVehiclesFlown: ['Falcon 9'],
    launchSites: ['Kennedy Space Center'],
    spacewalks: { count: 0, totalTime: null },
    missions: [
      {
        name: 'Crew-5 / Expedition 68/69',
        launchDate: '2022-10-05',
        spacecraft: 'Crew Dragon',
        launchVehicle: 'Falcon 9',
        launchSite: 'Kennedy Space Center',
        role: 'Mission Specialist',
        duration: '157 days',
        note: 'First Russian cosmonaut to fly on a Crew Dragon.',
      },
    ],
  },

  // ---- Additional ESA astronauts ----
  {
    id: 'luca-parmitano',
    name: 'Luca Parmitano',
    agency: 'European Space Agency',
    agencyLinkId: 'esa',
    nationality: 'Italy',
    status: 'ACTIVE',
    selectionYear: 2009,
    spacecraftFlown: ['Soyuz'],
    launchVehiclesFlown: ['Soyuz'],
    launchSites: ['Baikonur Cosmodrome'],
    spacewalks: { count: 4, totalTime: null },
    missions: [
      {
        name: 'Soyuz TMA-09M / Expedition 36/37',
        launchDate: '2013-05-28',
        spacecraft: 'Soyuz',
        launchVehicle: 'Soyuz',
        launchSite: 'Baikonur Cosmodrome',
        role: 'Flight Engineer',
        duration: null,
      },
      {
        name: 'Soyuz MS-13 / Expedition 60/61',
        launchDate: '2019-07-20',
        spacecraft: 'Soyuz',
        launchVehicle: 'Soyuz',
        launchSite: 'Baikonur Cosmodrome',
        role: 'ISS Commander (Expedition 61)',
        duration: null,
        note: 'First Italian to command the ISS.',
      },
    ],
  },
  {
    id: 'alexander-gerst',
    name: 'Alexander Gerst',
    agency: 'European Space Agency',
    agencyLinkId: 'esa',
    nationality: 'Germany',
    status: 'ACTIVE',
    selectionYear: 2009,
    spacecraftFlown: ['Soyuz'],
    launchVehiclesFlown: ['Soyuz'],
    launchSites: ['Baikonur Cosmodrome'],
    spacewalks: { count: 0, totalTime: null },
    missions: [
      {
        name: 'Soyuz TMA-13M / Expedition 40/41',
        launchDate: '2014-05-28',
        spacecraft: 'Soyuz',
        launchVehicle: 'Soyuz',
        launchSite: 'Baikonur Cosmodrome',
        role: 'Flight Engineer',
        duration: null,
      },
      {
        name: 'Soyuz MS-09 / Expedition 56/57',
        launchDate: '2018-06-06',
        spacecraft: 'Soyuz',
        launchVehicle: 'Soyuz',
        launchSite: 'Baikonur Cosmodrome',
        role: 'ISS Commander (Expedition 57)',
        duration: null,
        note: 'First German to command the ISS.',
      },
    ],
  },
  {
    id: 'matthias-maurer',
    name: 'Matthias Maurer',
    agency: 'European Space Agency',
    agencyLinkId: 'esa',
    nationality: 'Germany',
    status: 'ACTIVE',
    selectionYear: 2015,
    spacecraftFlown: ['Crew Dragon'],
    launchVehiclesFlown: ['Falcon 9'],
    launchSites: ['Kennedy Space Center'],
    spacewalks: { count: 1, totalTime: null },
    missions: [
      {
        name: 'Crew-3 / Expedition 66/67',
        launchDate: '2021-11-11',
        spacecraft: 'Crew Dragon',
        launchVehicle: 'Falcon 9',
        launchSite: 'Kennedy Space Center',
        role: 'Mission Specialist',
        duration: '177 days',
      },
    ],
  },
  {
    id: 'andreas-mogensen',
    name: 'Andreas Mogensen',
    agency: 'European Space Agency',
    agencyLinkId: 'esa',
    nationality: 'Denmark',
    status: 'ACTIVE',
    selectionYear: 2009,
    spacecraftFlown: ['Soyuz', 'Crew Dragon'],
    launchVehiclesFlown: ['Soyuz', 'Falcon 9'],
    launchSites: ['Baikonur Cosmodrome', 'Kennedy Space Center'],
    spacewalks: { count: 1, totalTime: null },
    missions: [
      {
        name: 'Soyuz TMA-18M',
        launchDate: '2015-09-02',
        spacecraft: 'Soyuz',
        launchVehicle: 'Soyuz',
        launchSite: 'Baikonur Cosmodrome',
        role: 'Flight Engineer',
        duration: null,
        note: 'First Danish astronaut in space.',
      },
      {
        name: 'Crew-7 / Expedition 69/70',
        launchDate: '2023-08-26',
        spacecraft: 'Crew Dragon',
        launchVehicle: 'Falcon 9',
        launchSite: 'Kennedy Space Center',
        role: 'ISS Commander (Expedition 70)',
        duration: '199 days',
      },
    ],
  },
  {
    id: 'paolo-nespoli',
    name: 'Paolo Nespoli',
    agency: 'European Space Agency',
    agencyLinkId: 'esa',
    nationality: 'Italy',
    status: 'RETIRED',
    selectionYear: 1998,
    spacecraftFlown: ['Space Shuttle', 'Soyuz'],
    launchVehiclesFlown: ['Space Shuttle', 'Soyuz'],
    launchSites: ['Kennedy Space Center', 'Baikonur Cosmodrome'],
    spacewalks: { count: 0, totalTime: null },
    missions: [
      {
        name: 'STS-120',
        launchDate: '2007-10-23',
        spacecraft: 'Space Shuttle Discovery',
        launchVehicle: 'Space Shuttle',
        launchSite: 'Kennedy Space Center',
        role: 'Mission Specialist',
        duration: null,
      },
      {
        name: 'Soyuz TMA-20 / Expedition 26/27',
        launchDate: '2010-12-15',
        spacecraft: 'Soyuz',
        launchVehicle: 'Soyuz',
        launchSite: 'Baikonur Cosmodrome',
        role: 'Flight Engineer',
        duration: null,
      },
      {
        name: 'Soyuz MS-05 / Expedition 52/53',
        launchDate: '2017-07-28',
        spacecraft: 'Soyuz',
        launchVehicle: 'Soyuz',
        launchSite: 'Baikonur Cosmodrome',
        role: 'Flight Engineer',
        duration: null,
      },
    ],
  },

  // ---- Additional JAXA astronauts ----
  {
    id: 'soichi-noguchi',
    name: 'Soichi Noguchi',
    agency: 'JAXA',
    agencyLinkId: 'jaxa',
    nationality: 'Japan',
    status: 'RETIRED',
    selectionYear: 1996,
    spacecraftFlown: ['Space Shuttle', 'Soyuz', 'Crew Dragon'],
    launchVehiclesFlown: ['Space Shuttle', 'Soyuz', 'Falcon 9'],
    launchSites: ['Kennedy Space Center', 'Baikonur Cosmodrome'],
    spacewalks: { count: 6, totalTime: null },
    missions: [
      {
        name: 'STS-114',
        launchDate: '2005-07-26',
        spacecraft: 'Space Shuttle Discovery',
        launchVehicle: 'Space Shuttle',
        launchSite: 'Kennedy Space Center',
        role: 'Mission Specialist',
        duration: null,
      },
      {
        name: 'Soyuz TMA-01M / Expedition 22/23',
        launchDate: '2009-12-20',
        spacecraft: 'Soyuz',
        launchVehicle: 'Soyuz',
        launchSite: 'Baikonur Cosmodrome',
        role: 'Flight Engineer',
        duration: null,
      },
      {
        name: 'Crew-1 / Expedition 64/65',
        launchDate: '2020-11-16',
        spacecraft: 'Crew Dragon',
        launchVehicle: 'Falcon 9',
        launchSite: 'Kennedy Space Center',
        role: 'Mission Specialist',
        duration: '168 days',
      },
    ],
  },
  {
    id: 'satoshi-furukawa',
    name: 'Satoshi Furukawa',
    agency: 'JAXA',
    agencyLinkId: 'jaxa',
    nationality: 'Japan',
    status: 'ACTIVE',
    selectionYear: 1999,
    spacecraftFlown: ['Soyuz', 'Crew Dragon'],
    launchVehiclesFlown: ['Soyuz', 'Falcon 9'],
    launchSites: ['Baikonur Cosmodrome', 'Kennedy Space Center'],
    spacewalks: { count: 0, totalTime: null },
    missions: [
      {
        name: 'Soyuz TMA-02M / Expedition 28/29',
        launchDate: '2011-06-08',
        spacecraft: 'Soyuz',
        launchVehicle: 'Soyuz',
        launchSite: 'Baikonur Cosmodrome',
        role: 'Flight Engineer',
        duration: null,
      },
      {
        name: 'Crew-7 / Expedition 69/70',
        launchDate: '2023-08-26',
        spacecraft: 'Crew Dragon',
        launchVehicle: 'Falcon 9',
        launchSite: 'Kennedy Space Center',
        role: 'Mission Specialist',
        duration: '199 days',
      },
    ],
  },
  {
    id: 'norishige-kanai',
    name: 'Norishige Kanai',
    agency: 'JAXA',
    agencyLinkId: 'jaxa',
    nationality: 'Japan',
    status: 'RETIRED',
    selectionYear: 2009,
    spacecraftFlown: ['Soyuz'],
    launchVehiclesFlown: ['Soyuz'],
    launchSites: ['Baikonur Cosmodrome'],
    spacewalks: { count: 0, totalTime: null },
    missions: [
      {
        name: 'Soyuz MS-07 / Expedition 54/55',
        launchDate: '2017-12-17',
        spacecraft: 'Soyuz',
        launchVehicle: 'Soyuz',
        launchSite: 'Baikonur Cosmodrome',
        role: 'Flight Engineer',
        duration: null,
      },
    ],
  },

  // ---- Additional CSA astronauts ----
  {
    id: 'marc-garneau',
    name: 'Marc Garneau',
    agency: 'Canadian Space Agency',
    agencyLinkId: 'csa',
    nationality: 'Canada',
    status: 'RETIRED',
    selectionYear: 1983,
    spacecraftFlown: ['Space Shuttle'],
    launchVehiclesFlown: ['Space Shuttle'],
    launchSites: ['Kennedy Space Center'],
    spacewalks: { count: 0, totalTime: null },
    missions: [
      {
        name: 'STS-41-G',
        launchDate: '1984-10-05',
        spacecraft: 'Space Shuttle Challenger',
        launchVehicle: 'Space Shuttle',
        launchSite: 'Kennedy Space Center',
        role: 'Payload Specialist',
        duration: null,
        note: 'First Canadian in space.',
      },
    ],
  },
  {
    id: 'julie-payette',
    name: 'Julie Payette',
    agency: 'Canadian Space Agency',
    agencyLinkId: 'csa',
    nationality: 'Canada',
    status: 'RETIRED',
    selectionYear: 1992,
    spacecraftFlown: ['Space Shuttle'],
    launchVehiclesFlown: ['Space Shuttle'],
    launchSites: ['Kennedy Space Center'],
    spacewalks: { count: 0, totalTime: null },
    missions: [
      {
        name: 'STS-96',
        launchDate: '1999-05-27',
        spacecraft: 'Space Shuttle Discovery',
        launchVehicle: 'Space Shuttle',
        launchSite: 'Kennedy Space Center',
        role: 'Mission Specialist',
        duration: null,
      },
      {
        name: 'STS-127',
        launchDate: '2009-07-15',
        spacecraft: 'Space Shuttle Endeavour',
        launchVehicle: 'Space Shuttle',
        launchSite: 'Kennedy Space Center',
        role: 'Mission Specialist',
        duration: null,
      },
    ],
  },
  {
    id: 'jeremy-hansen',
    name: 'Jeremy Hansen',
    agency: 'Canadian Space Agency',
    agencyLinkId: 'csa',
    nationality: 'Canada',
    status: 'ACTIVE',
    selectionYear: 2009,
    spacecraftFlown: ['Orion'],
    launchVehiclesFlown: [],
    launchSites: [],
    spacewalks: { count: 0, totalTime: null },
    missions: [
      {
        name: 'Artemis II',
        launchDate: null,
        spacecraft: 'Orion',
        launchVehicle: 'Space Launch System',
        launchSite: 'Kennedy Space Center',
        role: 'Mission Specialist',
        duration: null,
        note: 'Assigned to the crewed lunar flyby mission; first Canadian to fly beyond low Earth orbit.',
      },
    ],
  },

  // ---- Additional CNSA astronauts ----
  {
    id: 'zhai-zhigang',
    name: 'Zhai Zhigang',
    agency: 'CNSA',
    agencyLinkId: 'cnsa',
    nationality: 'China',
    status: 'ACTIVE',
    selectionYear: 1998,
    spacecraftFlown: ['Shenzhou'],
    launchVehiclesFlown: ['Long March 2F'],
    launchSites: ['Jiuquan Satellite Launch Center'],
    spacewalks: { count: 1, totalTime: null },
    missions: [
      {
        name: 'Shenzhou 7',
        launchDate: '2008-09-25',
        spacecraft: 'Shenzhou',
        launchVehicle: 'Long March 2F',
        launchSite: 'Jiuquan Satellite Launch Center',
        role: 'Commander',
        duration: null,
        note: 'Performed the first Chinese spacewalk.',
      },
      {
        name: 'Shenzhou 13',
        launchDate: '2021-10-15',
        spacecraft: 'Shenzhou',
        launchVehicle: 'Long March 2F',
        launchSite: 'Jiuquan Satellite Launch Center',
        role: 'Commander',
        duration: '183 days',
      },
    ],
  },
  {
    id: 'nie-haisheng',
    name: 'Nie Haisheng',
    agency: 'CNSA',
    agencyLinkId: 'cnsa',
    nationality: 'China',
    status: 'RETIRED',
    selectionYear: 1998,
    spacecraftFlown: ['Shenzhou'],
    launchVehiclesFlown: ['Long March 2F'],
    launchSites: ['Jiuquan Satellite Launch Center'],
    spacewalks: { count: 0, totalTime: null },
    missions: [
      {
        name: 'Shenzhou 6',
        launchDate: '2005-10-12',
        spacecraft: 'Shenzhou',
        launchVehicle: 'Long March 2F',
        launchSite: 'Jiuquan Satellite Launch Center',
        role: 'Mission Specialist',
        duration: null,
      },
      {
        name: 'Shenzhou 10',
        launchDate: '2013-06-11',
        spacecraft: 'Shenzhou',
        launchVehicle: 'Long March 2F',
        launchSite: 'Jiuquan Satellite Launch Center',
        role: 'Commander',
        duration: null,
      },
      {
        name: 'Shenzhou 12',
        launchDate: '2021-06-17',
        spacecraft: 'Shenzhou',
        launchVehicle: 'Long March 2F',
        launchSite: 'Jiuquan Satellite Launch Center',
        role: 'Commander',
        duration: '92 days',
        note: 'First crew to occupy the Tiangong space station.',
      },
    ],
  },
  {
    id: 'jing-haipeng',
    name: 'Jing Haipeng',
    agency: 'CNSA',
    agencyLinkId: 'cnsa',
    nationality: 'China',
    status: 'ACTIVE',
    selectionYear: 1998,
    spacecraftFlown: ['Shenzhou'],
    launchVehiclesFlown: ['Long March 2F'],
    launchSites: ['Jiuquan Satellite Launch Center'],
    spacewalks: { count: 0, totalTime: null },
    missions: [
      {
        name: 'Shenzhou 7',
        launchDate: '2008-09-25',
        spacecraft: 'Shenzhou',
        launchVehicle: 'Long March 2F',
        launchSite: 'Jiuquan Satellite Launch Center',
        role: 'Mission Specialist',
        duration: null,
      },
      {
        name: 'Shenzhou 9',
        launchDate: '2012-06-16',
        spacecraft: 'Shenzhou',
        launchVehicle: 'Long March 2F',
        launchSite: 'Jiuquan Satellite Launch Center',
        role: 'Commander',
        duration: null,
      },
      {
        name: 'Shenzhou 11',
        launchDate: '2016-10-17',
        spacecraft: 'Shenzhou',
        launchVehicle: 'Long March 2F',
        launchSite: 'Jiuquan Satellite Launch Center',
        role: 'Commander',
        duration: '33 days',
      },
    ],
  },

  // ---- India (Gaganyaan programme and Axiom Mission 4) ----
  {
    id: 'shubhanshu-shukla',
    name: 'Shubhanshu Shukla',
    agency: 'ISRO',
    agencyLinkId: null,
    nationality: 'India',
    status: 'ACTIVE',
    selectionYear: 2019,
    spacecraftFlown: ['Crew Dragon'],
    launchVehiclesFlown: ['Falcon 9'],
    launchSites: ['Kennedy Space Center'],
    spacewalks: { count: 0, totalTime: null },
    missions: [
      {
        name: 'Axiom Mission 4',
        launchDate: '2025-06-25',
        spacecraft: 'Crew Dragon',
        launchVehicle: 'Falcon 9',
        launchSite: 'Kennedy Space Center',
        role: 'Pilot',
        duration: null,
        note: 'Second Indian citizen in space, and the first to visit the ISS.',
      },
    ],
  },

];
