// Astronaut / spaceflight-crew dataset for SpaceTec's Astronaut Database.
//
// Every entry here is built from well-established, publicly documented
// spaceflight history (agency biographies, mission records). Fields that
// aren't reliably known for a given astronaut are simply omitted — the UI
// renders those as "DATA UNAVAILABLE" rather than guessing. Nothing here
// is fabricated.
//
// `agencyLinkId` matches an id in SpaceTecHub.js's AGENCIES list, so the
// astronaut profile can deep-link straight to that agency's existing card
// instead of duplicating agency info.

export const STATUS_VALUES = ['ACTIVE', 'RETIRED', 'DECEASED'];

export const ASTRONAUTS = [
  {
    id: 'yuri-gagarin',
    name: 'Yuri Gagarin',
    agency: 'Soviet Space Programme',
    agencyLinkId: 'roscosmos',
    nationality: 'Soviet Union',
    status: 'DECEASED',
    selectionYear: 1960,
    spacecraftFlown: ['Vostok'],
    launchVehiclesFlown: ['Vostok-K'],
    launchSites: ['Baikonur Cosmodrome'],
    spacewalks: { count: 0, totalTime: null },
    missions: [
      {
        name: 'Vostok 1',
        launchDate: '1961-04-12',
        spacecraft: 'Vostok',
        launchVehicle: 'Vostok-K',
        launchSite: 'Baikonur Cosmodrome',
        role: 'Pilot',
        duration: '1 hour 48 minutes',
        note: 'First human spaceflight in history.',
      },
    ],
  },
  {
    id: 'valentina-tereshkova',
    name: 'Valentina Tereshkova',
    agency: 'Soviet Space Programme',
    agencyLinkId: 'roscosmos',
    nationality: 'Soviet Union',
    status: 'RETIRED',
    selectionYear: 1962,
    spacecraftFlown: ['Vostok'],
    launchVehiclesFlown: ['Vostok-K'],
    launchSites: ['Baikonur Cosmodrome'],
    spacewalks: { count: 0, totalTime: null },
    missions: [
      {
        name: 'Vostok 6',
        launchDate: '1963-06-16',
        spacecraft: 'Vostok',
        launchVehicle: 'Vostok-K',
        launchSite: 'Baikonur Cosmodrome',
        role: 'Pilot',
        duration: '2 days 22 hours 50 minutes',
        note: 'First woman in space.',
      },
    ],
  },
  {
    id: 'alexei-leonov',
    name: 'Alexei Leonov',
    agency: 'Soviet Space Programme',
    agencyLinkId: 'roscosmos',
    nationality: 'Soviet Union',
    status: 'DECEASED',
    selectionYear: 1960,
    spacecraftFlown: ['Voskhod', 'Soyuz'],
    launchVehiclesFlown: ['Voskhod', 'Soyuz'],
    launchSites: ['Baikonur Cosmodrome'],
    spacewalks: { count: 1, totalTime: '12 minutes 9 seconds' },
    missions: [
      {
        name: 'Voskhod 2',
        launchDate: '1965-03-18',
        spacecraft: 'Voskhod',
        launchVehicle: 'Voskhod',
        launchSite: 'Baikonur Cosmodrome',
        role: 'Pilot',
        duration: '1 day 2 hours',
        note: 'Performed the first spacewalk in history.',
      },
      {
        name: 'Soyuz 19 (Apollo–Soyuz Test Project)',
        launchDate: '1975-07-15',
        spacecraft: 'Soyuz',
        launchVehicle: 'Soyuz',
        launchSite: 'Baikonur Cosmodrome',
        role: 'Commander',
        duration: '5 days 22 hours 30 minutes',
      },
    ],
  },
  {
    id: 'neil-armstrong',
    name: 'Neil Armstrong',
    agency: 'NASA',
    agencyLinkId: 'nasa',
    nationality: 'United States',
    status: 'DECEASED',
    selectionYear: 1962,
    spacecraftFlown: ['Gemini', 'Apollo Command/Service Module', 'Apollo Lunar Module'],
    launchVehiclesFlown: ['Titan II GLV', 'Saturn V'],
    launchSites: ['Cape Canaveral', 'Kennedy Space Center'],
    spacewalks: { count: 1, totalTime: '2 hours 31 minutes' },
    missions: [
      {
        name: 'Gemini 8',
        launchDate: '1966-03-16',
        spacecraft: 'Gemini',
        launchVehicle: 'Titan II GLV',
        launchSite: 'Cape Canaveral',
        role: 'Command Pilot',
        duration: '10 hours 41 minutes',
        note: 'First docking of two spacecraft in orbit.',
      },
      {
        name: 'Apollo 11',
        launchDate: '1969-07-16',
        spacecraft: 'Apollo Command/Service Module & Lunar Module',
        launchVehicle: 'Saturn V',
        launchSite: 'Kennedy Space Center',
        role: 'Commander',
        duration: '8 days 3 hours 18 minutes',
        note: 'First crewed lunar landing; first person to walk on the Moon.',
      },
    ],
  },
  {
    id: 'buzz-aldrin',
    name: 'Buzz Aldrin',
    agency: 'NASA',
    agencyLinkId: 'nasa',
    nationality: 'United States',
    status: 'RETIRED',
    selectionYear: 1963,
    spacecraftFlown: ['Gemini', 'Apollo Command/Service Module', 'Apollo Lunar Module'],
    launchVehiclesFlown: ['Titan II GLV', 'Saturn V'],
    launchSites: ['Cape Canaveral', 'Kennedy Space Center'],
    spacewalks: { count: 4, totalTime: '7 hours 52 minutes' },
    missions: [
      {
        name: 'Gemini 12',
        launchDate: '1966-11-11',
        spacecraft: 'Gemini',
        launchVehicle: 'Titan II GLV',
        launchSite: 'Cape Canaveral',
        role: 'Pilot',
        duration: '3 days 22 hours 34 minutes',
      },
      {
        name: 'Apollo 11',
        launchDate: '1969-07-16',
        spacecraft: 'Apollo Command/Service Module & Lunar Module',
        launchVehicle: 'Saturn V',
        launchSite: 'Kennedy Space Center',
        role: 'Lunar Module Pilot',
        duration: '8 days 3 hours 18 minutes',
        note: 'Second person to walk on the Moon.',
      },
    ],
  },
  {
    id: 'michael-collins',
    name: 'Michael Collins',
    agency: 'NASA',
    agencyLinkId: 'nasa',
    nationality: 'United States',
    status: 'DECEASED',
    selectionYear: 1963,
    spacecraftFlown: ['Gemini', 'Apollo Command/Service Module'],
    launchVehiclesFlown: ['Titan II GLV', 'Saturn V'],
    launchSites: ['Cape Canaveral', 'Kennedy Space Center'],
    spacewalks: { count: 1, totalTime: '39 minutes' },
    missions: [
      {
        name: 'Gemini 10',
        launchDate: '1966-07-18',
        spacecraft: 'Gemini',
        launchVehicle: 'Titan II GLV',
        launchSite: 'Cape Canaveral',
        role: 'Pilot',
        duration: '2 days 22 hours 47 minutes',
      },
      {
        name: 'Apollo 11',
        launchDate: '1969-07-16',
        spacecraft: 'Apollo Command/Service Module',
        launchVehicle: 'Saturn V',
        launchSite: 'Kennedy Space Center',
        role: 'Command Module Pilot',
        duration: '8 days 3 hours 18 minutes',
        note: 'Piloted the Command Module in lunar orbit during the Apollo 11 landing.',
      },
    ],
  },
  {
    id: 'john-glenn',
    name: 'John Glenn',
    agency: 'NASA',
    agencyLinkId: 'nasa',
    nationality: 'United States',
    status: 'DECEASED',
    selectionYear: 1959,
    spacecraftFlown: ['Mercury', 'Space Shuttle'],
    launchVehiclesFlown: ['Atlas LV-3B', 'Space Shuttle'],
    launchSites: ['Cape Canaveral', 'Kennedy Space Center'],
    spacewalks: { count: 0, totalTime: null },
    missions: [
      {
        name: 'Mercury-Atlas 6 (Friendship 7)',
        launchDate: '1962-02-20',
        spacecraft: 'Mercury',
        launchVehicle: 'Atlas LV-3B',
        launchSite: 'Cape Canaveral',
        role: 'Pilot',
        duration: '4 hours 55 minutes',
        note: 'First American to orbit the Earth.',
      },
      {
        name: 'STS-95',
        launchDate: '1998-10-29',
        spacecraft: 'Space Shuttle Discovery',
        launchVehicle: 'Space Shuttle',
        launchSite: 'Kennedy Space Center',
        role: 'Payload Specialist',
        duration: '8 days 21 hours 44 minutes',
        note: 'At 77, became the oldest person to fly in space at the time.',
      },
    ],
  },
  {
    id: 'sally-ride',
    name: 'Sally Ride',
    agency: 'NASA',
    agencyLinkId: 'nasa',
    nationality: 'United States',
    status: 'DECEASED',
    selectionYear: 1978,
    spacecraftFlown: ['Space Shuttle'],
    launchVehiclesFlown: ['Space Shuttle'],
    launchSites: ['Kennedy Space Center'],
    spacewalks: { count: 0, totalTime: null },
    missions: [
      {
        name: 'STS-7',
        launchDate: '1983-06-18',
        spacecraft: 'Space Shuttle Challenger',
        launchVehicle: 'Space Shuttle',
        launchSite: 'Kennedy Space Center',
        role: 'Mission Specialist',
        duration: '6 days 2 hours 24 minutes',
        note: 'First American woman in space.',
      },
      {
        name: 'STS-41-G',
        launchDate: '1984-10-05',
        spacecraft: 'Space Shuttle Challenger',
        launchVehicle: 'Space Shuttle',
        launchSite: 'Kennedy Space Center',
        role: 'Mission Specialist',
        duration: '8 days 5 hours 24 minutes',
      },
    ],
  },
  {
    id: 'sunita-williams',
    name: 'Sunita Williams',
    agency: 'NASA',
    agencyLinkId: 'nasa',
    nationality: 'United States',
    status: 'ACTIVE',
    selectionYear: 1998,
    spacecraftFlown: ['Space Shuttle', 'Soyuz', 'Boeing Starliner'],
    launchVehiclesFlown: ['Space Shuttle', 'Soyuz', 'Atlas V'],
    launchSites: ['Kennedy Space Center', 'Baikonur Cosmodrome', 'Cape Canaveral'],
    spacewalks: { count: 9, totalTime: '62 hours 6 minutes' },
    missions: [
      {
        name: 'STS-116 / Expedition 14/15',
        launchDate: '2006-12-09',
        spacecraft: 'Space Shuttle Discovery / ISS',
        launchVehicle: 'Space Shuttle',
        launchSite: 'Kennedy Space Center',
        role: 'Flight Engineer',
        duration: '195 days 18 hours',
      },
      {
        name: 'Soyuz TMA-05M / Expedition 32/33',
        launchDate: '2012-07-15',
        spacecraft: 'Soyuz',
        launchVehicle: 'Soyuz',
        launchSite: 'Baikonur Cosmodrome',
        role: 'ISS Commander (Expedition 33)',
        duration: '127 days',
      },
      {
        name: 'Boeing Crewed Flight Test / Expedition 71/72',
        launchDate: '2024-06-05',
        spacecraft: 'Boeing Starliner',
        launchVehicle: 'Atlas V',
        launchSite: 'Cape Canaveral',
        role: 'Pilot',
        duration: null,
        note: 'Extended ISS stay after Starliner returned uncrewed; came home on a Crew Dragon.',
      },
    ],
  },
  {
    id: 'peggy-whitson',
    name: 'Peggy Whitson',
    agency: 'NASA',
    agencyLinkId: 'nasa',
    nationality: 'United States',
    status: 'ACTIVE',
    selectionYear: 1996,
    spacecraftFlown: ['Space Shuttle', 'Soyuz', 'Crew Dragon'],
    launchVehiclesFlown: ['Space Shuttle', 'Soyuz', 'Falcon 9'],
    launchSites: ['Kennedy Space Center', 'Baikonur Cosmodrome'],
    spacewalks: { count: 10, totalTime: '60 hours 21 minutes' },
    missions: [
      {
        name: 'STS-111 / Expedition 5',
        launchDate: '2002-06-05',
        spacecraft: 'Space Shuttle Endeavour / ISS',
        launchVehicle: 'Space Shuttle',
        launchSite: 'Kennedy Space Center',
        role: 'Flight Engineer',
        duration: '184 days',
      },
      {
        name: 'Soyuz TMA-11 / Expedition 16',
        launchDate: '2007-10-10',
        spacecraft: 'Soyuz',
        launchVehicle: 'Soyuz',
        launchSite: 'Baikonur Cosmodrome',
        role: 'ISS Commander',
        duration: '191 days',
        note: 'First woman to command the ISS.',
      },
      {
        name: 'Soyuz MS-03 / Expedition 50/51',
        launchDate: '2016-11-17',
        spacecraft: 'Soyuz',
        launchVehicle: 'Soyuz',
        launchSite: 'Baikonur Cosmodrome',
        role: 'ISS Commander (Expedition 51)',
        duration: '289 days',
      },
      {
        name: 'Axiom Mission 2',
        launchDate: '2023-05-21',
        spacecraft: 'Crew Dragon',
        launchVehicle: 'Falcon 9',
        launchSite: 'Kennedy Space Center',
        role: 'Commander',
        duration: '8 days',
      },
    ],
  },
  {
    id: 'scott-kelly',
    name: 'Scott Kelly',
    agency: 'NASA',
    agencyLinkId: 'nasa',
    nationality: 'United States',
    status: 'RETIRED',
    selectionYear: 1996,
    spacecraftFlown: ['Space Shuttle', 'Soyuz'],
    launchVehiclesFlown: ['Space Shuttle', 'Soyuz'],
    launchSites: ['Kennedy Space Center', 'Baikonur Cosmodrome'],
    spacewalks: { count: 3, totalTime: '12 hours 1 minute' },
    missions: [
      {
        name: 'STS-103',
        launchDate: '1999-12-19',
        spacecraft: 'Space Shuttle Discovery',
        launchVehicle: 'Space Shuttle',
        launchSite: 'Kennedy Space Center',
        role: 'Pilot',
        duration: '7 days 23 hours',
      },
      {
        name: 'STS-118',
        launchDate: '2007-08-08',
        spacecraft: 'Space Shuttle Endeavour',
        launchVehicle: 'Space Shuttle',
        launchSite: 'Kennedy Space Center',
        role: 'Commander',
        duration: '12 days 17 hours',
      },
      {
        name: 'Soyuz TMA-18M / Expedition 43/44/45/46 ("Year in Space")',
        launchDate: '2015-03-27',
        spacecraft: 'Soyuz',
        launchVehicle: 'Soyuz',
        launchSite: 'Baikonur Cosmodrome',
        role: 'ISS Commander (Expedition 46)',
        duration: '340 days',
        note: 'Longest single spaceflight by a NASA astronaut at the time.',
      },
    ],
  },
  {
    id: 'christina-koch',
    name: 'Christina Koch',
    agency: 'NASA',
    agencyLinkId: 'nasa',
    nationality: 'United States',
    status: 'ACTIVE',
    selectionYear: 2013,
    spacecraftFlown: ['Soyuz'],
    launchVehiclesFlown: ['Soyuz'],
    launchSites: ['Baikonur Cosmodrome'],
    spacewalks: { count: 6, totalTime: '42 hours 15 minutes' },
    missions: [
      {
        name: 'Soyuz MS-12 / Expedition 59/60/61',
        launchDate: '2019-03-14',
        spacecraft: 'Soyuz',
        launchVehicle: 'Soyuz',
        launchSite: 'Baikonur Cosmodrome',
        role: 'Flight Engineer',
        duration: '328 days',
        note: 'Longest single spaceflight by a woman at the time; part of the first all-female spacewalk with Jessica Meir.',
      },
    ],
  },
  {
    id: 'samantha-cristoforetti',
    name: 'Samantha Cristoforetti',
    agency: 'European Space Agency',
    agencyLinkId: 'esa',
    nationality: 'Italy',
    status: 'ACTIVE',
    selectionYear: 2009,
    spacecraftFlown: ['Soyuz', 'Crew Dragon'],
    launchVehiclesFlown: ['Soyuz', 'Falcon 9'],
    launchSites: ['Baikonur Cosmodrome', 'Kennedy Space Center'],
    spacewalks: { count: 1, totalTime: '7 hours 5 minutes' },
    missions: [
      {
        name: 'Soyuz TMA-15M / Expedition 42/43',
        launchDate: '2014-11-23',
        spacecraft: 'Soyuz',
        launchVehicle: 'Soyuz',
        launchSite: 'Baikonur Cosmodrome',
        role: 'Flight Engineer',
        duration: '199 days 16 hours',
        note: 'Longest single spaceflight by a woman at the time of return.',
      },
      {
        name: 'Crew-4 / Expedition 67/68',
        launchDate: '2022-04-27',
        spacecraft: 'Crew Dragon',
        launchVehicle: 'Falcon 9',
        launchSite: 'Kennedy Space Center',
        role: 'ISS Commander (Expedition 68)',
        duration: '170 days',
        note: 'First European woman to command the ISS.',
      },
    ],
  },
  {
    id: 'tim-peake',
    name: 'Tim Peake',
    agency: 'European Space Agency',
    agencyLinkId: 'esa',
    nationality: 'United Kingdom',
    status: 'RETIRED',
    selectionYear: 2009,
    spacecraftFlown: ['Soyuz'],
    launchVehiclesFlown: ['Soyuz'],
    launchSites: ['Baikonur Cosmodrome'],
    spacewalks: { count: 1, totalTime: '4 hours 43 minutes' },
    missions: [
      {
        name: 'Soyuz TMA-19M / Expedition 46/47',
        launchDate: '2015-12-15',
        spacecraft: 'Soyuz',
        launchVehicle: 'Soyuz',
        launchSite: 'Baikonur Cosmodrome',
        role: 'Flight Engineer',
        duration: '186 days',
        note: 'First British ESA astronaut on the ISS.',
      },
    ],
  },
  {
    id: 'thomas-pesquet',
    name: 'Thomas Pesquet',
    agency: 'European Space Agency',
    agencyLinkId: 'esa',
    nationality: 'France',
    status: 'ACTIVE',
    selectionYear: 2009,
    spacecraftFlown: ['Soyuz', 'Crew Dragon'],
    launchVehiclesFlown: ['Soyuz', 'Falcon 9'],
    launchSites: ['Baikonur Cosmodrome', 'Kennedy Space Center'],
    spacewalks: { count: 4, totalTime: '23 hours 24 minutes' },
    missions: [
      {
        name: 'Soyuz MS-03 / Expedition 50/51',
        launchDate: '2016-11-17',
        spacecraft: 'Soyuz',
        launchVehicle: 'Soyuz',
        launchSite: 'Baikonur Cosmodrome',
        role: 'Flight Engineer',
        duration: '196 days',
      },
      {
        name: 'Crew-2 / Expedition 65',
        launchDate: '2021-04-23',
        spacecraft: 'Crew Dragon',
        launchVehicle: 'Falcon 9',
        launchSite: 'Kennedy Space Center',
        role: 'ISS Commander (Expedition 65)',
        duration: '199 days',
        note: 'First French astronaut to command the ISS.',
      },
    ],
  },
  {
    id: 'rakesh-sharma',
    name: 'Rakesh Sharma',
    agency: 'Intercosmos (Soviet–Indian mission)',
    agencyLinkId: null,
    nationality: 'India',
    status: 'RETIRED',
    selectionYear: 1982,
    spacecraftFlown: ['Soyuz'],
    launchVehiclesFlown: ['Soyuz'],
    launchSites: ['Baikonur Cosmodrome'],
    spacewalks: { count: 0, totalTime: null },
    missions: [
      {
        name: 'Soyuz T-11',
        launchDate: '1984-04-03',
        spacecraft: 'Soyuz',
        launchVehicle: 'Soyuz',
        launchSite: 'Baikonur Cosmodrome',
        role: 'Cosmonaut Researcher',
        duration: '7 days 21 hours 40 minutes',
        note: 'First Indian citizen in space, flown under the Soviet Intercosmos programme.',
      },
    ],
  },
  {
    id: 'yang-liwei',
    name: 'Yang Liwei',
    agency: 'CNSA',
    agencyLinkId: 'cnsa',
    nationality: 'China',
    status: 'RETIRED',
    selectionYear: 1998,
    spacecraftFlown: ['Shenzhou'],
    launchVehiclesFlown: ['Long March 2F'],
    launchSites: ['Jiuquan Satellite Launch Center'],
    spacewalks: { count: 0, totalTime: null },
    missions: [
      {
        name: 'Shenzhou 5',
        launchDate: '2003-10-15',
        spacecraft: 'Shenzhou',
        launchVehicle: 'Long March 2F',
        launchSite: 'Jiuquan Satellite Launch Center',
        role: 'Pilot',
        duration: '21 hours 22 minutes',
        note: 'First crewed Chinese spaceflight.',
      },
    ],
  },
  {
    id: 'liu-yang',
    name: 'Liu Yang',
    agency: 'CNSA',
    agencyLinkId: 'cnsa',
    nationality: 'China',
    status: 'ACTIVE',
    selectionYear: 2010,
    spacecraftFlown: ['Shenzhou'],
    launchVehiclesFlown: ['Long March 2F'],
    launchSites: ['Jiuquan Satellite Launch Center'],
    spacewalks: { count: 0, totalTime: null },
    missions: [
      {
        name: 'Shenzhou 9',
        launchDate: '2012-06-16',
        spacecraft: 'Shenzhou',
        launchVehicle: 'Long March 2F',
        launchSite: 'Jiuquan Satellite Launch Center',
        role: 'Mission Specialist',
        duration: '12 days 15 hours',
        note: 'First Chinese woman in space.',
      },
      {
        name: 'Shenzhou 14',
        launchDate: '2022-06-05',
        spacecraft: 'Shenzhou',
        launchVehicle: 'Long March 2F',
        launchSite: 'Jiuquan Satellite Launch Center',
        role: 'Mission Specialist',
        duration: '183 days',
      },
    ],
  },
  {
    id: 'wang-yaping',
    name: 'Wang Yaping',
    agency: 'CNSA',
    agencyLinkId: 'cnsa',
    nationality: 'China',
    status: 'ACTIVE',
    selectionYear: 2010,
    spacecraftFlown: ['Shenzhou'],
    launchVehiclesFlown: ['Long March 2F'],
    launchSites: ['Jiuquan Satellite Launch Center'],
    spacewalks: { count: 1, totalTime: '6 hours 25 minutes' },
    missions: [
      {
        name: 'Shenzhou 10',
        launchDate: '2013-06-11',
        spacecraft: 'Shenzhou',
        launchVehicle: 'Long March 2F',
        launchSite: 'Jiuquan Satellite Launch Center',
        role: 'Mission Specialist',
        duration: '14 days 14 hours',
      },
      {
        name: 'Shenzhou 13',
        launchDate: '2021-10-15',
        spacecraft: 'Shenzhou',
        launchVehicle: 'Long March 2F',
        launchSite: 'Jiuquan Satellite Launch Center',
        role: 'Mission Specialist',
        duration: '183 days',
        note: 'First Chinese woman to perform a spacewalk.',
      },
    ],
  },
  {
    id: 'koichi-wakata',
    name: 'Koichi Wakata',
    agency: 'JAXA',
    agencyLinkId: 'jaxa',
    nationality: 'Japan',
    status: 'RETIRED',
    selectionYear: 1992,
    spacecraftFlown: ['Space Shuttle', 'Soyuz', 'Crew Dragon'],
    launchVehiclesFlown: ['Space Shuttle', 'Soyuz', 'Falcon 9'],
    launchSites: ['Kennedy Space Center', 'Baikonur Cosmodrome'],
    spacewalks: { count: 0, totalTime: null },
    missions: [
      {
        name: 'STS-72',
        launchDate: '1996-01-11',
        spacecraft: 'Space Shuttle Endeavour',
        launchVehicle: 'Space Shuttle',
        launchSite: 'Kennedy Space Center',
        role: 'Mission Specialist',
        duration: '8 days 22 hours',
      },
      {
        name: 'STS-92',
        launchDate: '2000-10-11',
        spacecraft: 'Space Shuttle Discovery',
        launchVehicle: 'Space Shuttle',
        launchSite: 'Kennedy Space Center',
        role: 'Mission Specialist',
        duration: '12 days 21 hours',
      },
      {
        name: 'Soyuz TMA-13 / Expedition 18/19/20',
        launchDate: '2009-03-26',
        spacecraft: 'Soyuz',
        launchVehicle: 'Soyuz',
        launchSite: 'Baikonur Cosmodrome',
        role: 'Flight Engineer',
        duration: '137 days',
      },
      {
        name: 'Soyuz TMA-11M / Expedition 38/39',
        launchDate: '2013-11-07',
        spacecraft: 'Soyuz',
        launchVehicle: 'Soyuz',
        launchSite: 'Baikonur Cosmodrome',
        role: 'ISS Commander (Expedition 39)',
        duration: '188 days',
        note: 'First Japanese ISS commander.',
      },
      {
        name: 'Crew-5 / Expedition 68/69',
        launchDate: '2022-10-05',
        spacecraft: 'Crew Dragon',
        launchVehicle: 'Falcon 9',
        launchSite: 'Kennedy Space Center',
        role: 'Flight Engineer',
        duration: '157 days',
      },
    ],
  },
  {
    id: 'naoko-yamazaki',
    name: 'Naoko Yamazaki',
    agency: 'JAXA',
    agencyLinkId: 'jaxa',
    nationality: 'Japan',
    status: 'RETIRED',
    selectionYear: 1999,
    spacecraftFlown: ['Space Shuttle'],
    launchVehiclesFlown: ['Space Shuttle'],
    launchSites: ['Kennedy Space Center'],
    spacewalks: { count: 0, totalTime: null },
    missions: [
      {
        name: 'STS-131',
        launchDate: '2010-04-05',
        spacecraft: 'Space Shuttle Discovery',
        launchVehicle: 'Space Shuttle',
        launchSite: 'Kennedy Space Center',
        role: 'Mission Specialist',
        duration: '15 days 2 hours',
        note: 'Second Japanese woman in space.',
      },
    ],
  },
  {
    id: 'chris-hadfield',
    name: 'Chris Hadfield',
    agency: 'Canadian Space Agency',
    agencyLinkId: 'csa',
    nationality: 'Canada',
    status: 'RETIRED',
    selectionYear: 1992,
    spacecraftFlown: ['Space Shuttle', 'Soyuz'],
    launchVehiclesFlown: ['Space Shuttle', 'Soyuz'],
    launchSites: ['Kennedy Space Center', 'Baikonur Cosmodrome'],
    spacewalks: { count: 2, totalTime: '14 hours 54 minutes' },
    missions: [
      {
        name: 'STS-74',
        launchDate: '1995-11-12',
        spacecraft: 'Space Shuttle Atlantis',
        launchVehicle: 'Space Shuttle',
        launchSite: 'Kennedy Space Center',
        role: 'Mission Specialist',
        duration: '8 days 4 hours',
        note: 'First Canadian to visit Mir.',
      },
      {
        name: 'STS-100',
        launchDate: '2001-04-19',
        spacecraft: 'Space Shuttle Endeavour',
        launchVehicle: 'Space Shuttle',
        launchSite: 'Kennedy Space Center',
        role: 'Mission Specialist',
        duration: '11 days 21 hours',
        note: 'First Canadian to perform a spacewalk.',
      },
      {
        name: 'Soyuz TMA-07M / Expedition 34/35',
        launchDate: '2012-12-19',
        spacecraft: 'Soyuz',
        launchVehicle: 'Soyuz',
        launchSite: 'Baikonur Cosmodrome',
        role: 'ISS Commander (Expedition 35)',
        duration: '146 days',
        note: 'First Canadian to command the ISS.',
      },
    ],
  },
  {
    id: 'roberta-bondar',
    name: 'Roberta Bondar',
    agency: 'Canadian Space Agency',
    agencyLinkId: 'csa',
    nationality: 'Canada',
    status: 'RETIRED',
    selectionYear: 1983,
    spacecraftFlown: ['Space Shuttle'],
    launchVehiclesFlown: ['Space Shuttle'],
    launchSites: ['Kennedy Space Center'],
    spacewalks: { count: 0, totalTime: null },
    missions: [
      {
        name: 'STS-42',
        launchDate: '1992-01-22',
        spacecraft: 'Space Shuttle Discovery',
        launchVehicle: 'Space Shuttle',
        launchSite: 'Kennedy Space Center',
        role: 'Payload Specialist',
        duration: '8 days 1 hour',
        note: 'First Canadian woman in space.',
      },
    ],
  },
];
