// Celestial Database — data only. No UI, no calculations here so the
// dataset can grow (new object types, new entries) without touching
// CelestialDatabase.js or the 3D viewer.
//
// Every numeric/text field below is a real published value. Where a value
// is not reliably known, it is left `null` and the UI renders
// "DATA UNAVAILABLE" instead of guessing.

export const OBJECT_TYPES = [
  'PLANETS',
  'DWARF PLANETS',
  'MOONS',
  'ASTEROIDS',
  'COMETS',
  'EXOPLANETS',
  'NEBULAE',
  'GALAXIES',
  'STAR CLUSTERS',
  'BLACK HOLES',
];

// 3D render hint per object — tells CelestialViewer.js how to represent the
// object when no external model/texture is available.
//   'rocky'      -> procedural rocky sphere
//   'gas-giant'  -> banded gas-giant sphere
//   'ringed'     -> gas-giant sphere + ring geometry
//   'ice'        -> pale icy sphere
//   'irregular'  -> lumpy non-spherical procedural mesh (asteroids/comets)
//   'accretion'  -> black-hole style disc + event-horizon visualization
//   'none'       -> no meaningful 3D representation (nebulae/galaxies/clusters)

export const CELESTIAL_OBJECTS = [
  {
    id: 'mercury',
    name: 'MERCURY',
    altNames: ['Sol I'],
    type: 'PLANETS',
    domain: 'SOLAR SYSTEM',
    catalog: null,
    description: 'The smallest and innermost planet of the Solar System, with a heavily cratered surface similar to the Moon.',
    render: { kind: 'rocky', baseColor: '#9c9186', roughColor: '#6b6259', craters: true },
    data: {
      diameterKm: 4879,
      massKg: '3.30 × 10^23',
      gravityMs2: 3.7,
      distanceFromSunKm: 57909000,
      orbitalPeriodDays: 88,
      rotationPeriodHours: 1407.6,
      avgTemperatureC: 167,
      moons: 0,
      atmosphere: 'Negligible (exosphere of O2, Na, H2, He, K)',
      discovery: 'Known since antiquity',
    },
    related: [],
  },
  {
    id: 'venus',
    name: 'VENUS',
    altNames: ['Sol II'],
    type: 'PLANETS',
    domain: 'SOLAR SYSTEM',
    catalog: null,
    description: 'The second planet from the Sun, with a thick carbon dioxide atmosphere producing a runaway greenhouse effect.',
    render: { kind: 'rocky', baseColor: '#d9b98a', roughColor: '#b8925c' },
    data: {
      diameterKm: 12104,
      massKg: '4.87 × 10^24',
      gravityMs2: 8.87,
      distanceFromSunKm: 108200000,
      orbitalPeriodDays: 224.7,
      rotationPeriodHours: -5832.5,
      avgTemperatureC: 464,
      moons: 0,
      atmosphere: '96.5% CO2, 3.5% N2, sulfuric acid clouds',
      discovery: 'Known since antiquity',
    },
    related: [],
  },
  {
    id: 'earth',
    name: 'EARTH',
    altNames: ['Sol III', 'Terra'],
    type: 'PLANETS',
    domain: 'SOLAR SYSTEM',
    catalog: null,
    description: 'The third planet from the Sun and the only known astronomical object to harbor life.',
    render: { kind: 'rocky', baseColor: '#2f6fb0', roughColor: '#3f7d3a' },
    data: {
      diameterKm: 12742,
      massKg: '5.97 × 10^24',
      gravityMs2: 9.81,
      distanceFromSunKm: 149600000,
      orbitalPeriodDays: 365.25,
      rotationPeriodHours: 23.93,
      avgTemperatureC: 15,
      moons: 1,
      atmosphere: '78% N2, 21% O2, 1% other',
      discovery: 'N/A',
    },
    related: [{ label: 'MOON', href: '#moon' }],
  },
  {
    id: 'mars',
    name: 'MARS',
    altNames: ['Sol IV', 'The Red Planet'],
    type: 'PLANETS',
    domain: 'SOLAR SYSTEM',
    catalog: null,
    description: 'The fourth planet from the Sun, a cold desert world with iron-oxide-rich soil giving it a reddish appearance.',
    render: { kind: 'rocky', baseColor: '#b1502f', roughColor: '#7a3620' },
    data: {
      diameterKm: 6779,
      massKg: '6.42 × 10^23',
      gravityMs2: 3.71,
      distanceFromSunKm: 227900000,
      orbitalPeriodDays: 687,
      rotationPeriodHours: 24.62,
      avgTemperatureC: -65,
      moons: 2,
      atmosphere: '95% CO2, 3% N2, 1.6% Ar',
      discovery: 'Known since antiquity',
    },
    related: [
      { label: 'ROCKET DATABASE', href: '/rocket-database' },
    ],
  },
  {
    id: 'jupiter',
    name: 'JUPITER',
    altNames: ['Sol V'],
    type: 'PLANETS',
    domain: 'SOLAR SYSTEM',
    catalog: null,
    description: 'The largest planet in the Solar System, a gas giant composed primarily of hydrogen and helium.',
    render: { kind: 'gas-giant', baseColor: '#c8a27a', bandColor: '#8f6a4a' },
    data: {
      diameterKm: 139820,
      massKg: '1.90 × 10^27',
      gravityMs2: 24.79,
      distanceFromSunKm: 778500000,
      orbitalPeriodDays: 4333,
      rotationPeriodHours: 9.93,
      avgTemperatureC: -110,
      moons: 95,
      atmosphere: '90% H2, 10% He',
      discovery: 'Known since antiquity',
    },
    related: [],
  },
  {
    id: 'saturn',
    name: 'SATURN',
    altNames: ['Sol VI'],
    type: 'PLANETS',
    domain: 'SOLAR SYSTEM',
    catalog: null,
    description: 'Known for its extensive ring system, Saturn is the second-largest planet, a gas giant of hydrogen and helium.',
    render: { kind: 'ringed', baseColor: '#d9c48a', bandColor: '#a8925e', ringColor: '#c9bfa0' },
    data: {
      diameterKm: 116460,
      massKg: '5.68 × 10^26',
      gravityMs2: 10.44,
      distanceFromSunKm: 1434000000,
      orbitalPeriodDays: 10756,
      rotationPeriodHours: 10.7,
      avgTemperatureC: -140,
      moons: 146,
      atmosphere: '96% H2, 3% He',
      discovery: 'Known since antiquity',
    },
    related: [],
  },
  {
    id: 'uranus',
    name: 'URANUS',
    altNames: ['Sol VII'],
    type: 'PLANETS',
    domain: 'SOLAR SYSTEM',
    catalog: null,
    description: 'An ice giant with a pale cyan color from atmospheric methane, notable for rotating on its side.',
    render: { kind: 'ice', baseColor: '#a9d8d6', roughColor: '#7fb8b5' },
    data: {
      diameterKm: 50724,
      massKg: '8.68 × 10^25',
      gravityMs2: 8.69,
      distanceFromSunKm: 2871000000,
      orbitalPeriodDays: 30687,
      rotationPeriodHours: -17.24,
      avgTemperatureC: -195,
      moons: 28,
      atmosphere: '83% H2, 15% He, 2% CH4',
      discovery: 'William Herschel, 1781',
    },
    related: [],
  },
  {
    id: 'neptune',
    name: 'NEPTUNE',
    altNames: ['Sol VIII'],
    type: 'PLANETS',
    domain: 'SOLAR SYSTEM',
    catalog: null,
    description: 'The most distant known planet in the Solar System, an ice giant with the fastest winds recorded.',
    render: { kind: 'ice', baseColor: '#3f5fd9', roughColor: '#2a3fa8' },
    data: {
      diameterKm: 49244,
      massKg: '1.02 × 10^26',
      gravityMs2: 11.15,
      distanceFromSunKm: 4495000000,
      orbitalPeriodDays: 60190,
      rotationPeriodHours: 16.11,
      avgTemperatureC: -200,
      moons: 16,
      atmosphere: '80% H2, 19% He, 1% CH4',
      discovery: 'Johann Galle, 1846',
    },
    related: [],
  },
  {
    id: 'pluto',
    name: 'PLUTO',
    altNames: ['134340 Pluto'],
    type: 'DWARF PLANETS',
    domain: 'SOLAR SYSTEM',
    catalog: '134340',
    description: 'The largest known dwarf planet in the Solar System, located in the Kuiper Belt.',
    render: { kind: 'ice', baseColor: '#c9b8a0', roughColor: '#9c8a6e', craters: true },
    data: {
      diameterKm: 2377,
      massKg: '1.30 × 10^22',
      gravityMs2: 0.62,
      distanceFromSunKm: 5906000000,
      orbitalPeriodDays: 90560,
      rotationPeriodHours: -153.3,
      avgTemperatureC: -225,
      moons: 5,
      atmosphere: 'Thin N2, CH4, CO (seasonal)',
      discovery: 'Clyde Tombaugh, 1930',
    },
    related: [],
  },
  {
    id: 'moon',
    name: 'THE MOON',
    altNames: ['Luna'],
    type: 'MOONS',
    domain: 'SOLAR SYSTEM',
    catalog: null,
    description: "Earth's only natural satellite and the fifth-largest moon in the Solar System.",
    render: { kind: 'rocky', baseColor: '#a8a8a8', roughColor: '#6f6f6f', craters: true },
    data: {
      diameterKm: 3474,
      massKg: '7.35 × 10^22',
      gravityMs2: 1.62,
      distanceFromSunKm: null,
      orbitalPeriodDays: 27.3,
      rotationPeriodHours: 655.7,
      avgTemperatureC: -20,
      moons: 0,
      atmosphere: 'Negligible (exosphere)',
      discovery: 'N/A',
    },
    related: [{ label: 'EARTH', href: '#earth' }],
  },
  {
    id: 'europa',
    name: 'EUROPA',
    altNames: ['Jupiter II'],
    type: 'MOONS',
    domain: 'SOLAR SYSTEM',
    catalog: null,
    description: "One of Jupiter's Galilean moons, with a smooth icy surface concealing a subsurface liquid-water ocean.",
    render: { kind: 'ice', baseColor: '#d8c9a8', roughColor: '#a89870' },
    data: {
      diameterKm: 3122,
      massKg: '4.80 × 10^22',
      gravityMs2: 1.31,
      distanceFromSunKm: null,
      orbitalPeriodDays: 3.55,
      rotationPeriodHours: 85.2,
      avgTemperatureC: -160,
      moons: 0,
      atmosphere: 'Trace O2',
      discovery: 'Galileo Galilei, 1610',
    },
    related: [{ label: 'JUPITER', href: '#jupiter' }],
  },
  {
    id: 'ceres',
    name: 'CERES',
    altNames: ['1 Ceres'],
    type: 'DWARF PLANETS',
    domain: 'SOLAR SYSTEM',
    catalog: '1',
    description: 'The largest object in the asteroid belt and the only dwarf planet located in the inner Solar System.',
    render: { kind: 'irregular', baseColor: '#8a8478' },
    data: {
      diameterKm: 940,
      massKg: '9.39 × 10^20',
      gravityMs2: 0.28,
      distanceFromSunKm: 413700000,
      orbitalPeriodDays: 1682,
      rotationPeriodHours: 9.07,
      avgTemperatureC: -105,
      moons: 0,
      atmosphere: 'None (trace water vapor)',
      discovery: 'Giuseppe Piazzi, 1801',
    },
    related: [],
  },
  {
    id: 'bennu',
    name: 'BENNU',
    altNames: ['101955 Bennu'],
    type: 'ASTEROIDS',
    domain: 'SOLAR SYSTEM',
    catalog: '101955',
    description: 'A carbonaceous near-Earth asteroid, sample-return target of NASA\u2019s OSIRIS-REx mission.',
    render: { kind: 'irregular', baseColor: '#3a3632' },
    data: {
      diameterKm: 0.49,
      orbitalPeriodDays: 436,
      semiMajorAxisAu: 1.126,
      classification: 'Apollo near-Earth asteroid, B-type',
      rotationPeriodHours: 4.3,
      discovery: 'LINEAR survey, 1999',
    },
    related: [],
  },
  {
    id: 'halley',
    name: "HALLEY'S COMET",
    altNames: ['1P/Halley'],
    type: 'COMETS',
    domain: 'SOLAR SYSTEM',
    catalog: '1P',
    description: 'The most famous periodic comet, visible from Earth every 75-76 years.',
    render: { kind: 'irregular', baseColor: '#4a4a52' },
    data: {
      orbitalPeriodDays: 27759,
      perihelionAu: 0.586,
      aphelionAu: 35.1,
      composition: 'Water ice, dust, CO, CO2, ammonia, methane',
      discovery: 'Recorded since 240 BC; Edmond Halley predicted its return in 1705',
    },
    related: [],
  },
  {
    id: 'kepler-452b',
    name: 'KEPLER-452B',
    altNames: [],
    type: 'EXOPLANETS',
    domain: 'DEEP SPACE',
    catalog: 'KOI-7016.01',
    description: 'A super-Earth exoplanet orbiting within the habitable zone of a Sun-like star.',
    render: { kind: 'rocky', baseColor: '#5a7d5a', roughColor: '#3f5f42' },
    data: {
      hostStar: 'Kepler-452',
      discoveryYear: 2015,
      orbitalPeriodDays: 385,
      distanceLy: 1800,
      radiusEarth: 1.63,
      massEarth: null,
      discoveryMethod: 'Transit (Kepler Space Telescope)',
    },
    related: [],
  },
  {
    id: 'proxima-b',
    name: 'PROXIMA CENTAURI B',
    altNames: ['Proxima b'],
    type: 'EXOPLANETS',
    domain: 'DEEP SPACE',
    catalog: null,
    description: "An Earth-sized exoplanet orbiting Proxima Centauri, the closest known star to the Sun.",
    render: { kind: 'rocky', baseColor: '#8a5a4a', roughColor: '#6b4438' },
    data: {
      hostStar: 'Proxima Centauri',
      discoveryYear: 2016,
      orbitalPeriodDays: 11.2,
      distanceLy: 4.24,
      radiusEarth: 1.07,
      massEarth: 1.17,
      discoveryMethod: 'Radial velocity',
    },
    related: [],
  },
  {
    id: 'sagittarius-a',
    name: 'SAGITTARIUS A*',
    altNames: ['Sgr A*'],
    type: 'BLACK HOLES',
    domain: 'DEEP SPACE',
    catalog: null,
    description: 'The supermassive black hole at the center of the Milky Way galaxy.',
    render: { kind: 'accretion', baseColor: '#000000', diskColor: '#e8a35a' },
    data: {
      massSolar: '4.15 million',
      distanceLy: 26000,
      type: 'Supermassive black hole',
      hostGalaxy: 'Milky Way',
      discovery: 'Inferred from stellar orbits; imaged by EHT in 2022',
    },
    related: [],
  },
  {
    id: 'm87',
    name: 'M87*',
    altNames: ['Messier 87 black hole'],
    type: 'BLACK HOLES',
    domain: 'DEEP SPACE',
    catalog: 'M87*',
    description: 'The first black hole ever directly imaged, at the center of galaxy Messier 87.',
    render: { kind: 'accretion', baseColor: '#000000', diskColor: '#f0c070' },
    data: {
      massSolar: '6.5 billion',
      distanceLy: 53000000,
      type: 'Supermassive black hole',
      hostGalaxy: 'Messier 87',
      discovery: 'Imaged by Event Horizon Telescope, 2019',
    },
    related: [],
  },
  {
    id: 'andromeda',
    name: 'ANDROMEDA GALAXY',
    altNames: ['M31', 'NGC 224'],
    type: 'GALAXIES',
    domain: 'DEEP SPACE',
    catalog: 'M31',
    description: 'The nearest large galaxy to the Milky Way, on a collision course with our galaxy in roughly 4.5 billion years.',
    render: { kind: 'none' },
    data: {
      type: 'Barred spiral galaxy',
      distanceLy: 2500000,
      diameterLy: 220000,
      discovery: 'Recorded since antiquity; first studied telescopically by Simon Marius, 1612',
    },
    related: [],
  },
  {
    id: 'orion-nebula',
    name: 'ORION NEBULA',
    altNames: ['M42', 'NGC 1976'],
    type: 'NEBULAE',
    domain: 'DEEP SPACE',
    catalog: 'M42',
    description: 'A diffuse emission nebula and stellar nursery, one of the brightest nebulae visible to the naked eye.',
    render: { kind: 'none' },
    data: {
      type: 'Emission/reflection nebula, stellar nursery',
      distanceLy: 1344,
      diameterLy: 24,
      discovery: 'Recorded since antiquity; telescopically documented by Nicolas-Claude Fabri de Peiresc, 1610',
    },
    related: [],
  },
  {
    id: 'pleiades',
    name: 'THE PLEIADES',
    altNames: ['M45', 'Seven Sisters'],
    type: 'STAR CLUSTERS',
    domain: 'DEEP SPACE',
    catalog: 'M45',
    description: 'An open star cluster of young, hot B-type stars, among the closest clusters to Earth.',
    render: { kind: 'none' },
    data: {
      type: 'Open star cluster',
      distanceLy: 444,
      ageYears: '75-150 million',
      discovery: 'Known since antiquity',
    },
    related: [],
  },
];
